// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import blauwvleugelsprinkhaan from './blauwvleugelsprinkhaan.webp';
import boomsprinkhaan from './boomsprinkhaan.webp';
import bramensprinkhaan from './bramensprinkhaan.webp';
import bruineSprinkhaan from './bruine-sprinkhaan.webp';
import doornsprinkhaan from './doornsprinkhaan.webp';
import greppelsprinkhaan from './greppelsprinkhaan.webp';
import groteGroeneSabelsprinkhaan from './grote-groene-sabelsprinkhaan.webp';
import huiskrekel from './huiskrekel.webp';
import krasser from './krasser.webp';
import krekel from './krekel.webp';
import moerassprinkhaan from './moerassprinkhaan.webp';
import ratelaar from './ratelaar.webp';
import sprinkhaan from './sprinkhaan.webp';
import struiksprinkhaan from './struiksprinkhaan.webp';
import treksprinkhaan from './treksprinkhaan.webp';
import veenmol from './veenmol.webp';
import veldkrekel from './veldkrekel.webp';

export const grasshoppersAndCrickets: WordTopic = {
  slug: 'grasshoppers-and-crickets',
  title: 'Grasshoppers and crickets',
  dutchTitle: 'Sprinkhanen en krekels',
  description: 'The jumpers and the singers of the summer meadow.',
  entries: [
    {
      slug: 'sprinkhaan',
      dutch: 'de sprinkhaan',
      english: 'the grasshopper',
      image: sprinkhaan,
      audio: '/audio/words/insects/grasshoppers-and-crickets/sprinkhaan.m4a',
      credit: {
        author: 'http://www.birdphotos.com',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: 'American_Bird_Grasshopper.jpg',
      },
    },
    {
      slug: 'grote-groene-sabelsprinkhaan',
      dutch: 'de grote groene sabelsprinkhaan',
      english: 'the great green bush-cricket',
      image: groteGroeneSabelsprinkhaan,
      audio: '/audio/words/insects/grasshoppers-and-crickets/grote-groene-sabelsprinkhaan.m4a',
      credit: {
        author: 'Didier Descouens',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: '(MHNT)_Tettigonia_viridissima_on_Avena_fatua.jpg',
      },
    },
    {
      slug: 'boomsprinkhaan',
      dutch: 'de boomsprinkhaan',
      english: 'the oak bush-cricket',
      image: boomsprinkhaan,
      audio: '/audio/words/insects/grasshoppers-and-crickets/boomsprinkhaan.m4a',
      credit: {
        author: 'Entomart',
        license: 'Attribution',
        licenseUrl: '',
        file: 'Meconema_thalassinum01.jpg',
      },
    },
    {
      slug: 'bramensprinkhaan',
      dutch: 'de bramensprinkhaan',
      english: 'the dark bush-cricket',
      image: bramensprinkhaan,
      audio: '/audio/words/insects/grasshoppers-and-crickets/bramensprinkhaan.m4a',
      credit: {
        author: 'Hectonichus',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Tettigoniidae_-_Pholidoptera_griseoaptera.JPG',
      },
    },
    {
      slug: 'greppelsprinkhaan',
      dutch: 'de greppelsprinkhaan',
      english: "Roesel's bush-cricket",
      image: greppelsprinkhaan,
      audio: '/audio/words/insects/grasshoppers-and-crickets/greppelsprinkhaan.m4a',
      credit: {
        author: 'Richard Bartz, Munich aka Makro Freak',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Metrioptera_roeseli_male_Richard_Bartz.jpg',
      },
    },
    {
      slug: 'struiksprinkhaan',
      dutch: 'de struiksprinkhaan',
      english: 'the speckled bush-cricket',
      image: struiksprinkhaan,
      audio: '/audio/words/insects/grasshoppers-and-crickets/struiksprinkhaan.m4a',
      credit: {
        author: 'Fritz Geller-Grimm',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Leptophyes_punctatissima_fg06.jpg',
      },
    },
    {
      slug: 'ratelaar',
      dutch: 'de ratelaar',
      english: 'the bow-winged grasshopper',
      image: ratelaar,
      audio: '/audio/words/insects/grasshoppers-and-crickets/ratelaar.m4a',
      credit: {
        author: 'G.-U. Tolkiehn',
        license: 'CC BY 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.5',
        file: 'Chorthippus_biguttulus_f_8835.jpg',
      },
    },
    {
      slug: 'bruine-sprinkhaan',
      dutch: 'de bruine sprinkhaan',
      english: 'the field grasshopper',
      image: bruineSprinkhaan,
      audio: '/audio/words/insects/grasshoppers-and-crickets/bruine-sprinkhaan.m4a',
      credit: {
        author: 'Alvesgaspar',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Grasshopper_April_2008-3.jpg',
      },
    },
    {
      slug: 'krasser',
      dutch: 'de krasser',
      english: 'the meadow grasshopper',
      image: krasser,
      audio: '/audio/words/insects/grasshoppers-and-crickets/krasser.m4a',
      credit: {
        author: 'G.-U. Tolkiehn',
        license: 'CC BY 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.5',
        file: 'Chorthippus_parallelus_1944.jpg',
      },
    },
    {
      slug: 'moerassprinkhaan',
      dutch: 'de moerassprinkhaan',
      english: 'the large marsh grasshopper',
      image: moerassprinkhaan,
      audio: '/audio/words/insects/grasshoppers-and-crickets/moerassprinkhaan.m4a',
      credit: {
        author: 'Aiwok',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Stethophyma_grossum_m1.JPG',
      },
    },
    {
      slug: 'blauwvleugelsprinkhaan',
      dutch: 'de blauwvleugelsprinkhaan',
      english: 'the blue-winged grasshopper',
      image: blauwvleugelsprinkhaan,
      audio: '/audio/words/insects/grasshoppers-and-crickets/blauwvleugelsprinkhaan.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Blue-winged_grasshopper_(Oedipoda_caerulescens)_male.jpg',
      },
    },
    {
      slug: 'doornsprinkhaan',
      dutch: 'de doornsprinkhaan',
      english: 'the groundhopper',
      image: doornsprinkhaan,
      audio: '/audio/words/insects/grasshoppers-and-crickets/doornsprinkhaan.m4a',
      credit: {
        author: 'Bj.schoenmakers',
        license: 'CC0',
        licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
        file: 'Tetrix_subulata_(Tetrigidae_sp.),_Elst_(Gld),_the_Netherlands.jpg',
      },
    },
    {
      slug: 'treksprinkhaan',
      dutch: 'de treksprinkhaan',
      english: 'the migratory locust',
      image: treksprinkhaan,
      audio: '/audio/words/insects/grasshoppers-and-crickets/treksprinkhaan.m4a',
      credit: {
        author: 'Jonathan Hornung',
        license: 'CC BY-SA 2.0 de',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/de/deed.en',
        file: 'Wanderheuschrecke-03.jpg',
      },
    },
    {
      slug: 'krekel',
      dutch: 'de krekel',
      english: 'the cricket',
      image: krekel,
      audio: '/audio/words/insects/grasshoppers-and-crickets/krekel.m4a',
      credit: {
        author: 'Didier Descouens',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Gryllus_campestris_MHNT.jpg',
      },
    },
    {
      slug: 'veldkrekel',
      dutch: 'de veldkrekel',
      english: 'the field cricket',
      image: veldkrekel,
      audio: '/audio/words/insects/grasshoppers-and-crickets/veldkrekel.m4a',
      credit: {
        author: 'Roberto Zanon',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Gryllus_campestris_3.jpg',
      },
    },
    {
      slug: 'huiskrekel',
      dutch: 'de huiskrekel',
      english: 'the house cricket',
      image: huiskrekel,
      audio: '/audio/words/insects/grasshoppers-and-crickets/huiskrekel.m4a',
      credit: {
        author: 'Geyersberg, Professor emeritus Hans Schneider',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Acheta_domesticus,_adultes_Weibchen.jpg',
      },
    },
    {
      slug: 'veenmol',
      dutch: 'de veenmol',
      english: 'the mole cricket',
      image: veenmol,
      audio: '/audio/words/insects/grasshoppers-and-crickets/veenmol.m4a',
      credit: {
        author: 'Eszter Kovács',
        license: 'CC BY-SA 2.0 de',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/de/deed.en',
        file: 'Gryllotalpa_gryllotalpa_vorne-oben.jpg',
      },
    },
  ],
};
