// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import alvleesklier from './alvleesklier.webp';
import blindedarm from './blindedarm.webp';
import buikvlies from './buikvlies.webp';
import darmvlok from './darmvlok.webp';
import dikkeDarm from './dikke-darm.webp';
import dunneDarm from './dunne-darm.webp';
import endeldarm from './endeldarm.webp';
import galblaas from './galblaas.webp';
import gehemelte from './gehemelte.webp';
import hoektand from './hoektand.webp';
import huig from './huig.webp';
import kies from './kies.webp';
import lever from './lever.webp';
import lip from './lip.webp';
import maag from './maag.webp';
import mond from './mond.webp';
import slokdarm from './slokdarm.webp';
import snijtand from './snijtand.webp';
import speekselklier from './speekselklier.webp';
import tand from './tand.webp';
import tandvlees from './tandvlees.webp';
import twaalfvingerigeDarm from './twaalfvingerige-darm.webp';
import verstandskies from './verstandskies.webp';
import wormvormigAanhangsel from './wormvormig-aanhangsel.webp';

export const digestion: WordTopic = {
  slug: 'digestion',
  title: 'Digestion',
  dutchTitle: 'Spijsvertering',
  description:
    'The road food travels, from de mond to de endeldarm, and the organs that help along the way.',
  entries: [
    {
      slug: 'mond',
      dutch: 'de mond',
      english: 'the mouth',
      image: mond,
      audio: '/audio/words/body/digestion/mond.m4a',
      credit: {
        author: 'Wikimedia Commons contributor',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Illu mouth.jpg',
      },
    },
    {
      slug: 'lip',
      dutch: 'de lip',
      english: 'the lip',
      image: lip,
      audio: '/audio/words/body/digestion/lip.m4a',
      credit: {
        author: 'PumpkinMan1943',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Lips_2023.jpg',
      },
    },
    {
      slug: 'tand',
      dutch: 'de tand',
      english: 'the tooth',
      image: tand,
      audio: '/audio/words/body/digestion/tand.m4a',
      credit: {
        author: 'User:Indolences',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Tooth Section.svg',
      },
    },
    {
      slug: 'snijtand',
      dutch: 'de snijtand',
      english: 'the incisor',
      image: snijtand,
      audio: '/audio/words/body/digestion/snijtand.m4a',
      credit: {
        author: 'dozenist',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: '06-10-06smile.jpg',
      },
    },
    {
      slug: 'hoektand',
      dutch: 'de hoektand',
      english: 'the canine tooth',
      image: hoektand,
      audio: '/audio/words/body/digestion/hoektand.m4a',
      credit: {
        author: 'Thirunavukkarasye-Raveendran',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Eckzahn in Fehlstellung wegen Platzmangel.jpg',
      },
    },
    {
      slug: 'kies',
      dutch: 'de kies',
      english: 'the molar',
      image: kies,
      audio: '/audio/words/body/digestion/kies.m4a',
      credit: {
        author: 'Gleam~commonswiki',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Lower_wisdom_tooth.jpg',
      },
    },
    {
      slug: 'verstandskies',
      dutch: 'de verstandskies',
      english: 'the wisdom tooth',
      image: verstandskies,
      audio: '/audio/words/body/digestion/verstandskies.m4a',
      credit: {
        author: 'M(e)ister Eiskalt; derivative work: Hic et nunc',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Weisheitszähne-1.jpg',
      },
    },
    {
      slug: 'tandvlees',
      dutch: 'het tandvlees',
      english: 'the gums',
      image: tandvlees,
      audio: '/audio/words/body/digestion/tandvlees.m4a',
      credit: {
        author: 'Dental_fluorosis.jpg: josconklin derivative work: Bobek',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Gingiva.jpg',
      },
    },
    {
      slug: 'gehemelte',
      dutch: 'het gehemelte',
      english: 'the palate',
      image: gehemelte,
      audio: '/audio/words/body/digestion/gehemelte.m4a',
      credit: {
        author: 'Pearson Scott Foresman',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Palate 2 (PSF).png',
      },
    },
    {
      slug: 'huig',
      dutch: 'de huig',
      english: 'the uvula',
      image: huig,
      audio: '/audio/words/body/digestion/huig.m4a',
      credit: {
        author: 'JonaLane',
        license: 'CC0',
        licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
        file: 'Uvula_of_an_adult.jpg',
      },
    },
    {
      slug: 'speekselklier',
      dutch: 'de speekselklier',
      english: 'the salivary gland',
      image: speekselklier,
      audio: '/audio/words/body/digestion/speekselklier.m4a',
      credit: {
        author: 'BruceBlaus',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: 'Blausen_0780_SalivaryGlands.png',
      },
    },
    {
      slug: 'slokdarm',
      dutch: 'de slokdarm',
      english: 'the oesophagus',
      image: slokdarm,
      audio: '/audio/words/body/digestion/slokdarm.m4a',
      credit: {
        author: 'Olek Remesz (wiki-pl: Orem, commons: Orem)',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Tractus_intestinalis_esophagus.svg',
      },
    },
    {
      slug: 'maag',
      dutch: 'de maag',
      english: 'the stomach',
      image: maag,
      audio: '/audio/words/body/digestion/maag.m4a',
      credit: {
        author: 'Henry Vandyke Carter',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Gray1046.svg',
      },
    },
    {
      slug: 'lever',
      dutch: 'de lever',
      english: 'the liver',
      image: lever,
      audio: '/audio/words/body/digestion/lever.m4a',
      credit: {
        author: 'Courtesy of NIAID Ryan Kissinger',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Human Liver (NIH BioArt 230).png',
      },
    },
    {
      slug: 'galblaas',
      dutch: 'de galblaas',
      english: 'the gallbladder',
      image: galblaas,
      audio: '/audio/words/body/digestion/galblaas.m4a',
      credit: {
        author: 'BruceBlaus',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Gallbladder_(organ).png',
      },
    },
    {
      slug: 'alvleesklier',
      dutch: 'de alvleesklier',
      english: 'the pancreas',
      image: alvleesklier,
      audio: '/audio/words/body/digestion/alvleesklier.m4a',
      credit: {
        author: 'BruceBlaus',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: 'Blausen_0699_PancreasAnatomy2.png',
      },
    },
    {
      slug: 'dunne-darm',
      dutch: 'de dunne darm',
      english: 'the small intestine',
      image: dunneDarm,
      audio: '/audio/words/body/digestion/dunne-darm.m4a',
      credit: {
        author: 'Olek Remesz (wiki-pl: Orem, commons: Orem)',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Tractus_intestinalis_intestinum_tenue.svg',
      },
    },
    {
      slug: 'twaalfvingerige-darm',
      dutch: 'de twaalfvingerige darm',
      english: 'the duodenum',
      image: twaalfvingerigeDarm,
      audio: '/audio/words/body/digestion/twaalfvingerige-darm.m4a',
      credit: {
        author: 'Olek Remesz (wiki-pl: Orem, commons: Orem)',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Tractus_intestinalis_duodenum.svg',
      },
    },
    {
      slug: 'darmvlok',
      dutch: 'de darmvlok',
      english: 'the intestinal villus',
      image: darmvlok,
      audio: '/audio/words/body/digestion/darmvlok.m4a',
      credit: {
        author: 'Snow93',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Intestinal villus simplified.svg',
      },
    },
    {
      slug: 'dikke-darm',
      dutch: 'de dikke darm',
      english: 'the large intestine',
      image: dikkeDarm,
      audio: '/audio/words/body/digestion/dikke-darm.m4a',
      credit: {
        author: 'Olek Remesz (wiki-pl: Orem, commons: Orem)',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Tractus_intestinalis_intestinum_crassum.svg',
      },
    },
    {
      slug: 'blindedarm',
      dutch: 'de blindedarm',
      english: 'the caecum',
      image: blindedarm,
      audio: '/audio/words/body/digestion/blindedarm.m4a',
      credit: {
        author: 'Olek Remesz (wiki-pl: Orem, commons: Orem)',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Tractus_intestinalis_cecum.svg',
      },
    },
    {
      slug: 'wormvormig-aanhangsel',
      dutch: 'het wormvormig aanhangsel',
      english: 'the appendix',
      image: wormvormigAanhangsel,
      audio: '/audio/words/body/digestion/wormvormig-aanhangsel.m4a',
      credit: {
        author: 'Olek Remesz (wiki-pl: Orem, commons: Orem)',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Tractus_intestinalis_appendix_vermiformis.svg',
      },
    },
    {
      slug: 'endeldarm',
      dutch: 'de endeldarm',
      english: 'the rectum',
      image: endeldarm,
      audio: '/audio/words/body/digestion/endeldarm.m4a',
      credit: {
        author: 'Armin Kübelbeck',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: 'Rectum_anatomy_en.svg',
      },
    },
    {
      slug: 'buikvlies',
      dutch: 'het buikvlies',
      english: 'the peritoneum',
      image: buikvlies,
      audio: '/audio/words/body/digestion/buikvlies.m4a',
      credit: {
        author: 'Henry Vandyke Carter',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Gray1035.png',
      },
    },
  ],
};
