// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordSection } from '@/features/words/types';

import { bodyParts } from './body-parts/body-parts';
import { breathing } from './breathing/breathing';
import { cellsAndTissues } from './cells-and-tissues/cells-and-tissues';
import { digestion } from './digestion/digestion';
import { glandsAndImmunity } from './glands-and-immunity/glands-and-immunity';
import { heartAndBlood } from './heart-and-blood/heart-and-blood';
import { kidneysAndReproduction } from './kidneys-and-reproduction/kidneys-and-reproduction';
import { nervousSystem } from './nervous-system/nervous-system';
import { senses } from './senses/senses';
import { skeletonAndMuscles } from './skeleton-and-muscles/skeleton-and-muscles';
import { skin } from './skin/skin';

export const body: WordSection = {
  slug: 'body',
  title: 'The human body',
  dutchTitle: 'Het lichaam',
  description: 'The body inside and out: body parts, senses, organs and the systems they form.',
  groups: [
    {
      title: 'On the outside',
      dutchTitle: 'Van buiten',
      topics: [bodyParts, senses, skin],
    },
    {
      title: 'On the inside',
      dutchTitle: 'Van binnen',
      topics: [
        skeletonAndMuscles,
        heartAndBlood,
        breathing,
        digestion,
        kidneysAndReproduction,
        nervousSystem,
        glandsAndImmunity,
      ],
    },
    {
      title: 'Building blocks',
      dutchTitle: 'Bouwstenen',
      topics: [cellsAndTissues],
    },
  ],
};
