// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import aziatischeHoornaar from './aziatische-hoornaar.webp';
import bijenwolf from './bijenwolf.webp';
import bladsnijdersmier from './bladsnijdersmier.webp';
import bladwesp from './bladwesp.webp';
import duitseWesp from './duitse-wesp.webp';
import faraomier from './faraomier.webp';
import franseVeldwesp from './franse-veldwesp.webp';
import galwesp from './galwesp.webp';
import geleWeidemier from './gele-weidemier.webp';
import gewoneWesp from './gewone-wesp.webp';
import goudwesp from './goudwesp.webp';
import graafwesp from './graafwesp.webp';
import hoornaar from './hoornaar.webp';
import mier from './mier.webp';
import reuzenhoutwesp from './reuzenhoutwesp.webp';
import rodeBosmier from './rode-bosmier.webp';
import sluipwesp from './sluipwesp.webp';
import vuurmier from './vuurmier.webp';
import wegmier from './wegmier.webp';
import wevermier from './wevermier.webp';

export const waspsAndAnts: WordTopic = {
  slug: 'wasps-and-ants',
  title: 'Wasps and ants',
  dutchTitle: 'Wespen en mieren',
  description: 'The ones with a narrow waist: wasps, hornets and the ants at your feet.',
  entries: [
    {
      slug: 'gewone-wesp',
      dutch: 'de gewone wesp',
      english: 'the common wasp',
      image: gewoneWesp,
      audio: '/audio/words/insects/wasps-and-ants/gewone-wesp.m4a',
      credit: {
        author: 'Magne Flåten',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Vespula_vulgaris-m.jpg',
      },
    },
    {
      slug: 'duitse-wesp',
      dutch: 'de Duitse wesp',
      english: 'the German wasp',
      image: duitseWesp,
      audio: '/audio/words/insects/wasps-and-ants/duitse-wesp.m4a',
      credit: {
        author: 'User:Fir0002',
        license: 'GFDL 1.2',
        licenseUrl: 'http://www.gnu.org/licenses/old-licenses/fdl-1.2.html',
        file: 'European_wasp_white_bg.jpg',
      },
    },
    {
      slug: 'hoornaar',
      dutch: 'de hoornaar',
      english: 'the hornet',
      image: hoornaar,
      audio: '/audio/words/insects/wasps-and-ants/hoornaar.m4a',
      credit: {
        author: 'Richard Bartz, Munich aka Makro Freak',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Vespa crabro germana with prey Richard Bartz Crop.jpg',
      },
    },
    {
      slug: 'aziatische-hoornaar',
      dutch: 'de Aziatische hoornaar',
      english: 'the Asian hornet',
      image: aziatischeHoornaar,
      audio: '/audio/words/insects/wasps-and-ants/aziatische-hoornaar.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Asian_hornet_(Vespa_velutina).jpg',
      },
    },
    {
      slug: 'franse-veldwesp',
      dutch: 'de Franse veldwesp',
      english: 'the European paper wasp',
      image: franseVeldwesp,
      audio: '/audio/words/insects/wasps-and-ants/franse-veldwesp.m4a',
      credit: {
        author: 'Judy Gallagher',
        license: 'CC BY 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
        file: 'European_Paper_Wasp_-_Polistes_dominula,_Saanichton,_British_Columbia,_August_5,_2016_(53552917108).jpg',
      },
    },
    {
      slug: 'bijenwolf',
      dutch: 'de bijenwolf',
      english: 'the bee wolf',
      image: bijenwolf,
      audio: '/audio/words/insects/wasps-and-ants/bijenwolf.m4a',
      credit: {
        author: 'Alvesgaspar',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Wasp_August_2007-12.jpg',
      },
    },
    {
      slug: 'sluipwesp',
      dutch: 'de sluipwesp',
      english: 'the ichneumon wasp',
      image: sluipwesp,
      audio: '/audio/words/insects/wasps-and-ants/sluipwesp.m4a',
      credit: {
        author: 'IronChris',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'IC_Ichneumonini.jpg',
      },
    },
    {
      slug: 'galwesp',
      dutch: 'de galwesp',
      english: 'the gall wasp',
      image: galwesp,
      audio: '/audio/words/insects/wasps-and-ants/galwesp.m4a',
      credit: {
        author: 'Judy Gallagher',
        license: 'CC BY 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
        file: 'Gall_Wasp_-_Cynipidae_family,_Leesylvania_State_Park,_Woodbridge,_Virginia.jpg',
      },
    },
    {
      slug: 'goudwesp',
      dutch: 'de goudwesp',
      english: 'the ruby-tailed wasp',
      image: goudwesp,
      audio: '/audio/words/insects/wasps-and-ants/goudwesp.m4a',
      credit: {
        author: 'Sven Damerow',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Gemeine_Goldwespe.jpg',
      },
    },
    {
      slug: 'bladwesp',
      dutch: 'de bladwesp',
      english: 'the sawfly',
      image: bladwesp,
      audio: '/audio/words/insects/wasps-and-ants/bladwesp.m4a',
      credit: {
        author: 'Guido Gerding',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'XN_Tenthredo_mesomela.jpg',
      },
    },
    {
      slug: 'reuzenhoutwesp',
      dutch: 'de reuzenhoutwesp',
      english: 'the giant woodwasp',
      image: reuzenhoutwesp,
      audio: '/audio/words/insects/wasps-and-ants/reuzenhoutwesp.m4a',
      credit: {
        author: 'Holger Gröschl',
        license: 'CC BY-SA 2.0 de',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/de/deed.en',
        file: 'Urocerus_gigas5.jpg',
      },
    },
    {
      slug: 'graafwesp',
      dutch: 'de graafwesp',
      english: 'the digger wasp',
      image: graafwesp,
      audio: '/audio/words/insects/wasps-and-ants/graafwesp.m4a',
      credit: {
        author: 'Muhammad Mahdi Karim',
        license: 'GFDL 1.2',
        licenseUrl: 'http://www.gnu.org/licenses/old-licenses/fdl-1.2.html',
        file: 'Tachysphex_specie_edit1.jpg',
      },
    },
    {
      slug: 'mier',
      dutch: 'de mier',
      english: 'the ant',
      image: mier,
      audio: '/audio/words/insects/wasps-and-ants/mier.m4a',
      credit: {
        author: 'Samantha Henneke from Seagrove, North Carolina, USA',
        license: 'CC BY 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
        file: 'Red_Ant_-_March_2025.jpg',
      },
    },
    {
      slug: 'rode-bosmier',
      dutch: 'de rode bosmier',
      english: 'the red wood ant',
      image: rodeBosmier,
      audio: '/audio/words/insects/wasps-and-ants/rode-bosmier.m4a',
      credit: {
        author: 'Richard Bartz, Munich Makro Freak',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'A_Formica_rufa_sideview.jpg',
      },
    },
    {
      slug: 'wegmier',
      dutch: 'de wegmier',
      english: 'the black garden ant',
      image: wegmier,
      audio: '/audio/words/insects/wasps-and-ants/wegmier.m4a',
      credit: {
        author: 'Katja Schulz from Washington, D. C., USA',
        license: 'CC BY 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
        file: 'Black_Garden_Ant_tending_Citrus_Mealybug_(16063538972).jpg',
      },
    },
    {
      slug: 'gele-weidemier',
      dutch: 'de gele weidemier',
      english: 'the yellow meadow ant',
      image: geleWeidemier,
      audio: '/audio/words/insects/wasps-and-ants/gele-weidemier.m4a',
      credit: {
        author: 'AJC1 from UK',
        license: 'CC BY-SA 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
        file: 'Angry_Ant_(Explored)_(31456859231).jpg',
      },
    },
    {
      slug: 'faraomier',
      dutch: 'de faraomier',
      english: 'the pharaoh ant',
      image: faraomier,
      audio: '/audio/words/insects/wasps-and-ants/faraomier.m4a',
      credit: {
        author: 'April Nobile',
        license: 'CC BY 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/4.0',
        file: 'Monomorium_pharaonis_casent0173986_profile_1.jpg',
      },
    },
    {
      slug: 'bladsnijdersmier',
      dutch: 'de bladsnijdersmier',
      english: 'the leafcutter ant',
      image: bladsnijdersmier,
      audio: '/audio/words/insects/wasps-and-ants/bladsnijdersmier.m4a',
      credit: {
        author: 'Pjt56',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Atta_cephalotes-pjt.jpg',
      },
    },
    {
      slug: 'wevermier',
      dutch: 'de wevermier',
      english: 'the weaver ant',
      image: wevermier,
      audio: '/audio/words/insects/wasps-and-ants/wevermier.m4a',
      credit: {
        author: 'Muhammad Mahdi Karim',
        license: 'GFDL 1.2',
        licenseUrl: 'http://www.gnu.org/licenses/old-licenses/fdl-1.2.html',
        file: 'Red_Weaver_Ant,_Oecophylla_smaragdina.jpg',
      },
    },
    {
      slug: 'vuurmier',
      dutch: 'de vuurmier',
      english: 'the fire ant',
      image: vuurmier,
      audio: '/audio/words/insects/wasps-and-ants/vuurmier.m4a',
      credit: {
        author: 'Scott Bauer, USDA ARS',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Fire_ants.jpg',
      },
    },
  ],
};
