// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import achillespees from './achillespees.webp';
import bekken from './bekken.webp';
import biceps from './biceps.webp';
import borstbeen from './borstbeen.webp';
import borstkas from './borstkas.webp';
import bot from './bot.webp';
import dijbeen from './dijbeen.webp';
import ellepijp from './ellepijp.webp';
import gewricht from './gewricht.webp';
import gewrichtsband from './gewrichtsband.webp';
import heiligbeen from './heiligbeen.webp';
import knieschijf from './knieschijf.webp';
import kraakbeen from './kraakbeen.webp';
import kuitbeen from './kuitbeen.webp';
import onderkaak from './onderkaak.webp';
import opperarmbeen from './opperarmbeen.webp';
import pees from './pees.webp';
import rib from './rib.webp';
import schedel from './schedel.webp';
import scheenbeen from './scheenbeen.webp';
import schouderblad from './schouderblad.webp';
import skelet from './skelet.webp';
import sleutelbeen from './sleutelbeen.webp';
import spaakbeen from './spaakbeen.webp';
import spier from './spier.webp';
import staartbeen from './staartbeen.webp';
import tussenwervelschijf from './tussenwervelschijf.webp';
import wervel from './wervel.webp';
import wervelkolom from './wervelkolom.webp';

export const skeletonAndMuscles: WordTopic = {
  slug: 'skeleton-and-muscles',
  title: 'Skeleton and muscles',
  dutchTitle: 'Skelet en spieren',
  description: 'What holds the body up and what moves it: bones, joints, muscles and tendons.',
  entries: [
    {
      slug: 'skelet',
      dutch: 'het skelet',
      english: 'the skeleton',
      image: skelet,
      audio: '/audio/words/body/skeleton-and-muscles/skelet.m4a',
      credit: {
        author: 'Sklmsta',
        license: 'CC0',
        licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
        file: 'Human-Skeleton.jpg',
      },
    },
    {
      slug: 'bot',
      dutch: 'het bot',
      english: 'the bone',
      image: bot,
      audio: '/audio/words/body/skeleton-and-muscles/bot.m4a',
      credit: {
        author: 'OpenStax College',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: '603 Anatomy of Long Bone.jpg',
      },
    },
    {
      slug: 'schedel',
      dutch: 'de schedel',
      english: 'the skull',
      image: schedel,
      audio: '/audio/words/body/skeleton-and-muscles/schedel.m4a',
      credit: {
        author: 'LadyofHats Mariana Ruiz Villarreal',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Human skull side bones numbered.svg',
      },
    },
    {
      slug: 'onderkaak',
      dutch: 'de onderkaak',
      english: 'the lower jaw',
      image: onderkaak,
      audio: '/audio/words/body/skeleton-and-muscles/onderkaak.m4a',
      credit: {
        author: 'MAKY.OREL',
        license: 'CC0',
        licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
        file: 'Cranium - mandibula (lateral view).jpg',
      },
    },
    {
      slug: 'wervelkolom',
      dutch: 'de wervelkolom',
      english: 'the spine',
      image: wervelkolom,
      audio: '/audio/words/body/skeleton-and-muscles/wervelkolom.m4a',
      credit: {
        author: 'Original: Arcadian Vector: Pixelsquid🎱',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Illu_vertebral_column.svg',
      },
    },
    {
      slug: 'wervel',
      dutch: 'de wervel',
      english: 'the vertebra',
      image: wervel,
      audio: '/audio/words/body/skeleton-and-muscles/wervel.m4a',
      credit: {
        author: 'Jmarchn',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Vertebra_Superior_View-en.svg',
      },
    },
    {
      slug: 'tussenwervelschijf',
      dutch: 'de tussenwervelschijf',
      english: 'the spinal disc',
      image: tussenwervelschijf,
      audio: '/audio/words/body/skeleton-and-muscles/tussenwervelschijf.m4a',
      credit: {
        author: 'Jmarchn',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: '716_Intervertebral_Disk.svg',
      },
    },
    {
      slug: 'rib',
      dutch: 'de rib',
      english: 'the rib',
      image: rib,
      audio: '/audio/words/body/skeleton-and-muscles/rib.m4a',
      credit: {
        author: 'MAKY.OREL',
        license: 'CC0',
        licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
        file: 'Costae_-_collection.jpg',
      },
    },
    {
      slug: 'borstkas',
      dutch: 'de borstkas',
      english: 'the rib cage',
      image: borstkas,
      audio: '/audio/words/body/skeleton-and-muscles/borstkas.m4a',
      credit: {
        author: 'Henry Vandyke Carter',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Gray112.png',
      },
    },
    {
      slug: 'borstbeen',
      dutch: 'het borstbeen',
      english: 'the breastbone',
      image: borstbeen,
      audio: '/audio/words/body/skeleton-and-muscles/borstbeen.m4a',
      credit: {
        author: 'Anatomography',
        license: 'CC BY-SA 2.1 jp',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en',
        file: 'Sternum_composition.png',
      },
    },
    {
      slug: 'sleutelbeen',
      dutch: 'het sleutelbeen',
      english: 'the collarbone',
      image: sleutelbeen,
      audio: '/audio/words/body/skeleton-and-muscles/sleutelbeen.m4a',
      credit: {
        author: 'Anatomography',
        license: 'CC BY-SA 2.1 jp',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en',
        file: 'Clavicle_-_anterior_view.png',
      },
    },
    {
      slug: 'schouderblad',
      dutch: 'het schouderblad',
      english: 'the shoulder blade',
      image: schouderblad,
      audio: '/audio/words/body/skeleton-and-muscles/schouderblad.m4a',
      credit: {
        author: 'LadyofHats Mariana Ruiz Villarreal',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Pectoral_girdle_front_diagram.svg',
      },
    },
    {
      slug: 'opperarmbeen',
      dutch: 'het opperarmbeen',
      english: 'the humerus',
      image: opperarmbeen,
      audio: '/audio/words/body/skeleton-and-muscles/opperarmbeen.m4a',
      credit: {
        author: 'Anatomography',
        license: 'CC BY-SA 2.1 jp',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en',
        file: 'Humerus_-_anterior_view.png',
      },
    },
    {
      slug: 'ellepijp',
      dutch: 'de ellepijp',
      english: 'the ulna',
      image: ellepijp,
      audio: '/audio/words/body/skeleton-and-muscles/ellepijp.m4a',
      credit: {
        author: 'Anatomography',
        license: 'CC BY-SA 2.1 jp',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en',
        file: 'Ulna_-_anterior_view.png',
      },
    },
    {
      slug: 'spaakbeen',
      dutch: 'het spaakbeen',
      english: 'the radius',
      image: spaakbeen,
      audio: '/audio/words/body/skeleton-and-muscles/spaakbeen.m4a',
      credit: {
        author: 'Anatomography',
        license: 'CC BY-SA 2.1 jp',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en',
        file: 'Radius_-_anterior_view2.png',
      },
    },
    {
      slug: 'bekken',
      dutch: 'het bekken',
      english: 'the pelvis',
      image: bekken,
      audio: '/audio/words/body/skeleton-and-muscles/bekken.m4a',
      credit: {
        author: 'Henry Vandyke Carter',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Gray241.png',
      },
    },
    {
      slug: 'heiligbeen',
      dutch: 'het heiligbeen',
      english: 'the sacrum',
      image: heiligbeen,
      audio: '/audio/words/body/skeleton-and-muscles/heiligbeen.m4a',
      credit: {
        author: 'BodyParts3D is made by DBCLS',
        license: 'CC BY-SA 2.1 jp',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en',
        file: 'Sacrum_-_anterior_view04.png',
      },
    },
    {
      slug: 'staartbeen',
      dutch: 'het staartbeen',
      english: 'the tailbone',
      image: staartbeen,
      audio: '/audio/words/body/skeleton-and-muscles/staartbeen.m4a',
      credit: {
        author: 'BodyParts3D is made by DBCLS',
        license: 'CC BY-SA 2.1 jp',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en',
        file: 'Coccyx_-_anterior_view02.png',
      },
    },
    {
      slug: 'dijbeen',
      dutch: 'het dijbeen',
      english: 'the thigh bone',
      image: dijbeen,
      audio: '/audio/words/body/skeleton-and-muscles/dijbeen.m4a',
      credit: {
        author: 'Anatomography',
        license: 'CC BY-SA 2.1 jp',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en',
        file: 'Femur_-_anterior_view2.png',
      },
    },
    {
      slug: 'knieschijf',
      dutch: 'de knieschijf',
      english: 'the kneecap',
      image: knieschijf,
      audio: '/audio/words/body/skeleton-and-muscles/knieschijf.m4a',
      credit: {
        author: 'Wikimedia Commons contributor',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Patella ant.jpg',
      },
    },
    {
      slug: 'scheenbeen',
      dutch: 'het scheenbeen',
      english: 'the shinbone',
      image: scheenbeen,
      audio: '/audio/words/body/skeleton-and-muscles/scheenbeen.m4a',
      credit: {
        author: 'Anatomography',
        license: 'CC BY-SA 2.1 jp',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en',
        file: 'Tibia_-_frontal_view.png',
      },
    },
    {
      slug: 'kuitbeen',
      dutch: 'het kuitbeen',
      english: 'the fibula',
      image: kuitbeen,
      audio: '/audio/words/body/skeleton-and-muscles/kuitbeen.m4a',
      credit: {
        author: 'Anatomography',
        license: 'CC BY-SA 2.1 jp',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en',
        file: 'Fibula_-_anterior_view.png',
      },
    },
    {
      slug: 'kraakbeen',
      dutch: 'het kraakbeen',
      english: 'the cartilage',
      image: kraakbeen,
      audio: '/audio/words/body/skeleton-and-muscles/kraakbeen.m4a',
      credit: {
        author: 'Wikimedia Commons contributor',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Illu synovial joint.jpg',
      },
    },
    {
      slug: 'gewricht',
      dutch: 'het gewricht',
      english: 'the joint',
      image: gewricht,
      audio: '/audio/words/body/skeleton-and-muscles/gewricht.m4a',
      credit: {
        author: 'Madhero88',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Joint.svg',
      },
    },
    {
      slug: 'gewrichtsband',
      dutch: 'de gewrichtsband',
      english: 'the ligament',
      image: gewrichtsband,
      audio: '/audio/words/body/skeleton-and-muscles/gewrichtsband.m4a',
      credit: {
        author: 'Mysid',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Knee diagram.svg',
      },
    },
    {
      slug: 'spier',
      dutch: 'de spier',
      english: 'the muscle',
      image: spier,
      audio: '/audio/words/body/skeleton-and-muscles/spier.m4a',
      credit: {
        author: 'Henry Vandyke Carter',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Arm muscles front superficial.png',
      },
    },
    {
      slug: 'biceps',
      dutch: 'de biceps',
      english: 'the biceps',
      image: biceps,
      audio: '/audio/words/body/skeleton-and-muscles/biceps.m4a',
      credit: {
        author: 'CFCF',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: '1120_Muscles_that_Move_the_Forearm_Humerus_Flex_Sin.png',
      },
    },
    {
      slug: 'pees',
      dutch: 'de pees',
      english: 'the tendon',
      image: pees,
      audio: '/audio/words/body/skeleton-and-muscles/pees.m4a',
      credit: {
        author: 'InjuryMap',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Quadriceps tendon.svg',
      },
    },
    {
      slug: 'achillespees',
      dutch: 'de achillespees',
      english: 'the Achilles tendon',
      image: achillespees,
      audio: '/audio/words/body/skeleton-and-muscles/achillespees.m4a',
      credit: {
        author: 'J. Gordon Betts, Kelly A. Young, James A. Wise, Eddie Johnson et al.',
        license: 'CC BY 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/4.0',
        file: '1123_Muscles_of_the_Leg_that_Move_the_Foot_and_Toes_b.png',
      },
    },
  ],
};
