// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import groteHersenen from './grote-hersenen.webp';
import hersenen from './hersenen.webp';
import hersenhelft from './hersenhelft.webp';
import hersenkwab from './hersenkwab.webp';
import hersenschors from './hersenschors.webp';
import hersenstam from './hersenstam.webp';
import hersenvlies from './hersenvlies.webp';
import heupzenuw from './heupzenuw.webp';
import hypothalamus from './hypothalamus.webp';
import kleineHersenen from './kleine-hersenen.webp';
import ruggenmerg from './ruggenmerg.webp';
import synaps from './synaps.webp';
import zenuw from './zenuw.webp';
import zenuwcel from './zenuwcel.webp';
import zenuwstelsel from './zenuwstelsel.webp';

export const nervousSystem: WordTopic = {
  slug: 'nervous-system',
  title: 'Nervous system',
  dutchTitle: 'Zenuwstelsel',
  description: 'The brain, the spinal cord and the nerves that wire them to everything else.',
  entries: [
    {
      slug: 'zenuwstelsel',
      dutch: 'het zenuwstelsel',
      english: 'the nervous system',
      image: zenuwstelsel,
      audio: '/audio/words/body/nervous-system/zenuwstelsel.m4a',
      credit: {
        author: 'Wikimedia Commons contributor',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: 'TE-Nervous_system_diagram.svg',
      },
    },
    {
      slug: 'hersenen',
      dutch: 'de hersenen',
      english: 'the brain',
      image: hersenen,
      audio: '/audio/words/body/nervous-system/hersenen.m4a',
      credit: {
        author: 'Patrick J. Lynch, medical illustrator',
        license: 'CC BY 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.5',
        file: 'Skull and brain normal human.svg',
      },
    },
    {
      slug: 'grote-hersenen',
      dutch: 'de grote hersenen',
      english: 'the cerebrum',
      image: groteHersenen,
      audio: '/audio/words/body/nervous-system/grote-hersenen.m4a',
      credit: {
        author: 'Henry Vandyke Carter',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Lobes_of_the_brain_NL.svg',
      },
    },
    {
      slug: 'hersenhelft',
      dutch: 'de hersenhelft',
      english: 'the cerebral hemisphere',
      image: hersenhelft,
      audio: '/audio/words/body/nervous-system/hersenhelft.m4a',
      credit: {
        author: 'BruceBlaus',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: 'Blausen_0215_CerebralHemispheres.png',
      },
    },
    {
      slug: 'hersenkwab',
      dutch: 'de hersenkwab',
      english: 'the lobe of the brain',
      image: hersenkwab,
      audio: '/audio/words/body/nervous-system/hersenkwab.m4a',
      credit: {
        author: 'Sebastian023',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'LobesCaptsLateral.png',
      },
    },
    {
      slug: 'hersenschors',
      dutch: 'de hersenschors',
      english: 'the cerebral cortex',
      image: hersenschors,
      audio: '/audio/words/body/nervous-system/hersenschors.m4a',
      credit: {
        author: 'Lorenzo Bandieri',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Cerebral_cortex,_side_view.svg',
      },
    },
    {
      slug: 'kleine-hersenen',
      dutch: 'de kleine hersenen',
      english: 'the cerebellum',
      image: kleineHersenen,
      audio: '/audio/words/body/nervous-system/kleine-hersenen.m4a',
      credit: {
        author: 'NEUROtiker',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Gehirn,_lateral_-_Lobi_+_Stammhirn_+_Cerebellum_eng.svg',
      },
    },
    {
      slug: 'hersenstam',
      dutch: 'de hersenstam',
      english: 'the brainstem',
      image: hersenstam,
      audio: '/audio/words/body/nervous-system/hersenstam.m4a',
      credit: {
        author: 'OpenStax',
        license: 'CC BY 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/4.0',
        file: '1311_Brain_Stem.jpg',
      },
    },
    {
      slug: 'hersenvlies',
      dutch: 'het hersenvlies',
      english: 'the meninges',
      image: hersenvlies,
      audio: '/audio/words/body/nervous-system/hersenvlies.m4a',
      credit: {
        author: 'https://www.scientificanimations.com',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: '3D_Medical_Illustration_Meninges_Details.jpg',
      },
    },
    {
      slug: 'hypothalamus',
      dutch: 'de hypothalamus',
      english: 'the hypothalamus',
      image: hypothalamus,
      audio: '/audio/words/body/nervous-system/hypothalamus.m4a',
      credit: {
        author: 'BruceBlaus',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: 'Blausen 0536 HypothalamusLocation.png',
      },
    },
    {
      slug: 'ruggenmerg',
      dutch: 'het ruggenmerg',
      english: 'the spinal cord',
      image: ruggenmerg,
      audio: '/audio/words/body/nervous-system/ruggenmerg.m4a',
      credit: {
        author: 'BruceBlaus',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: 'Blausen_0822_SpinalCord.png',
      },
    },
    {
      slug: 'zenuw',
      dutch: 'de zenuw',
      english: 'the nerve',
      image: zenuw,
      audio: '/audio/words/body/nervous-system/zenuw.m4a',
      credit: {
        author: 'OpenStax College',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: '1319_Nerve_StructureN.jpg',
      },
    },
    {
      slug: 'heupzenuw',
      dutch: 'de heupzenuw',
      english: 'the sciatic nerve',
      image: heupzenuw,
      audio: '/audio/words/body/nervous-system/heupzenuw.m4a',
      credit: {
        author: 'KDS4444',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Sciatic_nerve2.jpg',
      },
    },
    {
      slug: 'zenuwcel',
      dutch: 'de zenuwcel',
      english: 'the nerve cell',
      image: zenuwcel,
      audio: '/audio/words/body/nervous-system/zenuwcel.m4a',
      credit: {
        author: 'BruceBlaus',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: 'Blausen_0657_MultipolarNeuron.png',
      },
    },
    {
      slug: 'synaps',
      dutch: 'de synaps',
      english: 'the synapse',
      image: synaps,
      audio: '/audio/words/body/nervous-system/synaps.m4a',
      credit: {
        author: 'Curtis Neveu',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Synapse_figure.png',
      },
    },
  ],
};
