// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import arm from './arm.webp';
import been from './been.webp';
import borst from './borst.webp';
import buik from './buik.webp';
import dij from './dij.webp';
import duim from './duim.webp';
import elleboog from './elleboog.webp';
import enkel from './enkel.webp';
import gezicht from './gezicht.webp';
import hand from './hand.webp';
import handpalm from './handpalm.webp';
import heup from './heup.webp';
import hiel from './hiel.webp';
import hoofd from './hoofd.webp';
import kaak from './kaak.webp';
import kin from './kin.webp';
import knie from './knie.webp';
import kuit from './kuit.webp';
import navel from './navel.webp';
import nek from './nek.webp';
import oksel from './oksel.webp';
import pink from './pink.webp';
import pols from './pols.webp';
import rug from './rug.webp';
import schouder from './schouder.webp';
import teen from './teen.webp';
import vinger from './vinger.webp';
import voet from './voet.webp';
import voetzool from './voetzool.webp';
import voorhoofd from './voorhoofd.webp';
import vuist from './vuist.webp';
import wang from './wang.webp';
import wijsvinger from './wijsvinger.webp';

export const bodyParts: WordTopic = {
  slug: 'body-parts',
  title: 'Body parts',
  dutchTitle: 'Lichaamsdelen',
  description: 'What you can point at, from het hoofd down to de teen.',
  entries: [
    {
      slug: 'hoofd',
      dutch: 'het hoofd',
      english: 'the head',
      image: hoofd,
      audio: '/audio/words/body/body-parts/hoofd.m4a',
      credit: {
        author: 'Leonardo da Vinci / Wenceslaus Hollar',
        license: 'CC0',
        licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
        file: 'Head of a bald man in profile to left MET DP823701.jpg',
      },
    },
    {
      slug: 'gezicht',
      dutch: 'het gezicht',
      english: 'the face',
      image: gezicht,
      audio: '/audio/words/body/body-parts/gezicht.m4a',
      credit: {
        author: 'Autisticeditor 20',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Human_faces.jpg',
      },
    },
    {
      slug: 'voorhoofd',
      dutch: 'het voorhoofd',
      english: 'the forehead',
      image: voorhoofd,
      audio: '/audio/words/body/body-parts/voorhoofd.m4a',
      credit: {
        author: 'Frank Vincentz',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Male_forehead-01_ies.jpg',
      },
    },
    {
      slug: 'wang',
      dutch: 'de wang',
      english: 'the cheek',
      image: wang,
      audio: '/audio/words/body/body-parts/wang.m4a',
      credit: {
        author: 'Paolo Neo',
        license: 'CC0',
        licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
        file: 'Cheek.jpg',
      },
    },
    {
      slug: 'kin',
      dutch: 'de kin',
      english: 'the chin',
      image: kin,
      audio: '/audio/words/body/body-parts/kin.m4a',
      credit: {
        author: 'Unknown author; cropped by Tizio',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Cleft-Chin.jpg',
      },
    },
    {
      slug: 'kaak',
      dutch: 'de kaak',
      english: 'the jaw',
      image: kaak,
      audio: '/audio/words/body/body-parts/kaak.m4a',
      credit: {
        author: 'Unknown author',
        license: 'CC0',
        licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
        file: 'Siebert_12_(jaws).jpg',
      },
    },
    {
      slug: 'nek',
      dutch: 'de nek',
      english: 'the neck',
      image: nek,
      audio: '/audio/words/body/body-parts/nek.m4a',
      credit: {
        author: 'David Shankbone',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Neck by David Shankbone.jpg',
      },
    },
    {
      slug: 'schouder',
      dutch: 'de schouder',
      english: 'the shoulder',
      image: schouder,
      audio: '/audio/words/body/body-parts/schouder.m4a',
      credit: {
        author: 'Genusfotografen (Tomas Gunnarsson) / Wikimedia',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Left_shoulder.jpg',
      },
    },
    {
      slug: 'oksel',
      dutch: 'de oksel',
      english: 'the armpit',
      image: oksel,
      audio: '/audio/words/body/body-parts/oksel.m4a',
      credit: {
        author: 'Gangster848',
        license: 'CC0',
        licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
        file: 'ArmpitHair2.jpg',
      },
    },
    {
      slug: 'arm',
      dutch: 'de arm',
      english: 'the arm',
      image: arm,
      audio: '/audio/words/body/body-parts/arm.m4a',
      credit: {
        author: 'Genusfotografen (Tomas Gunnarsson) / Wikimedia Sverige',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Extended_arm.jpg',
      },
    },
    {
      slug: 'elleboog',
      dutch: 'de elleboog',
      english: 'the elbow',
      image: elleboog,
      audio: '/audio/words/body/body-parts/elleboog.m4a',
      credit: {
        author: 'Genusfotografen (Tommas Gunnarsson) / Wikimedia Sverige',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Elbow_on_gray_background.jpg',
      },
    },
    {
      slug: 'pols',
      dutch: 'de pols',
      english: 'the wrist',
      image: pols,
      audio: '/audio/words/body/body-parts/pols.m4a',
      credit: {
        author: 'Tomasz Sienicki',
        license: 'CC BY 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.5',
        file: 'Nadgarstek_(ubt).jpeg',
      },
    },
    {
      slug: 'hand',
      dutch: 'de hand',
      english: 'the hand',
      image: hand,
      audio: '/audio/words/body/body-parts/hand.m4a',
      credit: {
        author: 'Genusfotografen (Tomas Gunnarsson) / Wikimedia',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Hand,_fingers_-_back.jpg',
      },
    },
    {
      slug: 'handpalm',
      dutch: 'de handpalm',
      english: 'the palm',
      image: handpalm,
      audio: '/audio/words/body/body-parts/handpalm.m4a',
      credit: {
        author: 'Evan-Amos',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Human-Hands-Front-Back.jpg',
      },
    },
    {
      slug: 'vuist',
      dutch: 'de vuist',
      english: 'the fist',
      image: vuist,
      audio: '/audio/words/body/body-parts/vuist.m4a',
      credit: {
        author: 'Genusfotografen (Tomas Gunnarsson) / Wikimedia Sverige',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Clenched fist.jpg',
      },
    },
    {
      slug: 'vinger',
      dutch: 'de vinger',
      english: 'the finger',
      image: vinger,
      audio: '/audio/words/body/body-parts/vinger.m4a',
      credit: {
        author: 'Sciencia58',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Human_fingers_both_sides_2.jpg',
      },
    },
    {
      slug: 'duim',
      dutch: 'de duim',
      english: 'the thumb',
      image: duim,
      audio: '/audio/words/body/body-parts/duim.m4a',
      credit: {
        author: 'Bwyell80',
        license: 'CC0',
        licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
        file: 'Liam_Thumb.jpg',
      },
    },
    {
      slug: 'wijsvinger',
      dutch: 'de wijsvinger',
      english: 'the index finger',
      image: wijsvinger,
      audio: '/audio/words/body/body-parts/wijsvinger.m4a',
      credit: {
        author: 'Pogrebnoj-Alexandroff',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Index_finger_=_to_attention.JPG',
      },
    },
    {
      slug: 'pink',
      dutch: 'de pink',
      english: 'the little finger',
      image: pink,
      audio: '/audio/words/body/body-parts/pink.m4a',
      credit: {
        author: 'Pogrebnoj-Alexandroff',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Little_finger.jpg',
      },
    },
    {
      slug: 'borst',
      dutch: 'de borst',
      english: 'the chest',
      image: borst,
      audio: '/audio/words/body/body-parts/borst.m4a',
      credit: {
        author: 'DanielMMS',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Bodymorphproj DanielMMS modB001 20211025 posA01.jpg',
      },
    },
    {
      slug: 'buik',
      dutch: 'de buik',
      english: 'the belly',
      image: buik,
      audio: '/audio/words/body/body-parts/buik.m4a',
      credit: {
        author: '7mike5000',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Abdomen-periumbilical_region.png',
      },
    },
    {
      slug: 'navel',
      dutch: 'de navel',
      english: 'the navel',
      image: navel,
      audio: '/audio/words/body/body-parts/navel.m4a',
      credit: {
        author: 'Stinkie Pinkie',
        license: 'CC BY 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
        file: 'Human_navel,_female.jpg',
      },
    },
    {
      slug: 'rug',
      dutch: 'de rug',
      english: 'the back',
      image: rug,
      audio: '/audio/words/body/body-parts/rug.m4a',
      credit: {
        author: 'Wellcome Collection',
        license: 'CC BY 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/4.0',
        file: 'A man with naked torso viewed from behind. Photograph by L. Wellcome V0029425.jpg',
      },
    },
    {
      slug: 'heup',
      dutch: 'de heup',
      english: 'the hip',
      image: heup,
      audio: '/audio/words/body/body-parts/heup.m4a',
      credit: {
        author: 'Protohiro at English Wikipedia; later versions by Daoui and Andrew pmk',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Hip.jpg',
      },
    },
    {
      slug: 'been',
      dutch: 'het been',
      english: 'the leg',
      image: been,
      audio: '/audio/words/body/body-parts/been.m4a',
      credit: {
        author: 'Henry Vandyke Carter',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Gray1240.png',
      },
    },
    {
      slug: 'dij',
      dutch: 'de dij',
      english: 'the thigh',
      image: dij,
      audio: '/audio/words/body/body-parts/dij.m4a',
      credit: {
        author: 'gnuckx derivative work: Jonathunder derivative work: Dr.K.',
        license: 'CC BY 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
        file: 'Thigh.jpg',
      },
    },
    {
      slug: 'knie',
      dutch: 'de knie',
      english: 'the knee',
      image: knie,
      audio: '/audio/words/body/body-parts/knie.m4a',
      credit: {
        author: 'Genusfotografen (Tomas Gunnarsson) / Wikimedia Sverige',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Human_knees.jpg',
      },
    },
    {
      slug: 'kuit',
      dutch: 'de kuit',
      english: 'the calf',
      image: kuit,
      audio: '/audio/words/body/body-parts/kuit.m4a',
      credit: {
        author: 'Bigdrewdle',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Sb calf (cropped).png',
      },
    },
    {
      slug: 'enkel',
      dutch: 'de enkel',
      english: 'the ankle',
      image: enkel,
      audio: '/audio/words/body/body-parts/enkel.m4a',
      credit: {
        author: 'אנדר-ויק',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Ankle.jpg',
      },
    },
    {
      slug: 'voet',
      dutch: 'de voet',
      english: 'the foot',
      image: voet,
      audio: '/audio/words/body/body-parts/voet.m4a',
      credit: {
        author: 'Genusfotografen (Tomas Gunnarsson) / Wikimedia',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Foot_on_white_background.jpg',
      },
    },
    {
      slug: 'hiel',
      dutch: 'de hiel',
      english: 'the heel',
      image: hiel,
      audio: '/audio/words/body/body-parts/hiel.m4a',
      credit: {
        author: 'Stilfehler',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Girls_heel.jpg',
      },
    },
    {
      slug: 'voetzool',
      dutch: 'de voetzool',
      english: 'the sole',
      image: voetzool,
      audio: '/audio/words/body/body-parts/voetzool.m4a',
      credit: {
        author: 'Alvinjiaodi',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Barefeet_Soles.jpg',
      },
    },
    {
      slug: 'teen',
      dutch: 'de teen',
      english: 'the toe',
      image: teen,
      audio: '/audio/words/body/body-parts/teen.m4a',
      credit: {
        author: 'Stoneisland24',
        license: 'CC0',
        licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
        file: 'Toes.png',
      },
    },
  ],
};
