// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import amerikaanseKakkerlak from './amerikaanse-kakkerlak.webp';
import bidsprinkhaan from './bidsprinkhaan.webp';
import duitseKakkerlak from './duitse-kakkerlak.webp';
import kakkerlak from './kakkerlak.webp';
import oorworm from './oorworm.webp';
import orchideebidsprinkhaan from './orchideebidsprinkhaan.webp';
import sissendeKakkerlak from './sissende-kakkerlak.webp';
import termiet from './termiet.webp';
import wandelendBlad from './wandelend-blad.webp';
import wandelendeTak from './wandelende-tak.webp';

export const mantisesAndCockroaches: WordTopic = {
  slug: 'mantises-and-cockroaches',
  title: 'Mantises, stick insects and cockroaches',
  dutchTitle: 'Bidsprinkhanen, wandelende takken en kakkerlakken',
  description: 'The hunters, the hiders and the ones nobody wants in the kitchen.',
  entries: [
    {
      slug: 'bidsprinkhaan',
      dutch: 'de bidsprinkhaan',
      english: 'the praying mantis',
      image: bidsprinkhaan,
      audio: '/audio/words/insects/mantises-and-cockroaches/bidsprinkhaan.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'European_praying_mantis_(Mantis_religiosa)_green_female_Dobruja.jpg',
      },
    },
    {
      slug: 'orchideebidsprinkhaan',
      dutch: 'de orchideebidsprinkhaan',
      english: 'the orchid mantis',
      image: orchideebidsprinkhaan,
      audio: '/audio/words/insects/mantises-and-cockroaches/orchideebidsprinkhaan.m4a',
      credit: {
        author: 'Luc Viatour',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Mantis_Hymenopus_coronatus_6_Luc_Viatour.jpg',
      },
    },
    {
      slug: 'wandelende-tak',
      dutch: 'de wandelende tak',
      english: 'the stick insect',
      image: wandelendeTak,
      audio: '/audio/words/insects/mantises-and-cockroaches/wandelende-tak.m4a',
      credit: {
        author: 'Fritz Geller-Grimm and Felix Grimm',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Le_Caylar_fg01.JPG',
      },
    },
    {
      slug: 'wandelend-blad',
      dutch: 'het wandelend blad',
      english: 'the leaf insect',
      image: wandelendBlad,
      audio: '/audio/words/insects/mantises-and-cockroaches/wandelend-blad.m4a',
      credit: {
        author: 'Drägüs',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Pulchriphyllium giganteum, adult femal from dorsal.jpg',
      },
    },
    {
      slug: 'kakkerlak',
      dutch: 'de kakkerlak',
      english: 'the cockroach',
      image: kakkerlak,
      audio: '/audio/words/insects/mantises-and-cockroaches/kakkerlak.m4a',
      credit: {
        author: 'Dimitǎr Boevski',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Blatta orientalis male from Botevgrad, Bulgaria 02.jpg',
      },
    },
    {
      slug: 'duitse-kakkerlak',
      dutch: 'de Duitse kakkerlak',
      english: 'the German cockroach',
      image: duitseKakkerlak,
      audio: '/audio/words/insects/mantises-and-cockroaches/duitse-kakkerlak.m4a',
      credit: {
        author: 'Bagous',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Blatella_germanica_2.jpg',
      },
    },
    {
      slug: 'amerikaanse-kakkerlak',
      dutch: 'de Amerikaanse kakkerlak',
      english: 'the American cockroach',
      image: amerikaanseKakkerlak,
      audio: '/audio/words/insects/mantises-and-cockroaches/amerikaanse-kakkerlak.m4a',
      credit: {
        author: 'Gary Alpert',
        license: 'CC BY 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.5',
        file: 'American-cockroach.jpg',
      },
    },
    {
      slug: 'sissende-kakkerlak',
      dutch: 'de sissende kakkerlak',
      english: 'the hissing cockroach',
      image: sissendeKakkerlak,
      audio: '/audio/words/insects/mantises-and-cockroaches/sissende-kakkerlak.m4a',
      credit: {
        author: 'Almabes at English Wikipedia',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Female_Madagascar_hissing_cockroach.JPG',
      },
    },
    {
      slug: 'termiet',
      dutch: 'de termiet',
      english: 'the termite',
      image: termiet,
      audio: '/audio/words/insects/mantises-and-cockroaches/termiet.m4a',
      credit: {
        author: 'Photo by Scott Bauer.',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Coptotermes_formosanus_shiraki_USGov_k8204-7.jpg',
      },
    },
    {
      slug: 'oorworm',
      dutch: 'de oorworm',
      english: 'the earwig',
      image: oorworm,
      audio: '/audio/words/insects/mantises-and-cockroaches/oorworm.m4a',
      credit: {
        author: 'Rhododendrites',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'European_earwig_(81241).jpg',
      },
    },
  ],
};
