// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import azuurwaterjuffer from './azuurwaterjuffer.webp';
import blauweBreedscheenjuffer from './blauwe-breedscheenjuffer.webp';
import bosbeekjuffer from './bosbeekjuffer.webp';
import bruineWinterjuffer from './bruine-winterjuffer.webp';
import gewonePantserjuffer from './gewone-pantserjuffer.webp';
import groteRoodoogjuffer from './grote-roodoogjuffer.webp';
import houtpantserjuffer from './houtpantserjuffer.webp';
import lantaarntje from './lantaarntje.webp';
import variabeleWaterjuffer from './variabele-waterjuffer.webp';
import vuurjuffer from './vuurjuffer.webp';
import waterjuffer from './waterjuffer.webp';
import watersnuffel from './watersnuffel.webp';
import weidebeekjuffer from './weidebeekjuffer.webp';

export const damselflies: WordTopic = {
  slug: 'damselflies',
  title: 'Damselflies',
  dutchTitle: 'Juffers',
  description: 'Thinner than a dragonfly, and they fold their wings when they land.',
  entries: [
    {
      slug: 'waterjuffer',
      dutch: 'de waterjuffer',
      english: 'the damselfly',
      image: waterjuffer,
      audio: '/audio/words/insects/damselflies/waterjuffer.m4a',
      credit: {
        author: 'hedera.baltica from Wrocław, Poland',
        license: 'CC BY-SA 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
        file: 'White-legged damselfly (45600872204).jpg',
      },
    },
    {
      slug: 'weidebeekjuffer',
      dutch: 'de weidebeekjuffer',
      english: 'the banded demoiselle',
      image: weidebeekjuffer,
      audio: '/audio/words/insects/damselflies/weidebeekjuffer.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Banded_demoiselle_damselfly_(Calopteryx_splendens)_male_4.jpg',
      },
    },
    {
      slug: 'bosbeekjuffer',
      dutch: 'de bosbeekjuffer',
      english: 'the beautiful demoiselle',
      image: bosbeekjuffer,
      audio: '/audio/words/insects/damselflies/bosbeekjuffer.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Beautiful_demoiselle_(Calopteryx_virgo)_male_3.jpg',
      },
    },
    {
      slug: 'vuurjuffer',
      dutch: 'de vuurjuffer',
      english: 'the large red damselfly',
      image: vuurjuffer,
      audio: '/audio/words/insects/damselflies/vuurjuffer.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Large_red_damselfly_(Pyrrhosoma_nymphula)_male_Dry_Sandford.jpg',
      },
    },
    {
      slug: 'lantaarntje',
      dutch: 'het lantaarntje',
      english: 'the blue-tailed damselfly',
      image: lantaarntje,
      audio: '/audio/words/insects/damselflies/lantaarntje.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Blue-tailed_damselfly_(Ischnura_elegans)_male_adult.jpg',
      },
    },
    {
      slug: 'azuurwaterjuffer',
      dutch: 'de azuurwaterjuffer',
      english: 'the azure damselfly',
      image: azuurwaterjuffer,
      audio: '/audio/words/insects/damselflies/azuurwaterjuffer.m4a',
      credit: {
        author: 'Jörg Hempel',
        license: 'CC BY-SA 3.0 de',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/de/deed.en',
        file: 'Coenagrion_puella_LC0315.jpg',
      },
    },
    {
      slug: 'variabele-waterjuffer',
      dutch: 'de variabele waterjuffer',
      english: 'the variable damselfly',
      image: variabeleWaterjuffer,
      audio: '/audio/words/insects/damselflies/variabele-waterjuffer.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Variable_damselfly_(Coenagrion_pulchellum)_male.jpg',
      },
    },
    {
      slug: 'watersnuffel',
      dutch: 'de watersnuffel',
      english: 'the common blue damselfly',
      image: watersnuffel,
      audio: '/audio/words/insects/damselflies/watersnuffel.m4a',
      credit: {
        author: 'Zampel',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Enallagma_cyathigerum-ZIMGP1037.jpg',
      },
    },
    {
      slug: 'grote-roodoogjuffer',
      dutch: 'de grote roodoogjuffer',
      english: 'the red-eyed damselfly',
      image: groteRoodoogjuffer,
      audio: '/audio/words/insects/damselflies/grote-roodoogjuffer.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Large_red-eye_(Erythromma_najas)_male_Sørlimyra.jpg',
      },
    },
    {
      slug: 'houtpantserjuffer',
      dutch: 'de houtpantserjuffer',
      english: 'the willow emerald damselfly',
      image: houtpantserjuffer,
      audio: '/audio/words/insects/damselflies/houtpantserjuffer.m4a',
      credit: {
        author: 'Andreas Eichler',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: '2017.08.06.-04-Kirschgartshaeuser_Schlaege_Mannheim--Weidenjungfer-Maennchen.jpg',
      },
    },
    {
      slug: 'gewone-pantserjuffer',
      dutch: 'de gewone pantserjuffer',
      english: 'the emerald damselfly',
      image: gewonePantserjuffer,
      audio: '/audio/words/insects/damselflies/gewone-pantserjuffer.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Emerald_damselfly_(Lestes_sponsa)_male_3.jpg',
      },
    },
    {
      slug: 'bruine-winterjuffer',
      dutch: 'de bruine winterjuffer',
      english: 'the winter damselfly',
      image: bruineWinterjuffer,
      audio: '/audio/words/insects/damselflies/bruine-winterjuffer.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Common_winter_damselfly_(Sympecma_fusca)_male.jpg',
      },
    },
    {
      slug: 'blauwe-breedscheenjuffer',
      dutch: 'de blauwe breedscheenjuffer',
      english: 'the white-legged damselfly',
      image: blauweBreedscheenjuffer,
      audio: '/audio/words/insects/damselflies/blauwe-breedscheenjuffer.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'White-legged_damselfly_(Platycnemis_pennipes)_male.jpg',
      },
    },
  ],
};
