// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import aziatischLieveheersbeestje from './aziatisch-lieveheersbeestje.webp';
import boktor from './boktor.webp';
import bombardeerkever from './bombardeerkever.webp';
import doodgraver from './doodgraver.webp';
import glimworm from './glimworm.webp';
import goudenTor from './gouden-tor.webp';
import groeneZandloopkever from './groene-zandloopkever.webp';
import junikever from './junikever.webp';
import kniptor from './kniptor.webp';
import kortschildkever from './kortschildkever.webp';
import lieveheersbeestje from './lieveheersbeestje.webp';
import loopkever from './loopkever.webp';
import meikever from './meikever.webp';
import mestkever from './mestkever.webp';
import muskusboktor from './muskusboktor.webp';
import neushoornkever from './neushoornkever.webp';
import oliekever from './oliekever.webp';
import prachtkever from './prachtkever.webp';
import rozenkever from './rozenkever.webp';
import snuitkever from './snuitkever.webp';
import soldaatje from './soldaatje.webp';
import vliegendHert from './vliegend-hert.webp';
import vuurvliegje from './vuurvliegje.webp';
import zwartkopvuurkever from './zwartkopvuurkever.webp';

export const gardenBeetles: WordTopic = {
  slug: 'garden-beetles',
  title: 'Beetles of garden and wood',
  dutchTitle: 'Kevers van tuin en bos',
  description: 'The beetles you meet outdoors, from het lieveheersbeestje to het vliegend hert.',
  entries: [
    {
      slug: 'lieveheersbeestje',
      dutch: 'het lieveheersbeestje',
      english: 'the ladybird',
      image: lieveheersbeestje,
      audio: '/audio/words/insects/garden-beetles/lieveheersbeestje.m4a',
      credit: {
        author: 'Photographer: Dominik Stodulski Graphic Processing: User:MathKnight',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: '7-Spotted-Ladybug-Coccinella-septempunctata-sq1.jpg',
      },
    },
    {
      slug: 'aziatisch-lieveheersbeestje',
      dutch: 'het Aziatisch lieveheersbeestje',
      english: 'the harlequin ladybird',
      image: aziatischLieveheersbeestje,
      audio: '/audio/words/insects/garden-beetles/aziatisch-lieveheersbeestje.m4a',
      credit: {
        author: 'JackyM59',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Coccinelle asiatique (Harmonia axyridis).jpg',
      },
    },
    {
      slug: 'meikever',
      dutch: 'de meikever',
      english: 'the cockchafer',
      image: meikever,
      audio: '/audio/words/insects/garden-beetles/meikever.m4a',
      credit: {
        author: 'Frank Vassen from Brussels, Belgium',
        license: 'CC BY 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
        file: 'Hanneton_commun_(Melolontha_melolontha)_♀,_Parc_de_Woluwé,_Bruxelles_(51222810874).jpg',
      },
    },
    {
      slug: 'junikever',
      dutch: 'de junikever',
      english: 'the summer chafer',
      image: junikever,
      audio: '/audio/words/insects/garden-beetles/junikever.m4a',
      credit: {
        author: 'Entomart',
        license: 'Attribution',
        licenseUrl: '',
        file: 'Amphimallon_solstitialis01.jpg',
      },
    },
    {
      slug: 'rozenkever',
      dutch: 'de rozenkever',
      english: 'the garden chafer',
      image: rozenkever,
      audio: '/audio/words/insects/garden-beetles/rozenkever.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Garden_chafer_beetle_(Phyllopertha_horticola).jpg',
      },
    },
    {
      slug: 'gouden-tor',
      dutch: 'de gouden tor',
      english: 'the rose chafer',
      image: goudenTor,
      audio: '/audio/words/insects/garden-beetles/gouden-tor.m4a',
      credit: {
        author: 'Chrumps',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Cetonia-aurata.jpg',
      },
    },
    {
      slug: 'vliegend-hert',
      dutch: 'het vliegend hert',
      english: 'the stag beetle',
      image: vliegendHert,
      audio: '/audio/words/insects/garden-beetles/vliegend-hert.m4a',
      credit: {
        author: 'J.F. Gaffard',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Lucanus_cervus.jpg',
      },
    },
    {
      slug: 'neushoornkever',
      dutch: 'de neushoornkever',
      english: 'the rhinoceros beetle',
      image: neushoornkever,
      audio: '/audio/words/insects/garden-beetles/neushoornkever.m4a',
      credit: {
        author: 'Hectonichus',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Oryctes_nasicornis-002.jpg',
      },
    },
    {
      slug: 'mestkever',
      dutch: 'de mestkever',
      english: 'the dung beetle',
      image: mestkever,
      audio: '/audio/words/insects/garden-beetles/mestkever.m4a',
      credit: {
        author: 'Rasbak at Dutch Wikipedia',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Mestkever.jpg',
      },
    },
    {
      slug: 'doodgraver',
      dutch: 'de doodgraver',
      english: 'the burying beetle',
      image: doodgraver,
      audio: '/audio/words/insects/garden-beetles/doodgraver.m4a',
      credit: {
        author: 'Udo Schmidt from Deutschland',
        license: 'CC BY-SA 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
        file: 'Necrophorus_vespillo_(Linné,_1758)_male_(3296105414).jpg',
      },
    },
    {
      slug: 'loopkever',
      dutch: 'de loopkever',
      english: 'the ground beetle',
      image: loopkever,
      audio: '/audio/words/insects/garden-beetles/loopkever.m4a',
      credit: {
        author: 'Soebe',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Carabus_auratus_with_prey.jpg',
      },
    },
    {
      slug: 'groene-zandloopkever',
      dutch: 'de groene zandloopkever',
      english: 'the green tiger beetle',
      image: groeneZandloopkever,
      audio: '/audio/words/insects/garden-beetles/groene-zandloopkever.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Green_tiger_beetle_(Cicindela_campestris)_Sweden.jpg',
      },
    },
    {
      slug: 'glimworm',
      dutch: 'de glimworm',
      english: 'the glow-worm',
      image: glimworm,
      audio: '/audio/words/insects/garden-beetles/glimworm.m4a',
      credit: {
        author: 'Hectonichus',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Lampyridae_-_Lampyris_noctiluca.JPG',
      },
    },
    {
      slug: 'vuurvliegje',
      dutch: 'het vuurvliegje',
      english: 'the firefly',
      image: vuurvliegje,
      audio: '/audio/words/insects/garden-beetles/vuurvliegje.m4a',
      credit: {
        author: 'Bruce Marlin',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Photuris_lucicrescens.jpg',
      },
    },
    {
      slug: 'soldaatje',
      dutch: 'het soldaatje',
      english: 'the soldier beetle',
      image: soldaatje,
      audio: '/audio/words/insects/garden-beetles/soldaatje.m4a',
      credit: {
        author: 'IES MANUEL GARCÍA BARROS A ESTRADA- PONTEVEDRA',
        license: 'CC BY-SA 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
        file: 'Rhagonycha_fulva_-_Galicia_-_01.jpg',
      },
    },
    {
      slug: 'kniptor',
      dutch: 'de kniptor',
      english: 'the click beetle',
      image: kniptor,
      audio: '/audio/words/insects/garden-beetles/kniptor.m4a',
      credit: {
        author: 'Sarefo',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Denticollis.linearis.3.jpg',
      },
    },
    {
      slug: 'boktor',
      dutch: 'de boktor',
      english: 'the longhorn beetle',
      image: boktor,
      audio: '/audio/words/insects/garden-beetles/boktor.m4a',
      credit: {
        author: 'Didier Descouens',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Batus_barbicornis_MHNT_femelle.jpg',
      },
    },
    {
      slug: 'muskusboktor',
      dutch: 'de muskusboktor',
      english: 'the musk beetle',
      image: muskusboktor,
      audio: '/audio/words/insects/garden-beetles/muskusboktor.m4a',
      credit: {
        author: 'Udo Schmidt from Deutschland',
        license: 'CC BY-SA 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
        file: 'Aromia_moschata_(Linné,_1758)_(3962350347).jpg',
      },
    },
    {
      slug: 'snuitkever',
      dutch: 'de snuitkever',
      english: 'the weevil',
      image: snuitkever,
      audio: '/audio/words/insects/garden-beetles/snuitkever.m4a',
      credit: {
        author: 'Alvesgaspar',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Weevil_September_2008-1.jpg',
      },
    },
    {
      slug: 'oliekever',
      dutch: 'de oliekever',
      english: 'the oil beetle',
      image: oliekever,
      audio: '/audio/words/insects/garden-beetles/oliekever.m4a',
      credit: {
        author: 'ivtorov',
        license: 'CC0',
        licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
        file: '2016-Meloe-Moscow.jpg',
      },
    },
    {
      slug: 'zwartkopvuurkever',
      dutch: 'de zwartkopvuurkever',
      english: 'the black-headed cardinal beetle',
      image: zwartkopvuurkever,
      audio: '/audio/words/insects/garden-beetles/zwartkopvuurkever.m4a',
      credit: {
        author: 'soebe',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Pyrochroa.coccinea.female.jpg',
      },
    },
    {
      slug: 'kortschildkever',
      dutch: 'de kortschildkever',
      english: 'the rove beetle',
      image: kortschildkever,
      audio: '/audio/words/insects/garden-beetles/kortschildkever.m4a',
      credit: {
        author: 'Quartl',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Ocypus olens qtl1.jpg',
      },
    },
    {
      slug: 'bombardeerkever',
      dutch: 'de bombardeerkever',
      english: 'the bombardier beetle',
      image: bombardeerkever,
      audio: '/audio/words/insects/garden-beetles/bombardeerkever.m4a',
      credit: {
        author: 'Patrick Coin (Patrick Coin)',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Brachinus_spPCCA20060328-2821B.jpg',
      },
    },
    {
      slug: 'prachtkever',
      dutch: 'de prachtkever',
      english: 'the jewel beetle',
      image: prachtkever,
      audio: '/audio/words/insects/garden-beetles/prachtkever.m4a',
      credit: {
        author: 'Brian Adler (BrianAdler)',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Chrysochroa fulgidissima (Tamamushi) In Nature.PNG',
      },
    },
  ],
};
