// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import achterlijf from './achterlijf.webp';
import angel from './angel.webp';
import borststuk from './borststuk.webp';
import dekschild from './dekschild.webp';
import facetoog from './facetoog.webp';
import haltertje from './haltertje.webp';
import kaak from './kaak.webp';
import kop from './kop.webp';
import legboor from './legboor.webp';
import pantser from './pantser.webp';
import poot from './poot.webp';
import roltong from './roltong.webp';
import vleugel from './vleugel.webp';
import voelspriet from './voelspriet.webp';

export const insectBody: WordTopic = {
  slug: 'insect-body',
  title: 'Body of an insect',
  dutchTitle: 'Lichaam van een insect',
  description: 'What an insect is made of, from de voelspriet to de angel.',
  entries: [
    {
      slug: 'kop',
      dutch: 'de kop',
      english: 'the head',
      image: kop,
      audio: '/audio/words/insects/insect-body/kop.m4a',
      credit: {
        author: 'JJ Harrison (https://www.jjharrison.com.au/)',
        license: 'CC BY-SA 1.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/1.0',
        file: 'Sarcophagid fly Portrait.jpg',
      },
    },
    {
      slug: 'borststuk',
      dutch: 'het borststuk',
      english: 'the thorax',
      image: borststuk,
      audio: '/audio/words/insects/insect-body/borststuk.m4a',
      credit: {
        author: 'Julia Wilkins',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Carpenter Bee thorax and wings.jpg',
      },
    },
    {
      slug: 'achterlijf',
      dutch: 'het achterlijf',
      english: 'the abdomen',
      image: achterlijf,
      audio: '/audio/words/insects/insect-body/achterlijf.m4a',
      credit: {
        author: 'maxson.erin',
        license: 'CC BY 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
        file: 'Chalybion californicum M (16166810326).jpg',
      },
    },
    {
      slug: 'voelspriet',
      dutch: 'de voelspriet',
      english: 'the antenna',
      image: voelspriet,
      audio: '/audio/words/insects/insect-body/voelspriet.m4a',
      credit: {
        author: 'Siga',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Rosalia_alpina_side.JPG',
      },
    },
    {
      slug: 'facetoog',
      dutch: 'het facetoog',
      english: 'the compound eye',
      image: facetoog,
      audio: '/audio/words/insects/insect-body/facetoog.m4a',
      credit: {
        author: 'Luis Fernández García',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Tabanus sp 20120812 1.jpg',
      },
    },
    {
      slug: 'vleugel',
      dutch: 'de vleugel',
      english: 'the wing',
      image: vleugel,
      audio: '/audio/words/insects/insect-body/vleugel.m4a',
      credit: {
        author: 'Chuck Spidell',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Twelve Spotted Skimmer Wing (219490233).jpeg',
      },
    },
    {
      slug: 'dekschild',
      dutch: 'het dekschild',
      english: 'the wing case',
      image: dekschild,
      audio: '/audio/words/insects/insect-body/dekschild.m4a',
      credit: {
        author: 'Mario Sarto',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Maybug.jpg',
      },
    },
    {
      slug: 'poot',
      dutch: 'de poot',
      english: 'the leg',
      image: poot,
      audio: '/audio/words/insects/insect-body/poot.m4a',
      credit: {
        author: 'Tenbergen',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Grasshopper leg.tif',
      },
    },
    {
      slug: 'angel',
      dutch: 'de angel',
      english: 'the sting',
      image: angel,
      audio: '/audio/words/insects/insect-body/angel.m4a',
      credit: {
        author: 'Pollinator',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Waspstinger1658-2.jpg',
      },
    },
    {
      slug: 'kaak',
      dutch: 'de kaak',
      english: 'the mandible',
      image: kaak,
      audio: '/audio/words/insects/insect-body/kaak.m4a',
      credit: {
        author: 'fir0002',
        license: 'GFDL 1.2',
        licenseUrl: 'http://www.gnu.org/licenses/old-licenses/fdl-1.2.html',
        file: 'Bullant_head_detail.jpg',
      },
    },
    {
      slug: 'roltong',
      dutch: 'de roltong',
      english: 'the proboscis',
      image: roltong,
      audio: '/audio/words/insects/insect-body/roltong.m4a',
      credit: {
        author: 'Edmund Shaw',
        license: 'CC BY-SA 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
        file: 'Brimstone butterfly with coiled proboscis in Tilehurst, Berkshire - geograph.org.uk - 3622306.jpg',
      },
    },
    {
      slug: 'pantser',
      dutch: 'het pantser',
      english: 'the exoskeleton',
      image: pantser,
      audio: '/audio/words/insects/insect-body/pantser.m4a',
      credit: {
        author: 'Jim Conrad',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Dragonfly-nymph-exoskeleton.jpg',
      },
    },
    {
      slug: 'legboor',
      dutch: 'de legboor',
      english: 'the ovipositor',
      image: legboor,
      audio: '/audio/words/insects/insect-body/legboor.m4a',
      credit: {
        author: 'Audrius Meskauskas',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'GrassHopperOviPositor.jpg',
      },
    },
    {
      slug: 'haltertje',
      dutch: 'het haltertje',
      english: 'the haltere',
      image: haltertje,
      audio: '/audio/words/insects/insect-body/haltertje.m4a',
      credit: {
        author: 'Assafn',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Tipula Halter.jpg',
      },
    },
  ],
};
