// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordSection } from '@/features/words/types';

import { bees } from './bees/bees';
import { butterflies } from './butterflies/butterflies';
import { cicadasAndAphids } from './cicadas-and-aphids/cicadas-and-aphids';
import { damselflies } from './damselflies/damselflies';
import { dragonflies } from './dragonflies/dragonflies';
import { flies } from './flies/flies';
import { gardenBeetles } from './garden-beetles/garden-beetles';
import { grasshoppersAndCrickets } from './grasshoppers-and-crickets/grasshoppers-and-crickets';
import { insectBody } from './insect-body/insect-body';
import { lifeCycle } from './life-cycle/life-cycle';
import { mantisesAndCockroaches } from './mantises-and-cockroaches/mantises-and-cockroaches';
import { mosquitoes } from './mosquitoes/mosquitoes';
import { moths } from './moths/moths';
import { nestsAndHoney } from './nests-and-honey/nests-and-honey';
import { pestAndGiantBeetles } from './pest-and-giant-beetles/pest-and-giant-beetles';
import { smallAndAncient } from './small-and-ancient/small-and-ancient';
import { trueBugs } from './true-bugs/true-bugs';
import { waspsAndAnts } from './wasps-and-ants/wasps-and-ants';

export const insects: WordSection = {
  slug: 'insects',
  title: 'Insects',
  dutchTitle: 'Insecten',
  description:
    'Six legs and a great many names: butterflies, beetles, bees, flies, dragonflies and the rest.',
  groups: [
    {
      title: 'The insect itself',
      dutchTitle: 'Het insect zelf',
      topics: [insectBody, lifeCycle, nestsAndHoney],
    },
    {
      title: 'Butterflies and moths',
      dutchTitle: 'Vlinders',
      topics: [butterflies, moths],
    },
    {
      title: 'Beetles',
      dutchTitle: 'Kevers',
      topics: [gardenBeetles, pestAndGiantBeetles],
    },
    {
      title: 'Bees, wasps and ants',
      dutchTitle: 'Bijen, wespen en mieren',
      topics: [bees, waspsAndAnts],
    },
    {
      title: 'Flies and mosquitoes',
      dutchTitle: 'Vliegen en muggen',
      topics: [flies, mosquitoes],
    },
    {
      title: 'Dragonflies and damselflies',
      dutchTitle: 'Libellen en juffers',
      topics: [dragonflies, damselflies],
    },
    {
      title: 'Grasshoppers and their kin',
      dutchTitle: 'Sprinkhanen en verwanten',
      topics: [grasshoppersAndCrickets, mantisesAndCockroaches],
    },
    {
      title: 'Bugs, lice and fleas',
      dutchTitle: 'Wantsen, luizen en vlooien',
      topics: [trueBugs, cicadasAndAphids, smallAndAncient],
    },
  ],
};
