// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import eendagsvlieg from './eendagsvlieg.webp';
import elzenvlieg from './elzenvlieg.webp';
import gaasvlieg from './gaasvlieg.webp';
import hoofdluis from './hoofdluis.webp';
import kameelhalsvlieg from './kameelhalsvlieg.webp';
import kokerjuffer from './kokerjuffer.webp';
import mierenleeuw from './mierenleeuw.webp';
import ovenvisje from './ovenvisje.webp';
import papiervisje from './papiervisje.webp';
import schorpioenvlieg from './schorpioenvlieg.webp';
import steenvlieg from './steenvlieg.webp';
import stofluis from './stofluis.webp';
import trips from './trips.webp';
import vlo from './vlo.webp';
import zilvervisje from './zilvervisje.webp';

export const smallAndAncient: WordTopic = {
  slug: 'small-and-ancient',
  title: 'Small and ancient',
  dutchTitle: 'Klein en oeroud',
  description: 'Fleas, lice and the quiet old orders: mayflies, lacewings and het zilvervisje.',
  entries: [
    {
      slug: 'vlo',
      dutch: 'de vlo',
      english: 'the flea',
      image: vlo,
      audio: '/audio/words/insects/small-and-ancient/vlo.m4a',
      credit: {
        author: 'Erturac',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Flea.JPG',
      },
    },
    {
      slug: 'hoofdluis',
      dutch: 'de hoofdluis',
      english: 'the head louse',
      image: hoofdluis,
      audio: '/audio/words/insects/small-and-ancient/hoofdluis.m4a',
      credit: {
        author: 'Gilles San Martin',
        license: 'CC BY-SA 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
        file: 'Male_human_head_louse.jpg',
      },
    },
    {
      slug: 'stofluis',
      dutch: 'de stofluis',
      english: 'the booklouse',
      image: stofluis,
      audio: '/audio/words/insects/small-and-ancient/stofluis.m4a',
      credit: {
        author: 'Katja Schulz from Washington, D. C., USA',
        license: 'CC BY 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
        file: 'Scaly-winged_Barklouse_(28572463783).jpg',
      },
    },
    {
      slug: 'trips',
      dutch: 'de trips',
      english: 'the thrips',
      image: trips,
      audio: '/audio/words/insects/small-and-ancient/trips.m4a',
      credit: {
        author: 'Ryan Hodnett',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Frankliniella sp. - Guelph, Ontario 2017-06-21 (02).jpg',
      },
    },
    {
      slug: 'zilvervisje',
      dutch: 'het zilvervisje',
      english: 'the silverfish',
      image: zilvervisje,
      audio: '/audio/words/insects/small-and-ancient/zilvervisje.m4a',
      credit: {
        author: 'Christian Fischer',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'LepismaSaccharina.jpg',
      },
    },
    {
      slug: 'ovenvisje',
      dutch: 'het ovenvisje',
      english: 'the firebrat',
      image: ovenvisje,
      audio: '/audio/words/insects/small-and-ancient/ovenvisje.m4a',
      credit: {
        author: 'KyleCMSmith',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Firebrat_(Thermobia_domestica).jpg',
      },
    },
    {
      slug: 'papiervisje',
      dutch: 'het papiervisje',
      english: 'the grey silverfish',
      image: papiervisje,
      audio: '/audio/words/insects/small-and-ancient/papiervisje.m4a',
      credit: {
        author: 'Rene Sylvestersen',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Gray_silverfish_-_Ctenolepisma_longicaudata.jpg',
      },
    },
    {
      slug: 'eendagsvlieg',
      dutch: 'de eendagsvlieg',
      english: 'the mayfly',
      image: eendagsvlieg,
      audio: '/audio/words/insects/small-and-ancient/eendagsvlieg.m4a',
      credit: {
        author: 'Richard Bartz',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Rhithrogena_germanica_subimago_on_Equisetum_hyemale.jpg',
      },
    },
    {
      slug: 'steenvlieg',
      dutch: 'de steenvlieg',
      english: 'the stonefly',
      image: steenvlieg,
      audio: '/audio/words/insects/small-and-ancient/steenvlieg.m4a',
      credit: {
        author: 'JJ Harrison (https://www.jjharrison.com.au/)',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Eusthenia_sp.jpg',
      },
    },
    {
      slug: 'kokerjuffer',
      dutch: 'de kokerjuffer',
      english: 'the caddisfly',
      image: kokerjuffer,
      audio: '/audio/words/insects/small-and-ancient/kokerjuffer.m4a',
      credit: {
        author: 'Bruce Marlin',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Trichoptera_caddisfly_1.jpg',
      },
    },
    {
      slug: 'gaasvlieg',
      dutch: 'de gaasvlieg',
      english: 'the lacewing',
      image: gaasvlieg,
      audio: '/audio/words/insects/small-and-ancient/gaasvlieg.m4a',
      credit: {
        author: 'James K. Lindsey',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Chrysopa_perla_02.jpg',
      },
    },
    {
      slug: 'mierenleeuw',
      dutch: 'de mierenleeuw',
      english: 'the antlion',
      image: mierenleeuw,
      audio: '/audio/words/insects/small-and-ancient/mierenleeuw.m4a',
      credit: {
        author: 'Entomart',
        license: 'Attribution',
        licenseUrl: '',
        file: 'Distoleon_tetragrammicus01.jpg',
      },
    },
    {
      slug: 'schorpioenvlieg',
      dutch: 'de schorpioenvlieg',
      english: 'the scorpionfly',
      image: schorpioenvlieg,
      audio: '/audio/words/insects/small-and-ancient/schorpioenvlieg.m4a',
      credit: {
        author: 'Richard Bartz',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Panorpa_communis_with_prey_Diogma_glabrata_glabrata.jpg',
      },
    },
    {
      slug: 'kameelhalsvlieg',
      dutch: 'de kameelhalsvlieg',
      english: 'the snakefly',
      image: kameelhalsvlieg,
      audio: '/audio/words/insects/small-and-ancient/kameelhalsvlieg.m4a',
      credit: {
        author: 'Beentree',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Dichrostigma_flavipes_beentree.jpg',
      },
    },
    {
      slug: 'elzenvlieg',
      dutch: 'de elzenvlieg',
      english: 'the alderfly',
      image: elzenvlieg,
      audio: '/audio/words/insects/small-and-ancient/elzenvlieg.m4a',
      credit: {
        author: 'Hectonichus',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Sialidae_-_Sialis_sp..JPG',
      },
    },
  ],
};
