// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import bonteKnaagkever from './bonte-knaagkever.webp';
import coloradokever from './coloradokever.webp';
import geelgerandeWaterkever from './geelgerande-waterkever.webp';
import goliathkever from './goliathkever.webp';
import graanklander from './graanklander.webp';
import heiligePillenkever from './heilige-pillenkever.webp';
import herculeskever from './herculeskever.webp';
import houtworm from './houtworm.webp';
import huisboktor from './huisboktor.webp';
import leliehaantje from './leliehaantje.webp';
import letterzetter from './letterzetter.webp';
import meeltor from './meeltor.webp';
import museumkever from './museumkever.webp';
import schrijvertje from './schrijvertje.webp';
import spekkever from './spekkever.webp';
import spinnendeWatertor from './spinnende-watertor.webp';

export const pestAndGiantBeetles: WordTopic = {
  slug: 'pest-and-giant-beetles',
  title: 'Pests, swimmers and giants',
  dutchTitle: 'Plagen, zwemmers en reuzen',
  description:
    'Beetles in the potato field, in the beam and in the pond, and the largest ones of the tropics.',
  entries: [
    {
      slug: 'coloradokever',
      dutch: 'de coloradokever',
      english: 'the Colorado potato beetle',
      image: coloradokever,
      audio: '/audio/words/insects/pest-and-giant-beetles/coloradokever.m4a',
      credit: {
        author: 'Scott Bauer, USDA ARS',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Colorado_potato_beetle.jpg',
      },
    },
    {
      slug: 'leliehaantje',
      dutch: 'het leliehaantje',
      english: 'the scarlet lily beetle',
      image: leliehaantje,
      audio: '/audio/words/insects/pest-and-giant-beetles/leliehaantje.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Scarlet_lily_beetles_(Lilioceris_lilii)_mating.jpg',
      },
    },
    {
      slug: 'letterzetter',
      dutch: 'de letterzetter',
      english: 'the spruce bark beetle',
      image: letterzetter,
      audio: '/audio/words/insects/pest-and-giant-beetles/letterzetter.m4a',
      credit: {
        author: 'Gilles San Martin',
        license: 'CC BY-SA 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
        file: 'Ips_typographus_(female).jpg',
      },
    },
    {
      slug: 'houtworm',
      dutch: 'de houtworm',
      english: 'the woodworm',
      image: houtworm,
      audio: '/audio/words/insects/pest-and-giant-beetles/houtworm.m4a',
      credit: {
        author: 'Entomart',
        license: 'Attribution',
        licenseUrl: '',
        file: 'Anobium_punctatum01.jpg',
      },
    },
    {
      slug: 'huisboktor',
      dutch: 'de huisboktor',
      english: 'the house longhorn beetle',
      image: huisboktor,
      audio: '/audio/words/insects/pest-and-giant-beetles/huisboktor.m4a',
      credit: {
        author: 'Hectonichus',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Cerambycidae_-_Hylotrupes_bajulus_(male).JPG',
      },
    },
    {
      slug: 'bonte-knaagkever',
      dutch: 'de bonte knaagkever',
      english: 'the deathwatch beetle',
      image: bonteKnaagkever,
      audio: '/audio/words/insects/pest-and-giant-beetles/bonte-knaagkever.m4a',
      credit: {
        author: 'Sarefo',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Xestobium.rufovillosum.jpg',
      },
    },
    {
      slug: 'meeltor',
      dutch: 'de meeltor',
      english: 'the mealworm beetle',
      image: meeltor,
      audio: '/audio/words/insects/pest-and-giant-beetles/meeltor.m4a',
      credit: {
        author: 'Udo Schmidt from Deutschland',
        license: 'CC BY-SA 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
        file: 'Tenebrio_molitor_Linné,_1758_(32842137535).png',
      },
    },
    {
      slug: 'spekkever',
      dutch: 'de spekkever',
      english: 'the larder beetle',
      image: spekkever,
      audio: '/audio/words/insects/pest-and-giant-beetles/spekkever.m4a',
      credit: {
        author: 'André Karwath aka Aka',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Dermestes_lardarius_-_top_(aka).jpg',
      },
    },
    {
      slug: 'museumkever',
      dutch: 'de museumkever',
      english: 'the varied carpet beetle',
      image: museumkever,
      audio: '/audio/words/insects/pest-and-giant-beetles/museumkever.m4a',
      credit: {
        author: 'Hectonichus',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Dermestidae_-_Anthrenus_verbasci.JPG',
      },
    },
    {
      slug: 'graanklander',
      dutch: 'de graanklander',
      english: 'the wheat weevil',
      image: graanklander,
      audio: '/audio/words/insects/pest-and-giant-beetles/graanklander.m4a',
      credit: {
        author: 'Tobias 67',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Sitophilus granarius TP03.jpg',
      },
    },
    {
      slug: 'geelgerande-waterkever',
      dutch: 'de geelgerande waterkever',
      english: 'the great diving beetle',
      image: geelgerandeWaterkever,
      audio: '/audio/words/insects/pest-and-giant-beetles/geelgerande-waterkever.m4a',
      credit: {
        author: 'Rudolphous',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Schiermonnikoog - Gewone geelrand (Dytiscus marginalis).jpg',
      },
    },
    {
      slug: 'schrijvertje',
      dutch: 'het schrijvertje',
      english: 'the whirligig beetle',
      image: schrijvertje,
      audio: '/audio/words/insects/pest-and-giant-beetles/schrijvertje.m4a',
      credit: {
        author: 'Udo Schmidt from Deutschland',
        license: 'CC BY-SA 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
        file: 'Gyrinus_substriatus_Stephens,_1828_(3968701087)_(2).jpg',
      },
    },
    {
      slug: 'spinnende-watertor',
      dutch: 'de spinnende watertor',
      english: 'the great silver water beetle',
      image: spinnendeWatertor,
      audio: '/audio/words/insects/pest-and-giant-beetles/spinnende-watertor.m4a',
      credit: {
        author: 'Darkone',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Großer_Kolbenwasserkäfer_Hydrous_piceus_1.jpg',
      },
    },
    {
      slug: 'herculeskever',
      dutch: 'de herculeskever',
      english: 'the Hercules beetle',
      image: herculeskever,
      audio: '/audio/words/insects/pest-and-giant-beetles/herculeskever.m4a',
      credit: {
        author: 'Didier Descouens',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Dynastes_hercules_ecuatorianus_MHNT.jpg',
      },
    },
    {
      slug: 'goliathkever',
      dutch: 'de goliathkever',
      english: 'the Goliath beetle',
      image: goliathkever,
      audio: '/audio/words/insects/pest-and-giant-beetles/goliathkever.m4a',
      credit: {
        author: 'fir0002',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Goliath_beetle.jpg',
      },
    },
    {
      slug: 'heilige-pillenkever',
      dutch: 'de heilige pillenkever',
      english: 'the sacred scarab',
      image: heiligePillenkever,
      audio: '/audio/words/insects/pest-and-giant-beetles/heilige-pillenkever.m4a',
      credit: {
        author: 'Sarefo',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Scarabaeus.sacer.jpg',
      },
    },
  ],
};
