// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import bladluis from './bladluis.webp';
import bladvlo from './bladvlo.webp';
import bloedcicade from './bloedcicade.webp';
import cicade from './cicade.webp';
import doorncicade from './doorncicade.webp';
import lantaarndrager from './lantaarndrager.webp';
import rhododendroncicade from './rhododendroncicade.webp';
import schildluis from './schildluis.webp';
import schuimbeestje from './schuimbeestje.webp';
import witteVlieg from './witte-vlieg.webp';
import wolluis from './wolluis.webp';

export const cicadasAndAphids: WordTopic = {
  slug: 'cicadas-and-aphids',
  title: 'Cicadas and aphids',
  dutchTitle: 'Cicaden en bladluizen',
  description: 'The loudest insects and the smallest sap-suckers on a rose.',
  entries: [
    {
      slug: 'cicade',
      dutch: 'de cicade',
      english: 'the cicada',
      image: cicade,
      audio: '/audio/words/insects/cicadas-and-aphids/cicade.m4a',
      credit: {
        author: 'Judy Gallagher',
        license: 'CC BY 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
        file: 'Cicada_-_Neotibicen_linnei,_Woodbridge,_Virginia.jpg',
      },
    },
    {
      slug: 'schuimbeestje',
      dutch: 'het schuimbeestje',
      english: 'the froghopper',
      image: schuimbeestje,
      audio: '/audio/words/insects/cicadas-and-aphids/schuimbeestje.m4a',
      credit: {
        author: 'Didier Descouens',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: '(MHNT)_Philaenus_spumarius.jpg',
      },
    },
    {
      slug: 'bloedcicade',
      dutch: 'de bloedcicade',
      english: 'the red-and-black froghopper',
      image: bloedcicade,
      audio: '/audio/words/insects/cicadas-and-aphids/bloedcicade.m4a',
      credit: {
        author: 'Hectonichus',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Cercopidae_-_Cercopis_vulnerata.JPG',
      },
    },
    {
      slug: 'rhododendroncicade',
      dutch: 'de rhododendroncicade',
      english: 'the rhododendron leafhopper',
      image: rhododendroncicade,
      audio: '/audio/words/insects/cicadas-and-aphids/rhododendroncicade.m4a',
      credit: {
        author: 'André Karwath aka Aka',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Graphocephala_fennahi_(aka).jpg',
      },
    },
    {
      slug: 'doorncicade',
      dutch: 'de doorncicade',
      english: 'the treehopper',
      image: doorncicade,
      audio: '/audio/words/insects/cicadas-and-aphids/doorncicade.m4a',
      credit: {
        author: 'Didier Descouens',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: '(MHNT)_Stictocephala_bisonia.jpg',
      },
    },
    {
      slug: 'lantaarndrager',
      dutch: 'de lantaarndrager',
      english: 'the lanternfly',
      image: lantaarndrager,
      audio: '/audio/words/insects/cicadas-and-aphids/lantaarndrager.m4a',
      credit: {
        author: 'Richard Ling',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Pyrops_candelaria.jpg',
      },
    },
    {
      slug: 'bladluis',
      dutch: 'de bladluis',
      english: 'the aphid',
      image: bladluis,
      audio: '/audio/words/insects/cicadas-and-aphids/bladluis.m4a',
      credit: {
        author: 'Alvesgaspar',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Aphids_September_2008-1.jpg',
      },
    },
    {
      slug: 'schildluis',
      dutch: 'de schildluis',
      english: 'the scale insect',
      image: schildluis,
      audio: '/audio/words/insects/cicadas-and-aphids/schildluis.m4a',
      credit: {
        author: 'BARAKAT2011',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Wax_Scale.jpg',
      },
    },
    {
      slug: 'wolluis',
      dutch: 'de wolluis',
      english: 'the mealybug',
      image: wolluis,
      audio: '/audio/words/insects/cicadas-and-aphids/wolluis.m4a',
      credit: {
        author: 'Crisco 1492',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Mealybugs_on_flower_stem,_Yogyakarta,_2014-10-31.jpg',
      },
    },
    {
      slug: 'witte-vlieg',
      dutch: 'de witte vlieg',
      english: 'the whitefly',
      image: witteVlieg,
      audio: '/audio/words/insects/cicadas-and-aphids/witte-vlieg.m4a',
      credit: {
        author: 'gaucho',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Weisse-Fliege.jpg',
      },
    },
    {
      slug: 'bladvlo',
      dutch: 'de bladvlo',
      english: 'the jumping plant louse',
      image: bladvlo,
      audio: '/audio/words/insects/cicadas-and-aphids/bladvlo.m4a',
      credit: {
        author: 'Mick Talbot from Lincoln (U.K.), England',
        license: 'CC BY 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
        file: 'Psylla_alni.02.jpg',
      },
    },
  ],
};
