// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import baard from './baard.jpg';
import eelt from './eelt.jpg';
import haar from './haar.jpg';
import haarzakje from './haarzakje.png';
import huid from './huid.jpg';
import kippenvel from './kippenvel.jpg';
import lederhuid from './lederhuid.png';
import litteken from './litteken.jpg';
import moedervlek from './moedervlek.jpg';
import nagel from './nagel.png';
import opperhuid from './opperhuid.jpg';
import rimpel from './rimpel.jpg';
import snor from './snor.jpg';
import sproet from './sproet.jpg';
import talgklier from './talgklier.jpg';
import vingerafdruk from './vingerafdruk.png';
import zweetklier from './zweetklier.png';

export const skin: WordTopic = {
  slug: 'skin',
  title: 'Skin, hair and nails',
  dutchTitle: 'Huid, haar en nagels',
  description: "The body's wrapping: its layers and glands, and everything that grows out of it.",
  entries: [
    {
      slug: 'huid',
      dutch: 'de huid',
      english: 'the skin',
      image: huid,
      audio: '/audio/words/body/skin/huid.m4a',
      credit: {
        author: 'Wikimedia Commons contributor',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Human_skin_structure.jpg',
      },
    },
    {
      slug: 'opperhuid',
      dutch: 'de opperhuid',
      english: 'the epidermis',
      image: opperhuid,
      audio: '/audio/words/body/skin/opperhuid.m4a',
      credit: {
        author: 'Kilbad',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Epidermis-delimited.JPG',
      },
    },
    {
      slug: 'lederhuid',
      dutch: 'de lederhuid',
      english: 'the dermis',
      image: lederhuid,
      audio: '/audio/words/body/skin/lederhuid.m4a',
      credit: {
        author: 'US-Gov',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Skin.png',
      },
    },
    {
      slug: 'zweetklier',
      dutch: 'de zweetklier',
      english: 'the sweat gland',
      image: zweetklier,
      audio: '/audio/words/body/skin/zweetklier.m4a',
      credit: {
        author: 'Courtesy of NIAID Ryan Kissinger',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Sweat Gland Cross Section (NIH BioArt 504).png',
      },
    },
    {
      slug: 'talgklier',
      dutch: 'de talgklier',
      english: 'the sebaceous gland',
      image: talgklier,
      audio: '/audio/words/body/skin/talgklier.m4a',
      credit: {
        author: 'OpenStax College',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: '407 Sebaceous Glands.jpg',
      },
    },
    {
      slug: 'haar',
      dutch: 'het haar',
      english: 'the hair',
      image: haar,
      audio: '/audio/words/body/skin/haar.m4a',
      credit: {
        author: 'Alex Neman',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Woman with long brown hair from behind (7 October 2023).jpg',
      },
    },
    {
      slug: 'haarzakje',
      dutch: 'het haarzakje',
      english: 'the hair follicle',
      image: haarzakje,
      audio: '/audio/words/body/skin/haarzakje.m4a',
      credit: {
        author: 'United States National Institutes of Health',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Hair_follicle-en.svg',
      },
    },
    {
      slug: 'nagel',
      dutch: 'de nagel',
      english: 'the nail',
      image: nagel,
      audio: '/audio/words/body/skin/nagel.m4a',
      credit: {
        author: 'Hariadhi',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Nail_svg_hariadhi.svg',
      },
    },
    {
      slug: 'vingerafdruk',
      dutch: 'de vingerafdruk',
      english: 'the fingerprint',
      image: vingerafdruk,
      audio: '/audio/words/body/skin/vingerafdruk.m4a',
      credit: {
        author: 'User:The Photographersehh/info',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Fingerprint picture.svg',
      },
    },
    {
      slug: 'sproet',
      dutch: 'de sproet',
      english: 'the freckle',
      image: sproet,
      audio: '/audio/words/body/skin/sproet.m4a',
      credit: {
        author: 'Loyna',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Vesnuschki.jpg',
      },
    },
    {
      slug: 'moedervlek',
      dutch: 'de moedervlek',
      english: 'the mole',
      image: moedervlek,
      audio: '/audio/words/body/skin/moedervlek.m4a',
      credit: {
        author: 'Делфина',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Skin Mole 10.JPG',
      },
    },
    {
      slug: 'rimpel',
      dutch: 'de rimpel',
      english: 'the wrinkle',
      image: rimpel,
      audio: '/audio/words/body/skin/rimpel.m4a',
      credit: {
        author: 'synthia k.',
        license: 'CC BY 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
        file: 'Old_Bangladeshi_drinking_tea_cropped.jpg',
      },
    },
    {
      slug: 'litteken',
      dutch: 'het litteken',
      english: 'the scar',
      image: litteken,
      audio: '/audio/words/body/skin/litteken.m4a',
      credit: {
        author: 'Wikimedia Commons contributor',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Scar_(xndr).jpg',
      },
    },
    {
      slug: 'kippenvel',
      dutch: 'het kippenvel',
      english: 'the goose bumps',
      image: kippenvel,
      audio: '/audio/words/body/skin/kippenvel.m4a',
      credit: {
        author: 'Ildar Sagdejev (Specious)',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: '2003-09-17_Goose_bumps.jpg',
      },
    },
    {
      slug: 'eelt',
      dutch: 'het eelt',
      english: 'the callus',
      image: eelt,
      audio: '/audio/words/body/skin/eelt.m4a',
      credit: {
        author: 'Emilio J. Rodríguez Posada',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Evolucion_de_un_callo.jpg',
      },
    },
    {
      slug: 'baard',
      dutch: 'de baard',
      english: 'the beard',
      image: baard,
      audio: '/audio/words/body/skin/baard.m4a',
      credit: {
        author: '@nazanin',
        license: 'CC0',
        licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
        file: 'Photography-wallpaper-facial-hair-man-beard-chin-moustache-human-elder-portrait-1453095.jpg',
      },
    },
    {
      slug: 'snor',
      dutch: 'de snor',
      english: 'the moustache',
      image: snor,
      audio: '/audio/words/body/skin/snor.m4a',
      credit: {
        author: 'Unknown author',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Gaishi_Nagaoka.jpg',
      },
    },
  ],
};
