// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import evenwichtsorgaan from './evenwichtsorgaan.webp';
import gehoorbeentje from './gehoorbeentje.webp';
import gehoorgang from './gehoorgang.webp';
import hoornvlies from './hoornvlies.webp';
import iris from './iris.webp';
import lens from './lens.webp';
import netvlies from './netvlies.webp';
import neus from './neus.webp';
import neusgat from './neusgat.webp';
import oog from './oog.webp';
import ooglid from './ooglid.webp';
import oogwit from './oogwit.webp';
import oogzenuw from './oogzenuw.webp';
import oor from './oor.webp';
import oorlel from './oorlel.webp';
import oorschelp from './oorschelp.webp';
import pupil from './pupil.webp';
import slakkenhuis from './slakkenhuis.webp';
import smaakpapil from './smaakpapil.webp';
import tong from './tong.webp';
import traanklier from './traanklier.webp';
import trommelvlies from './trommelvlies.webp';
import wenkbrauw from './wenkbrauw.webp';
import wimper from './wimper.webp';

export const senses: WordTopic = {
  slug: 'senses',
  title: 'Sense organs',
  dutchTitle: 'Zintuigen',
  description: 'The eye, the ear, the nose and the tongue, and the parts they are made of.',
  entries: [
    {
      slug: 'oog',
      dutch: 'het oog',
      english: 'the eye',
      image: oog,
      audio: '/audio/words/body/senses/oog.m4a',
      credit: {
        author: 'ROTFLOLEB',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Human_eye_with_blood_vessels.jpg',
      },
    },
    {
      slug: 'ooglid',
      dutch: 'het ooglid',
      english: 'the eyelid',
      image: ooglid,
      audio: '/audio/words/body/senses/ooglid.m4a',
      credit: {
        author: 'Rapidreflex',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Closed_human_eye,_superior_view.jpg',
      },
    },
    {
      slug: 'wimper',
      dutch: 'de wimper',
      english: 'the eyelash',
      image: wimper,
      audio: '/audio/words/body/senses/wimper.m4a',
      credit: {
        author: 'Rapidreflex',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Human_eyelashes.jpg',
      },
    },
    {
      slug: 'wenkbrauw',
      dutch: 'de wenkbrauw',
      english: 'the eyebrow',
      image: wenkbrauw,
      audio: '/audio/words/body/senses/wenkbrauw.m4a',
      credit: {
        author: 'http://commons.wikimedia.org/wiki/User:Jastrow',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: "Jeremy_Cadot's_eyebrow.jpg",
      },
    },
    {
      slug: 'traanklier',
      dutch: 'de traanklier',
      english: 'the tear gland',
      image: traanklier,
      audio: '/audio/words/body/senses/traanklier.m4a',
      credit: {
        author: 'Henry Vandyke Carter',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Gray896.png',
      },
    },
    {
      slug: 'oogwit',
      dutch: 'het oogwit',
      english: 'the white of the eye',
      image: oogwit,
      audio: '/audio/words/body/senses/oogwit.m4a',
      credit: {
        author: 'Mikael Häggström',
        license: 'CC0',
        licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
        file: 'Sclera.PNG',
      },
    },
    {
      slug: 'hoornvlies',
      dutch: 'het hoornvlies',
      english: 'the cornea',
      image: hoornvlies,
      audio: '/audio/words/body/senses/hoornvlies.m4a',
      credit: {
        author: 'Mikael Häggström',
        license: 'CC0',
        licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
        file: 'Cornea.png',
      },
    },
    {
      slug: 'iris',
      dutch: 'de iris',
      english: 'the iris',
      image: iris,
      audio: '/audio/words/body/senses/iris.m4a',
      credit: {
        author: 'Rapidreflex',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Human_eye_close_up,_anterior_view.jpg',
      },
    },
    {
      slug: 'pupil',
      dutch: 'de pupil',
      english: 'the pupil',
      image: pupil,
      audio: '/audio/words/body/senses/pupil.m4a',
      credit: {
        author: 'Petr Novák, Wikipedia',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Eye_iris.jpg',
      },
    },
    {
      slug: 'lens',
      dutch: 'de lens',
      english: 'the lens',
      image: lens,
      audio: '/audio/words/body/senses/lens.m4a',
      credit: {
        author: 'Erin Silversmith',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Focus in an eye.svg',
      },
    },
    {
      slug: 'netvlies',
      dutch: 'het netvlies',
      english: 'the retina',
      image: netvlies,
      audio: '/audio/words/body/senses/netvlies.m4a',
      credit: {
        author: 'NIH National Eye Institute',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Human_eye_cross-sectional_view_grayscale.png',
      },
    },
    {
      slug: 'oogzenuw',
      dutch: 'de oogzenuw',
      english: 'the optic nerve',
      image: oogzenuw,
      audio: '/audio/words/body/senses/oogzenuw.m4a',
      credit: {
        author: 'Henry Vandyke Carter',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Gray773.png',
      },
    },
    {
      slug: 'oor',
      dutch: 'het oor',
      english: 'the ear',
      image: oor,
      audio: '/audio/words/body/senses/oor.m4a',
      credit: {
        author: 'Genusfotografen (Tomas Gunnarsson) / Wikimedia Sverige',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Human_right_ear_(cropped).jpg',
      },
    },
    {
      slug: 'oorschelp',
      dutch: 'de oorschelp',
      english: 'the outer ear',
      image: oorschelp,
      audio: '/audio/words/body/senses/oorschelp.m4a',
      credit: {
        author: 'Henry Vandyke Carter',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Gray904.png',
      },
    },
    {
      slug: 'oorlel',
      dutch: 'de oorlel',
      english: 'the earlobe',
      image: oorlel,
      audio: '/audio/words/body/senses/oorlel.m4a',
      credit: {
        author: 'Wikimedia Commons contributor',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Earcov.JPG',
      },
    },
    {
      slug: 'gehoorgang',
      dutch: 'de gehoorgang',
      english: 'the ear canal',
      image: gehoorgang,
      audio: '/audio/words/body/senses/gehoorgang.m4a',
      credit: {
        author: 'Iain at English Wikipedia, SVG conversion by User:Surachit',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Ear-anatomy-text-small-en.svg',
      },
    },
    {
      slug: 'trommelvlies',
      dutch: 'het trommelvlies',
      english: 'the eardrum',
      image: trommelvlies,
      audio: '/audio/words/body/senses/trommelvlies.m4a',
      credit: {
        author: 'BruceBlaus',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: 'Blausen_0328_EarAnatomy.png',
      },
    },
    {
      slug: 'gehoorbeentje',
      dutch: 'het gehoorbeentje',
      english: 'the ossicle',
      image: gehoorbeentje,
      audio: '/audio/words/body/senses/gehoorbeentje.m4a',
      credit: {
        author: 'I enjoy sandwiches',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Temporal_bone_-_The_Hungry_Artist_Multimedia.jpg',
      },
    },
    {
      slug: 'slakkenhuis',
      dutch: 'het slakkenhuis',
      english: 'the cochlea',
      image: slakkenhuis,
      audio: '/audio/words/body/senses/slakkenhuis.m4a',
      credit: {
        author: 'BruceBlaus',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: 'Blausen 0329 EarAnatomy InternalEar.png',
      },
    },
    {
      slug: 'evenwichtsorgaan',
      dutch: 'het evenwichtsorgaan',
      english: 'the organ of balance',
      image: evenwichtsorgaan,
      audio: '/audio/words/body/senses/evenwichtsorgaan.m4a',
      credit: {
        author: 'BruceBlaus',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Vertigo.png',
      },
    },
    {
      slug: 'neus',
      dutch: 'de neus',
      english: 'the nose',
      image: neus,
      audio: '/audio/words/body/senses/neus.m4a',
      credit: {
        author: 'LHOON',
        license: 'CC BY-SA 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
        file: 'Neus1.jpg',
      },
    },
    {
      slug: 'neusgat',
      dutch: 'het neusgat',
      english: 'the nostril',
      image: neusgat,
      audio: '/audio/words/body/senses/neusgat.m4a',
      credit: {
        author: 'Kuebi = Armin Kübelbeck',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Human_Nostrils_01.JPG',
      },
    },
    {
      slug: 'tong',
      dutch: 'de tong',
      english: 'the tongue',
      image: tong,
      audio: '/audio/words/body/senses/tong.m4a',
      credit: {
        author: 'Mahdiabbasinv',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'زبان_tongue.jpg',
      },
    },
    {
      slug: 'smaakpapil',
      dutch: 'de smaakpapil',
      english: 'the taste bud',
      image: smaakpapil,
      audio: '/audio/words/body/senses/smaakpapil.m4a',
      credit: {
        author: 'OpenStax',
        license: 'CC BY 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/4.0',
        file: '1402_The_Tongue.jpg',
      },
    },
  ],
};
