// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import adamsappel from './adamsappel.jpg';
import bijholte from './bijholte.jpg';
import keel from './keel.png';
import long from './long.png';
import longblaasje from './longblaasje.png';
import longkwab from './longkwab.jpg';
import longvlies from './longvlies.jpg';
import luchtpijp from './luchtpijp.png';
import luchtpijptak from './luchtpijptak.jpg';
import luchtwegen from './luchtwegen.png';
import middenrif from './middenrif.png';
import neusholte from './neusholte.jpg';
import stemband from './stemband.png';
import strotklepje from './strotklepje.png';
import strottenhoofd from './strottenhoofd.png';

export const breathing: WordTopic = {
  slug: 'breathing',
  title: 'Breathing',
  dutchTitle: 'Ademhaling',
  description: 'The way air takes, from de neusholte to het longblaasje.',
  entries: [
    {
      slug: 'luchtwegen',
      dutch: 'de luchtwegen',
      english: 'the airways',
      image: luchtwegen,
      audio: '/audio/words/body/breathing/luchtwegen.m4a',
      credit: {
        author: 'Lord Akryl, Jmarchn',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Illu_conducting_passages.svg',
      },
    },
    {
      slug: 'neusholte',
      dutch: 'de neusholte',
      english: 'the nasal cavity',
      image: neusholte,
      audio: '/audio/words/body/breathing/neusholte.m4a',
      credit: {
        author: 'Arcadian',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Illu01_head_neck.jpg',
      },
    },
    {
      slug: 'bijholte',
      dutch: 'de bijholte',
      english: 'the sinus',
      image: bijholte,
      audio: '/audio/words/body/breathing/bijholte.m4a',
      credit: {
        author: 'OpenStax College',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Paranasal_Sinuses_ant.jpg',
      },
    },
    {
      slug: 'keel',
      dutch: 'de keel',
      english: 'the throat',
      image: keel,
      audio: '/audio/words/body/breathing/keel.m4a',
      credit: {
        author: 'Persian Poet Gal at English Wikipedia',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Throat_Diagram.png',
      },
    },
    {
      slug: 'strotklepje',
      dutch: 'het strotklepje',
      english: 'the epiglottis',
      image: strotklepje,
      audio: '/audio/words/body/breathing/strotklepje.m4a',
      credit: {
        author: 'Henry Vandyke Carter',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Gray958.png',
      },
    },
    {
      slug: 'strottenhoofd',
      dutch: 'het strottenhoofd',
      english: 'the larynx',
      image: strottenhoofd,
      audio: '/audio/words/body/breathing/strottenhoofd.m4a',
      credit: {
        author: 'Olek Remesz (wiki-pl: Orem, commons: Orem)',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Larynx_external_en.svg',
      },
    },
    {
      slug: 'stemband',
      dutch: 'de stemband',
      english: 'the vocal cord',
      image: stemband,
      audio: '/audio/words/body/breathing/stemband.m4a',
      credit: {
        author: 'Henry Vandyke Carter',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Gray956.png',
      },
    },
    {
      slug: 'adamsappel',
      dutch: 'de adamsappel',
      english: "the Adam's apple",
      image: adamsappel,
      audio: '/audio/words/body/breathing/adamsappel.m4a',
      credit: {
        author: 'TONY LU',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: "Adam's apple 69A.jpg",
      },
    },
    {
      slug: 'luchtpijp',
      dutch: 'de luchtpijp',
      english: 'the windpipe',
      image: luchtpijp,
      audio: '/audio/words/body/breathing/luchtpijp.m4a',
      credit: {
        author: 'Hariadhi',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Trachea svg hariadhi.svg',
      },
    },
    {
      slug: 'luchtpijptak',
      dutch: 'de luchtpijptak',
      english: 'the bronchus',
      image: luchtpijptak,
      audio: '/audio/words/body/breathing/luchtpijptak.m4a',
      credit: {
        author: 'https://www.scientificanimations.com',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: '3D_Medical_Animation_Bronchus_Description.jpg',
      },
    },
    {
      slug: 'long',
      dutch: 'de long',
      english: 'the lung',
      image: long,
      audio: '/audio/words/body/breathing/long.m4a',
      credit: {
        author: 'Patrick J. Lynch, medical illustrator',
        license: 'CC BY 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.5',
        file: 'Lungs_diagram_detailed.svg',
      },
    },
    {
      slug: 'longkwab',
      dutch: 'de longkwab',
      english: 'the lobe of the lung',
      image: longkwab,
      audio: '/audio/words/body/breathing/longkwab.m4a',
      credit: {
        author: 'OpenStax College',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: '2312 Gross Anatomy of the Lungs.jpg',
      },
    },
    {
      slug: 'longblaasje',
      dutch: 'het longblaasje',
      english: 'the alveolus',
      image: longblaasje,
      audio: '/audio/words/body/breathing/longblaasje.m4a',
      credit: {
        author: 'LadyofHats',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Alveolus_diagram.svg',
      },
    },
    {
      slug: 'longvlies',
      dutch: 'het longvlies',
      english: 'the pleura',
      image: longvlies,
      audio: '/audio/words/body/breathing/longvlies.m4a',
      credit: {
        author: 'OpenStax College',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: '2313_The_Lung_Pleurea.jpg',
      },
    },
    {
      slug: 'middenrif',
      dutch: 'het middenrif',
      english: 'the diaphragm',
      image: middenrif,
      audio: '/audio/words/body/breathing/middenrif.m4a',
      credit: {
        author: 'Theresa knott',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Respiratory_system.svg',
      },
    },
  ],
};
