'use client';

/**
 * Plays a pre-recorded Dutch clip.
 *
 * These are static files, not browser speech synthesis. `speechSynthesis`
 * sounded correct only for visitors who happened to have a Dutch voice
 * installed; everyone else got the phrase read in English. Shipping audio is
 * what languageguide.org and digitaldialects.com do, and it is the only way
 * the pronunciation is the same for every visitor.
 *
 * Clips are generated by scripts/generate-pronunciations.py — regenerate them
 * there rather than editing files under public/audio by hand.
 */

// One element for the whole page: sweeping the pointer across a grid should
// replace whatever is playing, not layer another clip on top of it.
let player: HTMLAudioElement | null = null;

export function playPronunciation(src: string) {
  player ??= new Audio();
  player.pause();
  player.src = src;

  // Browsers refuse audio until the visitor has interacted with the page, so a
  // hover before the first click legitimately rejects. There is nothing to
  // recover from and nothing worth logging — the next click will work.
  void player.play().catch(() => undefined);
}
