// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import cocon from './cocon.webp';
import ei from './ei.webp';
import engerling from './engerling.webp';
import gedaanteverwisseling from './gedaanteverwisseling.webp';
import larve from './larve.webp';
import made from './made.webp';
import nimf from './nimf.webp';
import pop from './pop.webp';
import rups from './rups.webp';
import vervelling from './vervelling.webp';

export const lifeCycle: WordTopic = {
  slug: 'life-cycle',
  title: 'Life cycle',
  dutchTitle: 'Levenscyclus',
  description: 'From het ei to the grown insect, and the shapes it takes in between.',
  entries: [
    {
      slug: 'ei',
      dutch: 'het ei',
      english: 'the egg',
      image: ei,
      audio: '/audio/words/insects/life-cycle/ei.m4a',
      credit: {
        author: 'Anitava Roy',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Eggs of Amblypodia anita (Hewitson, 1862) - Purple Leaf Blue WLB.jpg',
      },
    },
    {
      slug: 'larve',
      dutch: 'de larve',
      english: 'the larva',
      image: larve,
      audio: '/audio/words/insects/life-cycle/larve.m4a',
      credit: {
        author: 'Jürgen Howaldt',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Asian Lady Beetle (Harmonia axyridis) Larva & Macrosiphum rosae (jh04).jpg',
      },
    },
    {
      slug: 'rups',
      dutch: 'de rups',
      english: 'the caterpillar',
      image: rups,
      audio: '/audio/words/insects/life-cycle/rups.m4a',
      credit: {
        author: 'Didier Descouens',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Chenille_de_Grand_porte_queue_(macaon).jpg',
      },
    },
    {
      slug: 'made',
      dutch: 'de made',
      english: 'the maggot',
      image: made,
      audio: '/audio/words/insects/life-cycle/made.m4a',
      credit: {
        author: 'Paul venter',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Decomposition00.jpg',
      },
    },
    {
      slug: 'engerling',
      dutch: 'de engerling',
      english: 'the grub',
      image: engerling,
      audio: '/audio/words/insects/life-cycle/engerling.m4a',
      credit: {
        author: 'AfroBrazilian',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Melolontha melolontha 09.JPG',
      },
    },
    {
      slug: 'pop',
      dutch: 'de pop',
      english: 'the pupa',
      image: pop,
      audio: '/audio/words/insects/life-cycle/pop.m4a',
      credit: {
        author: 'Didier Descouens',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Cetoine_global.jpg',
      },
    },
    {
      slug: 'cocon',
      dutch: 'de cocon',
      english: 'the cocoon',
      image: cocon,
      audio: '/audio/words/insects/life-cycle/cocon.m4a',
      credit: {
        author: 'Biswarup Ganguly',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: 'Cocoon - Bombyx mori - Kolkata 2013-06-04 8547.JPG',
      },
    },
    {
      slug: 'nimf',
      dutch: 'de nimf',
      english: 'the nymph',
      image: nimf,
      audio: '/audio/words/insects/life-cycle/nimf.m4a',
      credit: {
        author: 'Dick Culbert from Gibsons, B.C., Canada',
        license: 'CC BY 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
        file: 'Schistocerca_gregaria_(21530461886).jpg',
      },
    },
    {
      slug: 'gedaanteverwisseling',
      dutch: 'de gedaanteverwisseling',
      english: 'the metamorphosis',
      image: gedaanteverwisseling,
      audio: '/audio/words/insects/life-cycle/gedaanteverwisseling.m4a',
      credit: {
        author: 'Clinton & Charles Robertson',
        license: 'CC BY 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
        file: 'Dragonfly_metamorphosis.jpg',
      },
    },
    {
      slug: 'vervelling',
      dutch: 'de vervelling',
      english: 'the moult',
      image: vervelling,
      audio: '/audio/words/insects/life-cycle/vervelling.m4a',
      credit: {
        author: 'Beatriz Moisset',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Rhopalomyia_solidaginis_eclosion.jpg',
      },
    },
  ],
};
