// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import atlasvlinder from './atlasvlinder.webp';
import buxusmot from './buxusmot.webp';
import doodshoofdvlinder from './doodshoofdvlinder.webp';
import eikenprocessierups from './eikenprocessierups.webp';
import fruitmot from './fruitmot.webp';
import gammaUil from './gamma-uil.webp';
import grootAvondrood from './groot-avondrood.webp';
import groteBeer from './grote-beer.webp';
import hermelijnvlinder from './hermelijnvlinder.webp';
import huismoeder from './huismoeder.webp';
import indischeMeelmot from './indische-meelmot.webp';
import kleermot from './kleermot.webp';
import kolibrievlinder from './kolibrievlinder.webp';
import ligusterpijlstaart from './ligusterpijlstaart.webp';
import lindepijlstaart from './lindepijlstaart.webp';
import nachtpauwoog from './nachtpauwoog.webp';
import peperEnZoutvlinder from './peper-en-zoutvlinder.webp';
import plakker from './plakker.webp';
import roodWeeskind from './rood-weeskind.webp';
import sintJacobsvlinder from './sint-jacobsvlinder.webp';
import sintJansvlinder from './sint-jansvlinder.webp';
import wapendrager from './wapendrager.webp';
import windepijlstaart from './windepijlstaart.webp';
import zijdevlinder from './zijdevlinder.webp';

export const moths: WordTopic = {
  slug: 'moths',
  title: 'Moths',
  dutchTitle: 'Nachtvlinders',
  description:
    'The far larger family that mostly flies after dark — and a few that do not wait for it.',
  entries: [
    {
      slug: 'kolibrievlinder',
      dutch: 'de kolibrievlinder',
      english: 'the hummingbird hawk-moth',
      image: kolibrievlinder,
      audio: '/audio/words/insects/moths/kolibrievlinder.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Hummingbird_hawk_moth_(Macroglossum_stellatarum)_in_flight.jpg',
      },
    },
    {
      slug: 'doodshoofdvlinder',
      dutch: 'de doodshoofdvlinder',
      english: "the death's-head hawkmoth",
      image: doodshoofdvlinder,
      audio: '/audio/words/insects/moths/doodshoofdvlinder.m4a',
      credit: {
        author: 'Didier Descouens',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Acherontia_atropos_MHNT_dos.jpg',
      },
    },
    {
      slug: 'ligusterpijlstaart',
      dutch: 'de ligusterpijlstaart',
      english: 'the privet hawk-moth',
      image: ligusterpijlstaart,
      audio: '/audio/words/insects/moths/ligusterpijlstaart.m4a',
      credit: {
        author: 'picture taken by Olaf Leillinger',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Sphinx.ligustri.7631.jpg',
      },
    },
    {
      slug: 'lindepijlstaart',
      dutch: 'de lindepijlstaart',
      english: 'the lime hawk-moth',
      image: lindepijlstaart,
      audio: '/audio/words/insects/moths/lindepijlstaart.m4a',
      credit: {
        author: 'en:user:Emanresu',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Lime_hawk_moth.jpg',
      },
    },
    {
      slug: 'windepijlstaart',
      dutch: 'de windepijlstaart',
      english: 'the convolvulus hawk-moth',
      image: windepijlstaart,
      audio: '/audio/words/insects/moths/windepijlstaart.m4a',
      credit: {
        author: 'Entomart',
        license: 'Attribution',
        licenseUrl: '',
        file: 'Agrius convolvuli (2005-08) 01.jpg',
      },
    },
    {
      slug: 'groot-avondrood',
      dutch: 'het groot avondrood',
      english: 'the elephant hawk-moth',
      image: grootAvondrood,
      audio: '/audio/words/insects/moths/groot-avondrood.m4a',
      credit: {
        author: 'jean pierre Hamon (14)',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Deilephila_elpenor_04.jpg',
      },
    },
    {
      slug: 'nachtpauwoog',
      dutch: 'de nachtpauwoog',
      english: 'the emperor moth',
      image: nachtpauwoog,
      audio: '/audio/words/insects/moths/nachtpauwoog.m4a',
      credit: {
        author: 'jean-pierre Hamon',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: '20_petit_paon_de_nuit.jpg',
      },
    },
    {
      slug: 'atlasvlinder',
      dutch: 'de atlasvlinder',
      english: 'the Atlas moth',
      image: atlasvlinder,
      audio: '/audio/words/insects/moths/atlasvlinder.m4a',
      credit: {
        author: 'Quartl',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Attacus_atlas_qtl3.jpg',
      },
    },
    {
      slug: 'zijdevlinder',
      dutch: 'de zijdevlinder',
      english: 'the silk moth',
      image: zijdevlinder,
      audio: '/audio/words/insects/moths/zijdevlinder.m4a',
      credit: {
        author: 'Oakenking at en.wikipedia',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Pairedmoths.jpg',
      },
    },
    {
      slug: 'sint-jacobsvlinder',
      dutch: 'de sint-jacobsvlinder',
      english: 'the cinnabar moth',
      image: sintJacobsvlinder,
      audio: '/audio/words/insects/moths/sint-jacobsvlinder.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Cinnabar_moth_(Tyria_jacobaeae)_2.jpg',
      },
    },
    {
      slug: 'sint-jansvlinder',
      dutch: 'de sint-jansvlinder',
      english: 'the six-spot burnet',
      image: sintJansvlinder,
      audio: '/audio/words/insects/moths/sint-jansvlinder.m4a',
      credit: {
        author: 'Ivar Leidus',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Zygaena_filipendulae_(top_view)_-_Kulna.jpg',
      },
    },
    {
      slug: 'grote-beer',
      dutch: 'de grote beer',
      english: 'the garden tiger moth',
      image: groteBeer,
      audio: '/audio/words/insects/moths/grote-beer.m4a',
      credit: {
        author: 'Marek Szczepanek',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Arctia_caja_(Marek_Szczepanek).jpg',
      },
    },
    {
      slug: 'gamma-uil',
      dutch: 'de gamma-uil',
      english: 'the silver Y',
      image: gammaUil,
      audio: '/audio/words/insects/moths/gamma-uil.m4a',
      credit: {
        author: 'Olei',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Autographa.gamma.6902.jpg',
      },
    },
    {
      slug: 'huismoeder',
      dutch: 'de huismoeder',
      english: 'the large yellow underwing',
      image: huismoeder,
      audio: '/audio/words/insects/moths/huismoeder.m4a',
      credit: {
        author: 'nick goodrum from Catfield in Norfolk, United Kingdom',
        license: 'CC BY 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
        file: 'Moth_Large_Yellow_Underwing_-_Noctua_pronuba_(28814950448).png',
      },
    },
    {
      slug: 'rood-weeskind',
      dutch: 'het rood weeskind',
      english: 'the red underwing',
      image: roodWeeskind,
      audio: '/audio/words/insects/moths/rood-weeskind.m4a',
      credit: {
        author: 'John de Haura',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Catocala.nupta-moth7-30.07.06.jpg',
      },
    },
    {
      slug: 'wapendrager',
      dutch: 'de wapendrager',
      english: 'the buff-tip',
      image: wapendrager,
      audio: '/audio/words/insects/moths/wapendrager.m4a',
      credit: {
        author: 'Olei',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Phalera.bucephala.7189.jpg',
      },
    },
    {
      slug: 'hermelijnvlinder',
      dutch: 'de hermelijnvlinder',
      english: 'the puss moth',
      image: hermelijnvlinder,
      audio: '/audio/words/insects/moths/hermelijnvlinder.m4a',
      credit: {
        author: 'Mark Fosh',
        license: 'CC BY 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
        file: 'Puss_Moth_1.jpg',
      },
    },
    {
      slug: 'peper-en-zoutvlinder',
      dutch: 'de peper-en-zoutvlinder',
      english: 'the peppered moth',
      image: peperEnZoutvlinder,
      audio: '/audio/words/insects/moths/peper-en-zoutvlinder.m4a',
      credit: {
        author: 'Cyndy Sims Parr',
        license: 'CC BY-SA 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
        file: 'Biston_betularia_male.jpg',
      },
    },
    {
      slug: 'plakker',
      dutch: 'de plakker',
      english: 'the spongy moth',
      image: plakker,
      audio: '/audio/words/insects/moths/plakker.m4a',
      credit: {
        author: 'Didier Descouens',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Lymantria_dispar_MHNT.CUT.2012.0.357_Col_de_Cricheto_Bastelica_male_Dos.jpg',
      },
    },
    {
      slug: 'eikenprocessierups',
      dutch: 'de eikenprocessierups',
      english: 'the oak processionary',
      image: eikenprocessierups,
      audio: '/audio/words/insects/moths/eikenprocessierups.m4a',
      credit: {
        author: 'Kleuske',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Thaumetopoea_processionea,_closeup.JPG',
      },
    },
    {
      slug: 'buxusmot',
      dutch: 'de buxusmot',
      english: 'the box tree moth',
      image: buxusmot,
      audio: '/audio/words/insects/moths/buxusmot.m4a',
      credit: {
        author: 'Didier Descouens',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Cydalima_perspectalis_MHNT_Imago.jpg',
      },
    },
    {
      slug: 'kleermot',
      dutch: 'de kleermot',
      english: 'the clothes moth',
      image: kleermot,
      audio: '/audio/words/insects/moths/kleermot.m4a',
      credit: {
        author: 'Olaf Leillinger',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Tineola.bisselliella.7218.jpg',
      },
    },
    {
      slug: 'indische-meelmot',
      dutch: 'de Indische meelmot',
      english: 'the Indian meal moth',
      image: indischeMeelmot,
      audio: '/audio/words/insects/moths/indische-meelmot.m4a',
      credit: {
        author: 'Mvuijlst',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Plodia_interpunctella_-_Indianmeal_moth.jpg',
      },
    },
    {
      slug: 'fruitmot',
      dutch: 'de fruitmot',
      english: 'the codling moth',
      image: fruitmot,
      audio: '/audio/words/insects/moths/fruitmot.m4a',
      credit: {
        author: 'Simon Winkley & Ken Walker, Museum Victoria',
        license: 'CC BY 3.0 au',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0/au/deed.en',
        file: 'Cydia_pomonella_male_dorsal.jpg',
      },
    },
  ],
};
