// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import bedwants from './bedwants.webp';
import bessenschildwants from './bessenschildwants.webp';
import bladpootrandwants from './bladpootrandwants.webp';
import bootsmannetje from './bootsmannetje.webp';
import duikerwants from './duikerwants.webp';
import groeneSchildwants from './groene-schildwants.webp';
import pyjamaschildwants from './pyjamaschildwants.webp';
import roodpootschildwants from './roodpootschildwants.webp';
import roofwants from './roofwants.webp';
import schaatsenrijder from './schaatsenrijder.webp';
import staafwants from './staafwants.webp';
import vuurwants from './vuurwants.webp';
import waterschorpioen from './waterschorpioen.webp';
import zuringrandwants from './zuringrandwants.webp';

export const trueBugs: WordTopic = {
  slug: 'true-bugs',
  title: 'True bugs',
  dutchTitle: 'Wantsen',
  description: 'Insects with a beak to pierce and suck, on land and on the water.',
  entries: [
    {
      slug: 'vuurwants',
      dutch: 'de vuurwants',
      english: 'the firebug',
      image: vuurwants,
      audio: '/audio/words/insects/true-bugs/vuurwants.m4a',
      credit: {
        author: 'Divotomezove',
        license: 'Attribution',
        licenseUrl: '',
        file: 'Firebug.jpg',
      },
    },
    {
      slug: 'groene-schildwants',
      dutch: 'de groene schildwants',
      english: 'the green shield bug',
      image: groeneSchildwants,
      audio: '/audio/words/insects/true-bugs/groene-schildwants.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Green_shield_bug_(Palomena_prasina)_3.jpg',
      },
    },
    {
      slug: 'pyjamaschildwants',
      dutch: 'de pyjamaschildwants',
      english: 'the striped shield bug',
      image: pyjamaschildwants,
      audio: '/audio/words/insects/true-bugs/pyjamaschildwants.m4a',
      credit: {
        author: 'Ivar Leidus',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Graphosoma_italicum_-_Kulna.jpg',
      },
    },
    {
      slug: 'bessenschildwants',
      dutch: 'de bessenschildwants',
      english: 'the sloe bug',
      image: bessenschildwants,
      audio: '/audio/words/insects/true-bugs/bessenschildwants.m4a',
      credit: {
        author: 'Hectonichus',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Pentatomidae_-_Dolycoris_baccarum-001.JPG',
      },
    },
    {
      slug: 'roodpootschildwants',
      dutch: 'de roodpootschildwants',
      english: 'the forest bug',
      image: roodpootschildwants,
      audio: '/audio/words/insects/true-bugs/roodpootschildwants.m4a',
      credit: {
        author: 'Alchemist-hp (www.pse-mendelejew.de)',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Pentatoma_rufipes_at_a_cherry_leaf.jpg',
      },
    },
    {
      slug: 'zuringrandwants',
      dutch: 'de zuringrandwants',
      english: 'the dock bug',
      image: zuringrandwants,
      audio: '/audio/words/insects/true-bugs/zuringrandwants.m4a',
      credit: {
        author: 'JackyM59',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Corée_marginée_(Coreus_marginatus).jpg',
      },
    },
    {
      slug: 'bladpootrandwants',
      dutch: 'de bladpootrandwants',
      english: 'the western conifer seed bug',
      image: bladpootrandwants,
      audio: '/audio/words/insects/true-bugs/bladpootrandwants.m4a',
      credit: {
        author: 'Didier Descouens',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Leptoglossus_occidentalis_MHNT.jpg',
      },
    },
    {
      slug: 'roofwants',
      dutch: 'de roofwants',
      english: 'the assassin bug',
      image: roofwants,
      audio: '/audio/words/insects/true-bugs/roofwants.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Assassin_bug_(Rhynocoris_iracundus)_with_bee_(Apis_ssp)_prey.jpg',
      },
    },
    {
      slug: 'bedwants',
      dutch: 'de bedwants',
      english: 'the bed bug',
      image: bedwants,
      audio: '/audio/words/insects/true-bugs/bedwants.m4a',
      credit: {
        author: 'Piotr Naskrecki / CDC',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Bed_bug,_Cimex_lectularius.jpg',
      },
    },
    {
      slug: 'schaatsenrijder',
      dutch: 'de schaatsenrijder',
      english: 'the pond skater',
      image: schaatsenrijder,
      audio: '/audio/words/insects/true-bugs/schaatsenrijder.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Water_strider_(Gerridae_sp.)_Makiling.jpg',
      },
    },
    {
      slug: 'bootsmannetje',
      dutch: 'het bootsmannetje',
      english: 'the backswimmer',
      image: bootsmannetje,
      audio: '/audio/words/insects/true-bugs/bootsmannetje.m4a',
      credit: {
        author: 'Holger Gröschl',
        license: 'CC BY-SA 2.0 de',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/de/deed.en',
        file: 'Notonecta_glauca1.jpg',
      },
    },
    {
      slug: 'waterschorpioen',
      dutch: 'de waterschorpioen',
      english: 'the water scorpion',
      image: waterschorpioen,
      audio: '/audio/words/insects/true-bugs/waterschorpioen.m4a',
      credit: {
        author: 'Jeffdelonge',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Nepa_cinerea01.jpg',
      },
    },
    {
      slug: 'staafwants',
      dutch: 'de staafwants',
      english: 'the water stick insect',
      image: staafwants,
      audio: '/audio/words/insects/true-bugs/staafwants.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Water_stick_insect_(Ranatra_linearis).jpg',
      },
    },
    {
      slug: 'duikerwants',
      dutch: 'de duikerwants',
      english: 'the water boatman',
      image: duikerwants,
      audio: '/audio/words/insects/true-bugs/duikerwants.m4a',
      credit: {
        author: 'James K. Lindsey',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Hesperocorixa.castanea.-.lindsey.jpg',
      },
    },
  ],
};
