// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import ader from './ader.webp';
import aorta from './aorta.webp';
import beenmerg from './beenmerg.webp';
import bloed from './bloed.webp';
import bloedplaatje from './bloedplaatje.webp';
import bloedplasma from './bloedplasma.webp';
import bloedsomloop from './bloedsomloop.webp';
import bloedvat from './bloedvat.webp';
import boezem from './boezem.webp';
import haarvat from './haarvat.webp';
import halsslagader from './halsslagader.webp';
import hart from './hart.webp';
import hartkamer from './hartkamer.webp';
import hartklep from './hartklep.webp';
import hartspier from './hartspier.webp';
import holleAder from './holle-ader.webp';
import kransslagader from './kransslagader.webp';
import longslagader from './longslagader.webp';
import rodeBloedcel from './rode-bloedcel.webp';
import slagader from './slagader.webp';
import witteBloedcel from './witte-bloedcel.webp';

export const heartAndBlood: WordTopic = {
  slug: 'heart-and-blood',
  title: 'Heart and blood',
  dutchTitle: 'Hart en bloed',
  description:
    'The pump, the vessels and what flows through them — and the marrow where blood is made.',
  entries: [
    {
      slug: 'bloedsomloop',
      dutch: 'de bloedsomloop',
      english: 'the circulation',
      image: bloedsomloop,
      audio: '/audio/words/body/heart-and-blood/bloedsomloop.m4a',
      credit: {
        author: 'LadyofHats, Mariana Ruiz Villarreal',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Circulatory_System_en.svg',
      },
    },
    {
      slug: 'hart',
      dutch: 'het hart',
      english: 'the heart',
      image: hart,
      audio: '/audio/words/body/heart-and-blood/hart.m4a',
      credit: {
        author: 'Jerm',
        license: 'CC BY 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.5',
        file: 'Heart_anterior_exterior_view.png',
      },
    },
    {
      slug: 'boezem',
      dutch: 'de boezem',
      english: 'the atrium',
      image: boezem,
      audio: '/audio/words/body/heart-and-blood/boezem.m4a',
      credit: {
        author: 'Drpaulineneveu',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: '01 Coeur Heart oreillette droite right atrium.svg',
      },
    },
    {
      slug: 'hartkamer',
      dutch: 'de hartkamer',
      english: 'the ventricle',
      image: hartkamer,
      audio: '/audio/words/body/heart-and-blood/hartkamer.m4a',
      credit: {
        author: 'MesserWoland',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Diagram of the human heart (multilingual).svg',
      },
    },
    {
      slug: 'hartklep',
      dutch: 'de hartklep',
      english: 'the heart valve',
      image: hartklep,
      audio: '/audio/words/body/heart-and-blood/hartklep.m4a',
      credit: {
        author: 'OpenStax College',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: '2011 Heart Valves.jpg',
      },
    },
    {
      slug: 'hartspier',
      dutch: 'de hartspier',
      english: 'the heart muscle',
      image: hartspier,
      audio: '/audio/words/body/heart-and-blood/hartspier.m4a',
      credit: {
        author: 'BruceBlaus',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: 'Blausen 0470 HeartWall.png',
      },
    },
    {
      slug: 'kransslagader',
      dutch: 'de kransslagader',
      english: 'the coronary artery',
      image: kransslagader,
      audio: '/audio/words/body/heart-and-blood/kransslagader.m4a',
      credit: {
        author: 'Coronary.pdf: Patrick J. Lynch, medical illustrator derivative work…',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Coronary_arteries.svg',
      },
    },
    {
      slug: 'bloedvat',
      dutch: 'het bloedvat',
      english: 'the blood vessel',
      image: bloedvat,
      audio: '/audio/words/body/heart-and-blood/bloedvat.m4a',
      credit: {
        author: 'Kelvinsong; derivative work: Begoon',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Blood_vessels_(retouched)_-en.svg',
      },
    },
    {
      slug: 'aorta',
      dutch: 'de aorta',
      english: 'the aorta',
      image: aorta,
      audio: '/audio/words/body/heart-and-blood/aorta.m4a',
      credit: {
        author: 'User:Mikael Häggström, using source image by Edoarado',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Aorta_segments.svg',
      },
    },
    {
      slug: 'slagader',
      dutch: 'de slagader',
      english: 'the artery',
      image: slagader,
      audio: '/audio/words/body/heart-and-blood/slagader.m4a',
      credit: {
        author: 'Kelvinsong',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Artery.svg',
      },
    },
    {
      slug: 'halsslagader',
      dutch: 'de halsslagader',
      english: 'the carotid artery',
      image: halsslagader,
      audio: '/audio/words/body/heart-and-blood/halsslagader.m4a',
      credit: {
        author: 'Henry Vandyke Carter',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Gray506.svg',
      },
    },
    {
      slug: 'longslagader',
      dutch: 'de longslagader',
      english: 'the pulmonary artery',
      image: longslagader,
      audio: '/audio/words/body/heart-and-blood/longslagader.m4a',
      credit: {
        author: 'OpenStax College',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: '2119 Pulmonary Circuit.jpg',
      },
    },
    {
      slug: 'ader',
      dutch: 'de ader',
      english: 'the vein',
      image: ader,
      audio: '/audio/words/body/heart-and-blood/ader.m4a',
      credit: {
        author: 'File:Vein.svg: Kelvinsong derivative work: Begoon',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Vein_(retouched).svg',
      },
    },
    {
      slug: 'holle-ader',
      dutch: 'de holle ader',
      english: 'the vena cava',
      image: holleAder,
      audio: '/audio/words/body/heart-and-blood/holle-ader.m4a',
      credit: {
        author: 'OpenStax College',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: '2132 Thoracic Abdominal Veins.jpg',
      },
    },
    {
      slug: 'haarvat',
      dutch: 'het haarvat',
      english: 'the capillary',
      image: haarvat,
      audio: '/audio/words/body/heart-and-blood/haarvat.m4a',
      credit: {
        author: 'Kelvinsong',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Capillary.svg',
      },
    },
    {
      slug: 'bloed',
      dutch: 'het bloed',
      english: 'the blood',
      image: bloed,
      audio: '/audio/words/body/heart-and-blood/bloed.m4a',
      credit: {
        author: 'Dotodot',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Tube with blood sample.jpg',
      },
    },
    {
      slug: 'bloedplasma',
      dutch: 'het bloedplasma',
      english: 'the blood plasma',
      image: bloedplasma,
      audio: '/audio/words/body/heart-and-blood/bloedplasma.m4a',
      credit: {
        author: 'DiverDave',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'FreshFrozenPlasma.JPG',
      },
    },
    {
      slug: 'rode-bloedcel',
      dutch: 'de rode bloedcel',
      english: 'the red blood cell',
      image: rodeBloedcel,
      audio: '/audio/words/body/heart-and-blood/rode-bloedcel.m4a',
      credit: {
        author: 'BruceBlaus',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: 'Blausen_0761_RedBloodCells.png',
      },
    },
    {
      slug: 'witte-bloedcel',
      dutch: 'de witte bloedcel',
      english: 'the white blood cell',
      image: witteBloedcel,
      audio: '/audio/words/body/heart-and-blood/witte-bloedcel.m4a',
      credit: {
        author: 'BruceBlaus',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: 'Blausen_0909_WhiteBloodCells.png',
      },
    },
    {
      slug: 'bloedplaatje',
      dutch: 'het bloedplaatje',
      english: 'the platelet',
      image: bloedplaatje,
      audio: '/audio/words/body/heart-and-blood/bloedplaatje.m4a',
      credit: {
        author: 'BruceBlaus',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: 'Blausen 0740 Platelets.png',
      },
    },
    {
      slug: 'beenmerg',
      dutch: 'het beenmerg',
      english: 'the bone marrow',
      image: beenmerg,
      audio: '/audio/words/body/heart-and-blood/beenmerg.m4a',
      credit: {
        author: 'OpenStax College',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: '619 Red and Yellow Bone Marrow.jpg',
      },
    },
  ],
};
