// Generated by scripts/generate-word-data.py — see that file to add a word.
import type { WordEntry } from '@/features/words/types';

import accordeon from './accordeon.jpg';
import altviool from './altviool.jpg';
import balalaika from './balalaika.jpg';
import basgitaar from './basgitaar.jpg';
import bekken from './bekken.jpg';
import blokfluit from './blokfluit.jpg';
import bugel from './bugel.jpg';
import castagnetten from './castagnetten.jpg';
import cello from './cello.jpg';
import citer from './citer.jpg';
import conga from './conga.jpg';
import contrabas from './contrabas.jpg';
import didgeridoo from './didgeridoo.jpg';
import djembe from './djembe.jpg';
import doedelzak from './doedelzak.jpg';
import draailier from './draailier.jpg';
import drumstel from './drumstel.jpg';
import dwarsfluit from './dwarsfluit.jpg';
import gitaar from './gitaar.jpg';
import gong from './gong.jpg';
import harmonium from './harmonium.jpg';
import harp from './harp.jpg';
import hobo from './hobo.jpg';
import klarinet from './klarinet.jpg';
import klavecimbel from './klavecimbel.jpg';
import kleineTrom from './kleine-trom.jpg';
import kornet from './kornet.jpg';
import luit from './luit.jpg';
import mandoline from './mandoline.jpg';
import maracas from './maracas.jpg';
import marimba from './marimba.jpg';
import mondharmonica from './mondharmonica.jpg';
import ocarina from './ocarina.jpg';
import orgel from './orgel.jpg';
import panfluit from './panfluit.jpg';
import pauk from './pauk.jpg';
import piano from './piano.jpg';
import piccolo from './piccolo.jpg';
import saxofoon from './saxofoon.jpg';
import sitar from './sitar.jpg';
import steeldrum from './steeldrum.jpg';
import synthesizer from './synthesizer.jpg';
import tamboerijn from './tamboerijn.jpg';
import theremin from './theremin.jpg';
import triangel from './triangel.jpg';
import trombone from './trombone.jpg';
import trompet from './trompet.jpg';
import viool from './viool.jpg';

export const instruments: WordEntry[] = [
  {
    slug: 'gitaar',
    dutch: 'de gitaar',
    english: 'the guitar',
    image: gitaar,
    audio: '/audio/words/instruments/gitaar.m4a',
    credit: {
      author: 'User:Martin Möller Talk',
      license: 'CC BY-SA 2.0 de',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/de/deed.en',
      file: 'GuitareClassique5.png',
    },
  },
  {
    slug: 'basgitaar',
    dutch: 'de basgitaar',
    english: 'the bass guitar',
    image: basgitaar,
    audio: '/audio/words/instruments/basgitaar.m4a',
    credit: {
      author: 'Wikimedia Commons contributor',
      license: 'Public domain',
      licenseUrl: '',
      file: 'Fender_Precision_Bass.jpg',
    },
  },
  {
    slug: 'viool',
    dutch: 'de viool',
    english: 'the violin',
    image: viool,
    audio: '/audio/words/instruments/viool.m4a',
    credit: {
      author: 'Just plain Bill',
      license: 'CC0',
      licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
      file: 'Violin_VL100.png',
    },
  },
  {
    slug: 'altviool',
    dutch: 'de altviool',
    english: 'the viola',
    image: altviool,
    audio: '/audio/words/instruments/altviool.m4a',
    credit: {
      author: 'Just plain Bill',
      license: 'Public domain',
      licenseUrl: '',
      file: 'Bratsche.jpg',
    },
  },
  {
    slug: 'cello',
    dutch: 'de cello',
    english: 'the cello',
    image: cello,
    audio: '/audio/words/instruments/cello.m4a',
    credit: {
      author: 'Georg Feitscher',
      license: 'CC BY 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
      file: 'Cello_front_side.png',
    },
  },
  {
    slug: 'contrabas',
    dutch: 'de contrabas',
    english: 'the double bass',
    image: contrabas,
    audio: '/audio/words/instruments/contrabas.m4a',
    credit: {
      author: 'User:AndrewKepert',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
      file: 'AGK_bass1_full.jpg',
    },
  },
  {
    slug: 'harp',
    dutch: 'de harp',
    english: 'the harp',
    image: harp,
    audio: '/audio/words/instruments/harp.m4a',
    credit: {
      author: 'Wikimedia Commons contributor',
      license: 'Public domain',
      licenseUrl: '',
      file: 'Harp.png',
    },
  },
  {
    slug: 'piano',
    dutch: 'de piano',
    english: 'the piano',
    image: piano,
    audio: '/audio/words/instruments/piano.m4a',
    credit: {
      author: 'Gryffindor',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
      file: 'Steinway_Vienna_002.JPG',
    },
  },
  {
    slug: 'klavecimbel',
    dutch: 'het klavecimbel',
    english: 'the harpsichord',
    image: klavecimbel,
    audio: '/audio/words/instruments/klavecimbel.m4a',
    credit: {
      author: 'Gérard Janot',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
      file: 'ClavecinRuckers&Taskin.JPG',
    },
  },
  {
    slug: 'orgel',
    dutch: 'het orgel',
    english: 'the organ',
    image: orgel,
    audio: '/audio/words/instruments/orgel.m4a',
    credit: {
      author: 'Ermell',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      file: 'Neunkirchen_am_Brand_Kirche_Orgel-20210411-RM-155230.jpg',
    },
  },
  {
    slug: 'harmonium',
    dutch: 'het harmonium',
    english: 'the harmonium',
    image: harmonium,
    audio: '/audio/words/instruments/harmonium.m4a',
    credit: {
      author: 'Boygold',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
      file: 'John_Church_and_Co._reed_organ.jpg',
    },
  },
  {
    slug: 'accordeon',
    dutch: 'het accordeon',
    english: 'the accordion',
    image: accordeon,
    audio: '/audio/words/instruments/accordeon.m4a',
    credit: {
      author: 'Necz0r',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
      file: 'A_converter_free-bass_piano-accordion_and_a_Russian_bayan.jpg',
    },
  },
  {
    slug: 'mondharmonica',
    dutch: 'de mondharmonica',
    english: 'the harmonica',
    image: mondharmonica,
    audio: '/audio/words/instruments/mondharmonica.m4a',
    credit: {
      author: 'George Leung',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
      file: '16-hole_chrom_10-hole_diatonic.jpg',
    },
  },
  {
    slug: 'trompet',
    dutch: 'de trompet',
    english: 'the trumpet',
    image: trompet,
    audio: '/audio/words/instruments/trompet.m4a',
    credit: {
      author: 'Yamaha Corporation',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      file: 'Yamaha_Trumpet_YTR-8335LA_crop.jpg',
    },
  },
  {
    slug: 'kornet',
    dutch: 'de kornet',
    english: 'the cornet',
    image: kornet,
    audio: '/audio/words/instruments/kornet.m4a',
    credit: {
      author: 'Yamaha Corporation',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      file: 'Yamaha_Cornet_YCR-6330II_crop.png',
    },
  },
  {
    slug: 'bugel',
    dutch: 'de bugel',
    english: 'the flugelhorn',
    image: bugel,
    audio: '/audio/words/instruments/bugel.m4a',
    credit: {
      author: 'Photograph: Yamaha Corporation',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      file: 'Yamaha_Flugelhorn_YFH-8310Z.jpg',
    },
  },
  {
    slug: 'trombone',
    dutch: 'de trombone',
    english: 'the trombone',
    image: trombone,
    audio: '/audio/words/instruments/trombone.m4a',
    credit: {
      author: 'Yamaha Corporation',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      file: 'Yamaha_Tenor_trombone_YSL-891Z_(re-crop).jpg',
    },
  },
  {
    slug: 'dwarsfluit',
    dutch: 'de dwarsfluit',
    english: 'the flute',
    image: dwarsfluit,
    audio: '/audio/words/instruments/dwarsfluit.m4a',
    credit: {
      author: 'Tubamirum',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      file: 'Flûte_traversière.png',
    },
  },
  {
    slug: 'piccolo',
    dutch: 'de piccolo',
    english: 'the piccolo',
    image: piccolo,
    audio: '/audio/words/instruments/piccolo.m4a',
    credit: {
      author: 'User:Caesura',
      license: 'Public domain',
      licenseUrl: '',
      file: 'Piccolo.jpg',
    },
  },
  {
    slug: 'blokfluit',
    dutch: 'de blokfluit',
    english: 'the recorder',
    image: blokfluit,
    audio: '/audio/words/instruments/blokfluit.m4a',
    credit: {
      author: 'Mussklprozz',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
      file: 'VariousRecorderFlutes.jpg',
    },
  },
  {
    slug: 'panfluit',
    dutch: 'de panfluit',
    english: 'the pan flute',
    image: panfluit,
    audio: '/audio/words/instruments/panfluit.m4a',
    credit: {
      author: 'Didier Descouens',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      file: 'Flute_de_pan_MHNT_ETH_AC_NH_31_Savès.jpg',
    },
  },
  {
    slug: 'klarinet',
    dutch: 'de klarinet',
    english: 'the clarinet',
    image: klarinet,
    audio: '/audio/words/instruments/klarinet.m4a',
    credit: {
      author: 'Leitner & Kraus GmbH, Neustadt/Aisch, Editor/Bearbeiter User:Gisbert K',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      file: 'Leitner+Kraus_410_320.png',
    },
  },
  {
    slug: 'hobo',
    dutch: 'de hobo',
    english: 'the oboe',
    image: hobo,
    audio: '/audio/words/instruments/hobo.m4a',
    credit: {
      author: 'Fratelli Patricola, Editor/Bearbeiter User:Gisbert K',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      file: 'Oboe_Patricola_Artista_PT1.jpg',
    },
  },
  {
    slug: 'saxofoon',
    dutch: 'de saxofoon',
    english: 'the saxophone',
    image: saxofoon,
    audio: '/audio/words/instruments/saxofoon.m4a',
    credit: {
      author: 'Jonathanischoice',
      license: 'CC BY 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by/4.0',
      file: 'Eight_saxophone_sizes_smaller.png',
    },
  },
  {
    slug: 'doedelzak',
    dutch: 'de doedelzak',
    english: 'the bagpipes',
    image: doedelzak,
    audio: '/audio/words/instruments/doedelzak.m4a',
    credit: {
      author: 'Lucas Kendall',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      file: 'Scotland_Independence_March,_28_March_2026_(32).jpg',
    },
  },
  {
    slug: 'ocarina',
    dutch: 'de ocarina',
    english: 'the ocarina',
    image: ocarina,
    audio: '/audio/words/instruments/ocarina.m4a',
    credit: {
      author: '0x010C',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      file: '2016-01_Ocarina_front.jpg',
    },
  },
  {
    slug: 'drumstel',
    dutch: 'het drumstel',
    english: 'the drum kit',
    image: drumstel,
    audio: '/audio/words/instruments/drumstel.m4a',
    credit: {
      author: 'Syed Wamiq Ahmed Hashmi re-draw SVG FOX 52 re-draw with AI Sendtel +',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
      file: 'Drum_kit_parts.png',
    },
  },
  {
    slug: 'kleine-trom',
    dutch: 'de kleine trom',
    english: 'the snare drum',
    image: kleineTrom,
    audio: '/audio/words/instruments/kleine-trom.m4a',
    credit: {
      author: 'Ugehrig',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      file: 'Imperial-Drums Piccolo-Snare-black.jpg',
    },
  },
  {
    slug: 'pauk',
    dutch: 'de pauk',
    english: 'the timpani',
    image: pauk,
    audio: '/audio/words/instruments/pauk.m4a',
    credit: {
      author: 'Reinhold Möller Ermell',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      file: 'Burgwindheim Pauken-20180909-RM-150632.jpg',
    },
  },
  {
    slug: 'bekken',
    dutch: 'het bekken',
    english: 'the cymbal',
    image: bekken,
    audio: '/audio/words/instruments/bekken.m4a',
    credit: {
      author: 'Jdpaschal',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
      file: 'ZildjianCustomRide.jpg',
    },
  },
  {
    slug: 'tamboerijn',
    dutch: 'de tamboerijn',
    english: 'the tambourine',
    image: tamboerijn,
    audio: '/audio/words/instruments/tamboerijn.m4a',
    credit: {
      author: 'Frenciscobcn',
      license: 'CC BY-SA 1.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/1.0',
      file: 'Pandeiro_new_30-09-07.jpg',
    },
  },
  {
    slug: 'triangel',
    dutch: 'de triangel',
    english: 'the triangle',
    image: triangel,
    audio: '/audio/words/instruments/triangel.m4a',
    credit: {
      author: 'AnonymousUnknown author',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      file: 'Triangle_001.jpg',
    },
  },
  {
    slug: 'marimba',
    dutch: 'de marimba',
    english: 'the marimba',
    image: marimba,
    audio: '/audio/words/instruments/marimba.m4a',
    credit: {
      author: 'Marimbaone',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
      file: 'Marimba_One_4000_Series.jpg',
    },
  },
  {
    slug: 'gong',
    dutch: 'de gong',
    english: 'the gong',
    image: gong,
    audio: '/audio/words/instruments/gong.m4a',
    credit: {
      author: 'Tropenmuseum',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
      file: 'COLLECTIE_TROPENMUSEUM_Gong_hangend_in_een_standaard_onderdeel_van_gamelan_Semar_Pagulingan_TMnr_1340-13.jpg',
    },
  },
  {
    slug: 'djembe',
    dutch: 'de djembe',
    english: 'the djembe',
    image: djembe,
    audio: '/audio/words/instruments/djembe.m4a',
    credit: {
      author: 'Djembe Art',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
      file: 'Lenke_djembe_from_Mali.jpeg',
    },
  },
  {
    slug: 'conga',
    dutch: 'de conga',
    english: 'the conga',
    image: conga,
    audio: '/audio/words/instruments/conga.m4a',
    credit: {
      author: 'Wikimedia Commons contributor',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
      file: 'Collectie_Nationaal_Museum_van_Wereldculturen_TM-6335-1a_Enkelvellige_tonvormige_buistrom,_onderdeel_van_een_set_Cuba.jpg',
    },
  },
  {
    slug: 'maracas',
    dutch: 'de maracas',
    english: 'the maracas',
    image: maracas,
    audio: '/audio/words/instruments/maracas.m4a',
    credit: {
      author: 'Axel Heymann',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
      file: 'Maracas.jpg',
    },
  },
  {
    slug: 'castagnetten',
    dutch: 'de castagnetten',
    english: 'the castanets',
    image: castagnetten,
    audio: '/audio/words/instruments/castagnetten.m4a',
    credit: {
      author: 'Rijksmuseum',
      license: 'CC0',
      licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
      file: 'Castagnetten,_BK-NM-11430-78.jpg',
    },
  },
  {
    slug: 'mandoline',
    dutch: 'de mandoline',
    english: 'the mandolin',
    image: mandoline,
    audio: '/audio/words/instruments/mandoline.m4a',
    credit: {
      author: 'Angelo Mannello',
      license: 'CC0',
      licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
      file: 'Mandolin_MET_DP169023_(2).jpg',
    },
  },
  {
    slug: 'luit',
    dutch: 'de luit',
    english: 'the lute',
    image: luit,
    audio: '/audio/words/instruments/luit.m4a',
    credit: {
      author: 'Ching',
      license: 'CC BY 2.0',
      licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
      file: 'Lute_(by_Princess_Ruto,_2013-02-11).jpg',
    },
  },
  {
    slug: 'citer',
    dutch: 'de citer',
    english: 'the zither',
    image: citer,
    audio: '/audio/words/instruments/citer.m4a',
    credit: {
      author: 'Dietrich Michael Weidmann',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
      file: '2012-03-04-Trachselwald_(Foto_Dietrich_Michael_Weidmann)_001.JPG',
    },
  },
  {
    slug: 'sitar',
    dutch: 'de sitar',
    english: 'the sitar',
    image: sitar,
    audio: '/audio/words/instruments/sitar.m4a',
    credit: {
      author: 'unknown, MET museum',
      license: 'CC0',
      licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
      file: 'Sitar,_late_19th_Century.jpg',
    },
  },
  {
    slug: 'balalaika',
    dutch: 'de balalaika',
    english: 'the balalaika',
    image: balalaika,
    audio: '/audio/words/instruments/balalaika.m4a',
    credit: {
      author: 'User:MaGz96',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
      file: '3_string_prim_balalaika.png',
    },
  },
  {
    slug: 'draailier',
    dutch: 'de draailier',
    english: 'the hurdy-gurdy',
    image: draailier,
    audio: '/audio/words/instruments/draailier.m4a',
    credit: {
      author: 'Wikimedia Commons contributor',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
      file: 'Louvet_Drehleier.JPG',
    },
  },
  {
    slug: 'didgeridoo',
    dutch: 'de didgeridoo',
    english: 'the didgeridoo',
    image: didgeridoo,
    audio: '/audio/words/instruments/didgeridoo.m4a',
    credit: {
      author: 'Hmarin',
      license: 'Public domain',
      licenseUrl: '',
      file: 'Australiandidgeridoos.jpg',
    },
  },
  {
    slug: 'steeldrum',
    dutch: 'de steeldrum',
    english: 'the steelpan',
    image: steeldrum,
    audio: '/audio/words/instruments/steeldrum.m4a',
    credit: {
      author: 'Kip1234',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      file: 'Steelpan_Instruments_at_Trinidad_and_Tobago_Carnival.jpg',
    },
  },
  {
    slug: 'synthesizer',
    dutch: 'de synthesizer',
    english: 'the synthesizer',
    image: synthesizer,
    audio: '/audio/words/instruments/synthesizer.m4a',
    credit: {
      author: 'glacial23',
      license: 'CC BY-SA 2.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
      file: 'R.A.Moog_minimoog_2.jpg',
    },
  },
  {
    slug: 'theremin',
    dutch: 'de theremin',
    english: 'the theremin',
    image: theremin,
    audio: '/audio/words/instruments/theremin.m4a',
    credit: {
      author: 'Hutschi',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
      file: 'Etherwave_Theremin_Kit.jpg',
    },
  },
];
