/**
 * Plays pre-recorded Dutch clips, one at a time.
 *
 * These are static files, not browser speech synthesis. `speechSynthesis`
 * sounded correct only for visitors who happened to have a Dutch voice
 * installed; everyone else got the phrase read in English. Shipping audio is
 * the only way the pronunciation is the same for every visitor. Clips are
 * generated by scripts/generate-pronunciations.py.
 *
 * Framework-free on purpose: React wiring lives in pronunciation-provider.tsx,
 * and the browser pieces (the Audio element, the document) are injectable so
 * the behaviour can be tested without a browser.
 */

export type PronunciationStatus =
  /** Nothing playing. */
  | 'idle'
  | 'playing'
  /** The browser refused to play because the visitor has not interacted with
   *  the page yet. Clears on the first click. */
  | 'blocked';

export type PlayOutcome =
  | 'played'
  /** Cut short by a later `play` or `stop` — normal when sweeping a grid. */
  | 'replaced'
  | 'blocked'
  | 'failed';

/** Function properties rather than methods: none of them use `this`, so
 *  they can be handed straight to `useSyncExternalStore`. */
export interface PronunciationPlayer {
  play: (src: string) => Promise<PlayOutcome>;
  /** Silence whatever is playing and forget a blocked request. Call when the
   *  cards leave the page, or the clip carries on under the next route. */
  stop: () => void;
  getStatus: () => PronunciationStatus;
  /** Notifies on every status change. Shaped for `useSyncExternalStore`. */
  subscribe: (listener: () => void) => () => void;
}

export interface PronunciationPlayerOptions {
  /** Turns the zone-relative path in the data into a fetchable URL. */
  resolveSrc?: (src: string) => string;
  /** Test seams. Both default to the browser's. */
  createAudio?: () => HTMLAudioElement;
  getDocument?: () => Document;
}

export function createPronunciationPlayer({
  resolveSrc = (src) => src,
  createAudio = () => new Audio(),
  getDocument = () => document,
}: PronunciationPlayerOptions = {}): PronunciationPlayer {
  // One element for the whole page: sweeping the pointer across a grid should
  // replace whatever is playing, not layer another clip on top of it. Created
  // lazily so the player can be constructed during server rendering.
  let audio: HTMLAudioElement | null = null;
  let status: PronunciationStatus = 'idle';
  // The clip a hover asked for before the visitor had clicked anything.
  let pendingSrc: string | null = null;
  let disarmGesture: (() => void) | null = null;
  const listeners = new Set<() => void>();

  function setStatus(next: PronunciationStatus) {
    if (status === next) return;
    status = next;
    listeners.forEach((listener) => listener());
  }

  function element() {
    if (!audio) {
      audio = createAudio();
      audio.preload = 'none';
      audio.addEventListener('ended', () => setStatus('idle'));
    }
    return audio;
  }

  // Browsers refuse audio until the visitor has interacted with the page, so
  // a hover before the first click legitimately rejects. Nothing can lift
  // that from script — but the first click anywhere does, and we can use it
  // to play what the visitor already asked for. `capture` so it runs before
  // a card's own click handler, which may then replace it.
  function armGesture() {
    if (disarmGesture) return;
    const doc = getDocument();
    const onGesture = () => {
      disarm();
      if (pendingSrc) void play(pendingSrc);
    };
    const disarm = () => {
      doc.removeEventListener('click', onGesture, true);
      disarmGesture = null;
    };
    doc.addEventListener('click', onGesture, true);
    disarmGesture = disarm;
  }

  async function play(src: string): Promise<PlayOutcome> {
    const el = element();
    el.pause();
    el.src = resolveSrc(src);
    try {
      await el.play();
      pendingSrc = null;
      setStatus('playing');
      return 'played';
    } catch (error) {
      const name = error instanceof DOMException ? error.name : '';
      // A newer play() or a pause() interrupted this one. Whichever call
      // interrupted it owns the status now, so leave it alone.
      if (name === 'AbortError') return 'replaced';
      if (name === 'NotAllowedError') {
        pendingSrc = src;
        setStatus('blocked');
        armGesture();
        return 'blocked';
      }
      // A missing file, an unsupported codec: worth a line in the console,
      // since the build cannot check audio paths the way it checks images.
      console.warn(`Could not play pronunciation ${src}:`, error);
      setStatus('idle');
      return 'failed';
    }
  }

  function stop() {
    pendingSrc = null;
    disarmGesture?.();
    if (audio) {
      audio.pause();
      audio.currentTime = 0;
    }
    setStatus('idle');
  }

  return {
    play,
    stop,
    getStatus: () => status,
    subscribe: (listener) => {
      listeners.add(listener);
      return () => {
        listeners.delete(listener);
      };
    },
  };
}
