// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import aardhommel from './aardhommel.webp';
import akkerhommel from './akkerhommel.webp';
import asbij from './asbij.webp';
import behangersbij from './behangersbij.webp';
import boomhommel from './boomhommel.webp';
import gehoorndeMetselbij from './gehoornde-metselbij.webp';
import hommel from './hommel.webp';
import honingbij from './honingbij.webp';
import houtbij from './houtbij.webp';
import klimopbij from './klimopbij.webp';
import pluimvoetbij from './pluimvoetbij.webp';
import rosseMetselbij from './rosse-metselbij.webp';
import sachembij from './sachembij.webp';
import steenhommel from './steenhommel.webp';
import tuinhommel from './tuinhommel.webp';
import vosje from './vosje.webp';
import weidehommel from './weidehommel.webp';
import wolbij from './wolbij.webp';

export const bees: WordTopic = {
  slug: 'bees',
  title: 'Bees and bumblebees',
  dutchTitle: 'Bijen en hommels',
  description: 'The honey bee, its wild relatives and the bumblebees.',
  entries: [
    {
      slug: 'honingbij',
      dutch: 'de honingbij',
      english: 'the honey bee',
      image: honingbij,
      audio: '/audio/words/insects/bees/honingbij.m4a',
      credit: {
        author: 'Andreas Trepte',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Apis_mellifera_Western_honey_bee.jpg',
      },
    },
    {
      slug: 'hommel',
      dutch: 'de hommel',
      english: 'the bumblebee',
      image: hommel,
      audio: '/audio/words/insects/bees/hommel.m4a',
      credit: {
        author: 'Ivar Leidus',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Bombus_lapidarius_-_Melilotus_officinalis_-_Tallinn.jpg',
      },
    },
    {
      slug: 'aardhommel',
      dutch: 'de aardhommel',
      english: 'the buff-tailed bumblebee',
      image: aardhommel,
      audio: '/audio/words/insects/bees/aardhommel.m4a',
      credit: {
        author: 'Marco Almbauer',
        license: 'CC0',
        licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
        file: 'Bombus_terrestris.jpg',
      },
    },
    {
      slug: 'steenhommel',
      dutch: 'de steenhommel',
      english: 'the red-tailed bumblebee',
      image: steenhommel,
      audio: '/audio/words/insects/bees/steenhommel.m4a',
      credit: {
        author: 'Ivar Leidus',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Bombus_lapidarius_queen_-_Echium_vulgare_-_Keila.jpg',
      },
    },
    {
      slug: 'akkerhommel',
      dutch: 'de akkerhommel',
      english: 'the common carder bee',
      image: akkerhommel,
      audio: '/audio/words/insects/bees/akkerhommel.m4a',
      credit: {
        author: 'André Karwath aka Aka',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Bombus_pascuorum_female_2_(aka).jpg',
      },
    },
    {
      slug: 'tuinhommel',
      dutch: 'de tuinhommel',
      english: 'the garden bumblebee',
      image: tuinhommel,
      audio: '/audio/words/insects/bees/tuinhommel.m4a',
      credit: {
        author: 'Ivar Leidus',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Bombus_hortorum_-_Linaria_vulgaris_-_Valingu.jpg',
      },
    },
    {
      slug: 'boomhommel',
      dutch: 'de boomhommel',
      english: 'the tree bumblebee',
      image: boomhommel,
      audio: '/audio/words/insects/bees/boomhommel.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Tree_bumblebee_(Bombus_hypnorum).jpg',
      },
    },
    {
      slug: 'weidehommel',
      dutch: 'de weidehommel',
      english: 'the early bumblebee',
      image: weidehommel,
      audio: '/audio/words/insects/bees/weidehommel.m4a',
      credit: {
        author: 'Ivar Leidus',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Bombus_pratorum_(male)_-_Knautia_arvensis_-_Keila.jpg',
      },
    },
    {
      slug: 'rosse-metselbij',
      dutch: 'de rosse metselbij',
      english: 'the red mason bee',
      image: rosseMetselbij,
      audio: '/audio/words/insects/bees/rosse-metselbij.m4a',
      credit: {
        author: 'André Karwath aka Aka',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Osmia_rufa_couple_(aka).jpg',
      },
    },
    {
      slug: 'gehoornde-metselbij',
      dutch: 'de gehoornde metselbij',
      english: 'the horned mason bee',
      image: gehoorndeMetselbij,
      audio: '/audio/words/insects/bees/gehoornde-metselbij.m4a',
      credit: {
        author: 'Gilles San Martin',
        license: 'CC BY-SA 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
        file: 'Male_and_female_Osmia_cornuta_-_La_Pairelle.jpg',
      },
    },
    {
      slug: 'behangersbij',
      dutch: 'de behangersbij',
      english: 'the leafcutter bee',
      image: behangersbij,
      audio: '/audio/words/insects/bees/behangersbij.m4a',
      credit: {
        author: 'The Packer Lab',
        license: 'Attribution',
        licenseUrl: '',
        file: 'Megachile_centuncularis_Male.jpg',
      },
    },
    {
      slug: 'houtbij',
      dutch: 'de blauwzwarte houtbij',
      english: 'the violet carpenter bee',
      image: houtbij,
      audio: '/audio/words/insects/bees/houtbij.m4a',
      credit: {
        author: 'Gideon Pisanty (Gidip) גדעון פיזנטי',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: 'Xylocopa_violacea_female_1.jpg',
      },
    },
    {
      slug: 'vosje',
      dutch: 'het vosje',
      english: 'the tawny mining bee',
      image: vosje,
      audio: '/audio/words/insects/bees/vosje.m4a',
      credit: {
        author: 'Entomart',
        license: 'Attribution',
        licenseUrl: '',
        file: 'Andrena_fulva01.jpg',
      },
    },
    {
      slug: 'asbij',
      dutch: 'de asbij',
      english: 'the ashy mining bee',
      image: asbij,
      audio: '/audio/words/insects/bees/asbij.m4a',
      credit: {
        author: 'orangeaurochs',
        license: 'CC BY 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
        file: 'Andrena_cineraria.jpg',
      },
    },
    {
      slug: 'wolbij',
      dutch: 'de grote wolbij',
      english: 'the wool carder bee',
      image: wolbij,
      audio: '/audio/words/insects/bees/wolbij.m4a',
      credit: {
        author: 'Bruce Marlin',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Anthidium_manicatum_male.jpg',
      },
    },
    {
      slug: 'pluimvoetbij',
      dutch: 'de pluimvoetbij',
      english: 'the pantaloon bee',
      image: pluimvoetbij,
      audio: '/audio/words/insects/bees/pluimvoetbij.m4a',
      credit: {
        author: 'Christian Fischer',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'DasypodaHirtipesFemale1.jpg',
      },
    },
    {
      slug: 'klimopbij',
      dutch: 'de klimopbij',
      english: 'the ivy bee',
      image: klimopbij,
      audio: '/audio/words/insects/bees/klimopbij.m4a',
      credit: {
        author: 'Didier Descouens',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: '(MHNT)_Colletes_hederae_on_Hederae_inflorescence.jpg',
      },
    },
    {
      slug: 'sachembij',
      dutch: 'de gewone sachembij',
      english: 'the hairy-footed flower bee',
      image: sachembij,
      audio: '/audio/words/insects/bees/sachembij.m4a',
      credit: {
        author: 'pjt56',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: 'Anthophora_plumipes_male.jpg',
      },
    },
  ],
};
