// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import akita from './akita.jpg';
import australischeHerder from './australische-herder.jpg';
import basset from './basset.jpg';
import beagle from './beagle.jpg';
import bernerSennenhond from './berner-sennenhond.jpg';
import borderCollie from './border-collie.jpg';
import boxer from './boxer.jpg';
import chihuahua from './chihuahua.jpg';
import cockerSpaniel from './cocker-spaniel.jpg';
import dalmatier from './dalmatier.jpg';
import doberman from './doberman.jpg';
import duitseDog from './duitse-dog.jpg';
import duitseHerder from './duitse-herder.jpg';
import goldenRetriever from './golden-retriever.jpg';
import husky from './husky.jpg';
import ierseSetter from './ierse-setter.jpg';
import jackRussell from './jack-russell.jpg';
import labrador from './labrador.jpg';
import mopshond from './mopshond.jpg';
import newfoundlander from './newfoundlander.jpg';
import poedel from './poedel.jpg';
import rottweiler from './rottweiler.jpg';
import samojeed from './samojeed.jpg';
import shibaInu from './shiba-inu.jpg';
import shihTzu from './shih-tzu.jpg';
import sintBernard from './sint-bernard.jpg';
import teckel from './teckel.jpg';
import whippet from './whippet.jpg';
import windhond from './windhond.jpg';
import yorkshireTerrier from './yorkshire-terrier.jpg';

export const dogs: WordTopic = {
  slug: 'dogs',
  title: 'Dogs',
  dutchTitle: 'Honden',
  description: 'Dog breeds from de teckel to de Duitse dog.',
  entries: [
    {
      slug: 'labrador',
      dutch: 'de labrador',
      english: 'the Labrador',
      image: labrador,
      audio: '/audio/words/dogs/labrador.m4a',
      credit: {
        author: 'IDS.photos from Tiverton, UK',
        license: 'CC BY-SA 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
        file: 'Labrador_on_Quantock_(2175262184).jpg',
      },
    },
    {
      slug: 'duitse-herder',
      dutch: 'de Duitse herder',
      english: 'the German Shepherd',
      image: duitseHerder,
      audio: '/audio/words/dogs/duitse-herder.m4a',
      credit: {
        author: 'gomagoti',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'German_Shepherd_-_DSC_0346_(10096362833).jpg',
      },
    },
    {
      slug: 'teckel',
      dutch: 'de teckel',
      english: 'the dachshund',
      image: teckel,
      audio: '/audio/words/dogs/teckel.m4a',
      credit: {
        author: 'Katemil94',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: '닥스훈트(단모종)_(Dachshund_(Short)).jpg',
      },
    },
    {
      slug: 'poedel',
      dutch: 'de poedel',
      english: 'the poodle',
      image: poedel,
      audio: '/audio/words/dogs/poedel.m4a',
      credit: {
        author: 'Tim Wilson from Blaine, MN, USA',
        license: 'CC BY 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
        file: 'Full_attention_(8067543690).jpg',
      },
    },
    {
      slug: 'golden-retriever',
      dutch: 'de golden retriever',
      english: 'the Golden Retriever',
      image: goldenRetriever,
      audio: '/audio/words/dogs/golden-retriever.m4a',
      credit: {
        author: 'Dukedestiny01.jpg: "Janneke Vreugdenhil" derivative work: Anka Friedri',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Golden_Retriever_Dukedestiny01_drvd.jpg',
      },
    },
    {
      slug: 'beagle',
      dutch: 'de beagle',
      english: 'the beagle',
      image: beagle,
      audio: '/audio/words/dogs/beagle.m4a',
      credit: {
        author: 'Wikimedia Commons contributor',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Beagle_600.jpg',
      },
    },
    {
      slug: 'rottweiler',
      dutch: 'de rottweiler',
      english: 'the Rottweiler',
      image: rottweiler,
      audio: '/audio/words/dogs/rottweiler.m4a',
      credit: {
        author: 'Dr. Manfred Herrmann Allgemeiner Deutscher Rottweiler-Klub (ADRK) e.V.',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Rottweiler_standing_facing_left.jpg',
      },
    },
    {
      slug: 'boxer',
      dutch: 'de boxer',
      english: 'the boxer',
      image: boxer,
      audio: '/audio/words/dogs/boxer.m4a',
      credit: {
        author: 'Mood210',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Male_fawn_Boxer_undocked.jpg',
      },
    },
    {
      slug: 'chihuahua',
      dutch: 'de chihuahua',
      english: 'the chihuahua',
      image: chihuahua,
      audio: '/audio/words/dogs/chihuahua.m4a',
      credit: {
        author: 'Bonnie van den Born, http://www.bonfoto.nl. The original uploader was',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Chihuahua1_bvdb.jpg',
      },
    },
    {
      slug: 'mopshond',
      dutch: 'de mopshond',
      english: 'the pug',
      image: mopshond,
      audio: '/audio/words/dogs/mopshond.m4a',
      credit: {
        author: 'Xidrep',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Mops-duke-mopszucht-vom-maegdebrunnen.jpg',
      },
    },
    {
      slug: 'husky',
      dutch: 'de Siberische husky',
      english: 'the Siberian Husky',
      image: husky,
      audio: '/audio/words/dogs/husky.m4a',
      credit: {
        author: 'xJaM (talk · contribs)',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Husky_L.jpg',
      },
    },
    {
      slug: 'border-collie',
      dutch: 'de border collie',
      english: 'the Border Collie',
      image: borderCollie,
      audio: '/audio/words/dogs/border-collie.m4a',
      credit: {
        author: 'Wikimedia Commons contributor',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Border_Collie_600.jpg',
      },
    },
    {
      slug: 'dalmatier',
      dutch: 'de dalmatiër',
      english: 'the Dalmatian',
      image: dalmatier,
      audio: '/audio/words/dogs/dalmatier.m4a',
      credit: {
        author: 'Bradlien',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Sun_Dog_Dalmatian.jpg',
      },
    },
    {
      slug: 'sint-bernard',
      dutch: 'de sint-bernard',
      english: 'the St. Bernard',
      image: sintBernard,
      audio: '/audio/words/dogs/sint-bernard.m4a',
      credit: {
        author: 'Blanky',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Hummel_Vedor_vd_Robandahoeve.jpg',
      },
    },
    {
      slug: 'doberman',
      dutch: 'de dobermann',
      english: 'the Dobermann',
      image: doberman,
      audio: '/audio/words/dogs/doberman.m4a',
      credit: {
        author: 'Miroslav Cacik',
        license: 'Copyrighted free use',
        licenseUrl: '',
        file: 'Dobermann_handling.jpg',
      },
    },
    {
      slug: 'duitse-dog',
      dutch: 'de Duitse dog',
      english: 'the Great Dane',
      image: duitseDog,
      audio: '/audio/words/dogs/duitse-dog.m4a',
      credit: {
        author: 'Lilly M',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Dog_niemiecki_żółty_LM980.jpg',
      },
    },
    {
      slug: 'shih-tzu',
      dutch: 'de shih tzu',
      english: 'the Shih Tzu',
      image: shihTzu,
      audio: '/audio/words/dogs/shih-tzu.m4a',
      credit: {
        author: 'Canino21',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Shihtzu_(cropped).jpg',
      },
    },
    {
      slug: 'jack-russell',
      dutch: 'de jack russell terriër',
      english: 'the Jack Russell Terrier',
      image: jackRussell,
      audio: '/audio/words/dogs/jack-russell.m4a',
      credit: {
        author: 'Plank',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: 'Jack_Russell_Terrier_1.jpg',
      },
    },
    {
      slug: 'yorkshire-terrier',
      dutch: 'de yorkshireterriër',
      english: 'the Yorkshire Terrier',
      image: yorkshireTerrier,
      audio: '/audio/words/dogs/yorkshire-terrier.m4a',
      credit: {
        author: 'Svenska Mässan from Sweden',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: '(2_version)_Grupp_3,_YORKSHIRETERRIER,_NO_UCH_SE_UCH_Oxzar_Amazing_Bel’s_Toffy_(24310212305).jpg',
      },
    },
    {
      slug: 'cocker-spaniel',
      dutch: 'de cockerspaniël',
      english: 'the Cocker Spaniel',
      image: cockerSpaniel,
      audio: '/audio/words/dogs/cocker-spaniel.m4a',
      credit: {
        author: 'Jean-Pol GRANDMONT',
        license: 'CC BY 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/4.0',
        file: '"Bill"_-_Cocker_spaniel_anglais_2.JPG',
      },
    },
    {
      slug: 'shiba-inu',
      dutch: 'de shiba inu',
      english: 'the Shiba Inu',
      image: shibaInu,
      audio: '/audio/words/dogs/shiba-inu.m4a',
      credit: {
        author: 'Takashiba at English Wikipedia',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Taka_Shiba.jpg',
      },
    },
    {
      slug: 'akita',
      dutch: 'de akita',
      english: 'the Akita',
      image: akita,
      audio: '/audio/words/dogs/akita.m4a',
      credit: {
        author: 'Peter Theakston; Keetanii; Melodorakitas; Sevenfatdogs',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: 'Akita_Collage.png',
      },
    },
    {
      slug: 'samojeed',
      dutch: 'de samojeed',
      english: 'the Samoyed',
      image: samojeed,
      audio: '/audio/words/dogs/samojeed.m4a',
      credit: {
        author: 'No machine-readable author provided. Pleple2000 assumed (based on copy',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Samojed00.jpg',
      },
    },
    {
      slug: 'berner-sennenhond',
      dutch: 'de berner sennenhond',
      english: 'the Bernese Mountain Dog',
      image: bernerSennenhond,
      audio: '/audio/words/dogs/berner-sennenhond.m4a',
      credit: {
        author: 'FriendlyToaster',
        license: 'CC BY 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/4.0',
        file: '3-BerneseMountainDogInGrass.jpg',
      },
    },
    {
      slug: 'australische-herder',
      dutch: 'de Australische herder',
      english: 'the Australian Shepherd',
      image: australischeHerder,
      audio: '/audio/words/dogs/australische-herder.m4a',
      credit: {
        author: 'Trickdog-Fina',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Australian_Shepherd_red_bi.JPG',
      },
    },
    {
      slug: 'whippet',
      dutch: 'de whippet',
      english: 'the whippet',
      image: whippet,
      audio: '/audio/words/dogs/whippet.m4a',
      credit: {
        author: 'Canarian',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Whippet_2018_6.jpg',
      },
    },
    {
      slug: 'basset',
      dutch: 'de bassethond',
      english: 'the Basset Hound',
      image: basset,
      audio: '/audio/words/dogs/basset.m4a',
      credit: {
        author: 'Cali1008',
        license: 'Public domain',
        licenseUrl: '',
        file: 'BassetHound_profil.jpg',
      },
    },
    {
      slug: 'newfoundlander',
      dutch: 'de newfoundlander',
      english: 'the Newfoundland',
      image: newfoundlander,
      audio: '/audio/words/dogs/newfoundlander.m4a',
      credit: {
        author: 'Flickr user DanDee Shots',
        license: 'CC BY 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
        file: 'Newfoundland_dog_Smoky.jpg',
      },
    },
    {
      slug: 'ierse-setter',
      dutch: 'de Ierse setter',
      english: 'the Irish Setter',
      image: ierseSetter,
      audio: '/audio/words/dogs/ierse-setter.m4a',
      credit: {
        author: 'Luis Miguel Bugallo Sánchez (Lmbuga Commons)(Lmbuga Galipedia) Public',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Can_Setter_dog_GFDL.jpg',
      },
    },
    {
      slug: 'windhond',
      dutch: 'de windhond',
      english: 'the greyhound',
      image: windhond,
      audio: '/audio/words/dogs/windhond.m4a',
      credit: {
        author: 'Neurodoc',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'GraceTheGreyhound.jpg',
      },
    },
  ],
};
