// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import bindweefsel from './bindweefsel.webp';
import cel from './cel.webp';
import celkern from './celkern.webp';
import celmembraan from './celmembraan.webp';
import chromosoom from './chromosoom.webp';
import mitochondrium from './mitochondrium.webp';
import orgaan from './orgaan.webp';
import spierweefsel from './spierweefsel.webp';
import stamcel from './stamcel.webp';
import vetweefsel from './vetweefsel.webp';
import weefsel from './weefsel.webp';
import zenuwweefsel from './zenuwweefsel.webp';

export const cellsAndTissues: WordTopic = {
  slug: 'cells-and-tissues',
  title: 'Cells and tissues',
  dutchTitle: 'Cellen en weefsels',
  description: 'What every organ is built from, down to het chromosoom.',
  entries: [
    {
      slug: 'orgaan',
      dutch: 'het orgaan',
      english: 'the organ',
      image: orgaan,
      audio: '/audio/words/body/cells-and-tissues/orgaan.m4a',
      credit: {
        author: 'Mikael Häggström',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Internal_organs.png',
      },
    },
    {
      slug: 'cel',
      dutch: 'de cel',
      english: 'the cell',
      image: cel,
      audio: '/audio/words/body/cells-and-tissues/cel.m4a',
      credit: {
        author: 'Unknown author',
        license: 'CC BY 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/4.0',
        file: 'Typical_human_cell.tif',
      },
    },
    {
      slug: 'celkern',
      dutch: 'de celkern',
      english: 'the cell nucleus',
      image: celkern,
      audio: '/audio/words/body/cells-and-tissues/celkern.m4a',
      credit: {
        author: 'TenOfAllTrades at English Wikipedia',
        license: 'Public domain',
        licenseUrl: '',
        file: 'HeLa_cells_stained_with_Hoechst_33258.jpg',
      },
    },
    {
      slug: 'celmembraan',
      dutch: 'het celmembraan',
      english: 'the cell membrane',
      image: celmembraan,
      audio: '/audio/words/body/cells-and-tissues/celmembraan.m4a',
      credit: {
        author: 'Dhatfield',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Cell_membrane_detailed_diagram_4.svg',
      },
    },
    {
      slug: 'mitochondrium',
      dutch: 'het mitochondrium',
      english: 'the mitochondrion',
      image: mitochondrium,
      audio: '/audio/words/body/cells-and-tissues/mitochondrium.m4a',
      credit: {
        author: 'Mariana Ruiz Villarreal LadyofHats',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Animal_mitochondrion_diagram_en.svg',
      },
    },
    {
      slug: 'chromosoom',
      dutch: 'het chromosoom',
      english: 'the chromosome',
      image: chromosoom,
      audio: '/audio/words/body/cells-and-tissues/chromosoom.m4a',
      credit: {
        author: 'File:Chromosome-upright.png Original version: Magnus Manske, this…',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Chromosome.svg',
      },
    },
    {
      slug: 'stamcel',
      dutch: 'de stamcel',
      english: 'the stem cell',
      image: stamcel,
      audio: '/audio/words/body/cells-and-tissues/stamcel.m4a',
      credit: {
        author: 'Mike Jones',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Stem cells diagram.png',
      },
    },
    {
      slug: 'weefsel',
      dutch: 'het weefsel',
      english: 'the tissue',
      image: weefsel,
      audio: '/audio/words/body/cells-and-tissues/weefsel.m4a',
      credit: {
        author: 'OpenStax College',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: '401 Types of Tissue.jpg',
      },
    },
    {
      slug: 'spierweefsel',
      dutch: 'het spierweefsel',
      english: 'the muscle tissue',
      image: spierweefsel,
      audio: '/audio/words/body/cells-and-tissues/spierweefsel.m4a',
      credit: {
        author: 'Prabirrr',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Types_of_muscle.webp',
      },
    },
    {
      slug: 'bindweefsel',
      dutch: 'het bindweefsel',
      english: 'the connective tissue',
      image: bindweefsel,
      audio: '/audio/words/body/cells-and-tissues/bindweefsel.m4a',
      credit: {
        author: 'OpenStax College',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: '408 Connective Tissue.jpg',
      },
    },
    {
      slug: 'vetweefsel',
      dutch: 'het vetweefsel',
      english: 'the fatty tissue',
      image: vetweefsel,
      audio: '/audio/words/body/cells-and-tissues/vetweefsel.m4a',
      credit: {
        author: 'BruceBlaus',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: 'Blausen 0012 AdiposeTissue.png',
      },
    },
    {
      slug: 'zenuwweefsel',
      dutch: 'het zenuwweefsel',
      english: 'the nervous tissue',
      image: zenuwweefsel,
      audio: '/audio/words/body/cells-and-tissues/zenuwweefsel.m4a',
      credit: {
        author: 'BruceBlaus',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: 'Blausen_0672_NeuralTissue.png',
      },
    },
  ],
};
