#!/usr/bin/env python3
"""Write the word data files for the woordenschat zone from scripts/word-topics.json.

Three things have to line up for a word to work: the image file, the audio
clip, and the credit its licence requires. At four words per topic that was
fine by hand; at ninety it is not, so the data is generated from
scripts/word-topics.json (the topics and their words) and each topic's
credits.json (written by fetch-word-images.py).

Outputs, all under apps/woordenschat/content/words:

    <topic>/<topic>.ts   one WordTopic: its title, description and entries
    topics.ts            the list of every topic, in the order of the JSON

To add a word: add it to word-topics.json, then run

    python3 scripts/fetch-word-images.py <topic> --only <slug>
    python3 scripts/generate-pronunciations.py
    python3 scripts/generate-word-data.py

To add a topic: add a new key to word-topics.json with its title, dutchTitle,
description and words, then run the same three commands for the whole topic.
No page needs writing — the zone builds one route per entry in topics.ts.

Editing a generated .ts directly is fine for a one-off tweak, but the next
run of this script overwrites it.
"""

from __future__ import annotations

import json
import pathlib
import re
import subprocess
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
# The words live in the woordenschat zone, not at the repo root.
ROOT = REPO / "apps" / "woordenschat"
CONTENT = ROOT / "content" / "words"
TOPICS = json.loads((pathlib.Path(__file__).resolve().parent / "word-topics.json").read_text())

HEADER = "// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.\n"


def identifier(slug: str) -> str:
    """maine-coon -> maineCoon"""
    head, *rest = slug.split("-")
    return head + "".join(part.capitalize() for part in rest)


def quote(value: str) -> str:
    """Single-quoted TS string literal.

    Credit fields come from free-form Commons HTML, so collapse whitespace
    first — an embedded newline would otherwise emit an unterminated literal.
    """
    flat = re.sub(r"\s+", " ", value).strip()
    return "'" + flat.replace("\\", "\\\\").replace("'", "\\'") + "'"


def write_topic(topic: str, definition: dict, missing: list[str]) -> int:
    credits_path = CONTENT / topic / "credits.json"
    if not credits_path.exists():
        raise SystemExit(f"no credits.json for {topic} — run fetch-word-images.py first")
    credits = json.loads(credits_path.read_text())

    usable = []
    for entry in definition["words"]:
        slug = entry["slug"]
        image = CONTENT / topic / f"{slug}.jpg"
        audio = ROOT / "public" / "audio" / "words" / topic / f"{slug}.m4a"
        if not image.exists() or slug not in credits:
            missing.append(f"{topic}/{slug}: image or credit missing")
            continue
        if not audio.exists():
            missing.append(f"{topic}/{slug}: audio clip missing")
            continue
        usable.append(entry)

    # Sorted so the file passes the import-order lint rule as generated.
    imports = "\n".join(
        f"import {identifier(e['slug'])} from './{e['slug']}.jpg';"
        for e in sorted(usable, key=lambda e: e["slug"])
    )
    entries = ""
    for entry in usable:
        slug = entry["slug"]
        credit = credits[slug]
        entries += (
            "    {\n"
            f"      slug: {quote(slug)},\n"
            f"      dutch: {quote(entry['dutch'])},\n"
            f"      english: {quote(entry['english'])},\n"
            f"      image: {identifier(slug)},\n"
            # Zone-relative, like a next/link href: the player prefixes the
            # basePath at runtime, so the data does not know where it is served.
            f"      audio: '/audio/words/{topic}/{slug}.m4a',\n"
            "      credit: {\n"
            f"        author: {quote(credit['artist'])},\n"
            f"        license: {quote(credit['license'])},\n"
            f"        licenseUrl: {quote(credit.get('licenseUrl', ''))},\n"
            f"        file: {quote(credit['file'])},\n"
            "      },\n"
            "    },\n"
        )

    out = (
        HEADER +
        "import type { WordTopic } from '@/features/words/types';\n\n"
        f"{imports}\n\n"
        f"export const {identifier(topic)}: WordTopic = {{\n"
        f"  slug: {quote(topic)},\n"
        f"  title: {quote(definition['title'])},\n"
        f"  dutchTitle: {quote(definition['dutchTitle'])},\n"
        f"  description: {quote(definition['description'])},\n"
        f"  entries: [\n{entries}  ],\n"
        "};\n"
    )
    (CONTENT / topic / f"{topic}.ts").write_text(out)
    return len(usable)


def write_registry(topics: list[str]) -> None:
    imports = "\n".join(
        f"import {{ {identifier(t)} }} from './{t}/{t}';" for t in sorted(topics)
    )
    listing = "".join(f"  {identifier(t)},\n" for t in topics)
    out = (
        HEADER +
        "import type { WordTopic } from '@/features/words/types';\n\n"
        f"{imports}\n\n"
        "/** Every topic, in the order it is listed on the index page. */\n"
        f"export const wordTopics: WordTopic[] = [\n{listing}];\n"
    )
    (CONTENT / "topics.ts").write_text(out)


def main() -> int:
    missing: list[str] = []
    for topic, definition in TOPICS.items():
        count = write_topic(topic, definition, missing)
        print(f"{topic}.ts: {count} entries")
    write_registry(list(TOPICS))
    print("topics.ts")

    # Hand the quoting and wrapping decisions to Prettier rather than mirroring
    # its rules here, so a regenerated file never shows up as a format diff.
    written = [CONTENT / "topics.ts", *(CONTENT / t / f"{t}.ts" for t in TOPICS)]
    subprocess.run(
        ["pnpm", "exec", "prettier", "--write", "--log-level", "warn", *map(str, written)],
        cwd=REPO,
        check=True,
    )

    if missing:
        print(f"\nskipped {len(missing)}:")
        for line in missing:
            print("  " + line)
    return 0


if __name__ == "__main__":
    sys.exit(main())
