#!/usr/bin/env python3
"""Write the word data files for the woordenschat zone from scripts/word-topics.json.

Three things have to line up for a word to work: the image file, the audio
clip, and the credit its licence requires. At four words per topic that was
fine by hand; at ninety it is not, so the data is generated from
scripts/word-topics.json (the topics and their words) and each topic's
credits.json (written by fetch-word-images.py).

Outputs, all under apps/woordenschat/content/words:

    <topic>/<topic>.ts             one WordTopic: its title, description and entries
    <section>/<topic>/<topic>.ts   the same, for a topic that belongs to a section
    <section>/<section>.ts         one WordSection: its groups of topics
    topics.ts                      the list of every topic and section, in the order of the JSON

To add a word: add it to word-topics.json, then run

    python3 scripts/fetch-word-images.py <topic> --only <slug>
    python3 scripts/generate-pronunciations.py
    python3 scripts/generate-word-data.py

To add a topic: add a new key to word-topics.json with its title, dutchTitle,
description and words, then run the same three commands for the whole topic.
No page needs writing — the zone builds one route per entry in topics.ts.

A section is a key with `groups` instead of `words`; word_topics.py describes
the shape. Its topics are named by path on the command line: body/senses.

Editing a generated .ts directly is fine for a one-off tweak, but the next
run of this script overwrites it.
"""

from __future__ import annotations

import json
import pathlib
import re
import subprocess
import sys

from word_topics import AUDIO, CONTENT, DEFINITIONS, REPO, is_section, section_topics

HEADER = "// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.\n"


def identifier(slug: str) -> str:
    """maine-coon -> maineCoon"""
    head, *rest = slug.split("-")
    return head + "".join(part.capitalize() for part in rest)


def extension(credit: dict) -> str:
    """The saved image's format. A Commons SVG is fetched as a PNG, so the
    extension is whatever fetch-word-images.py recorded; the photographs
    predate that field and are all JPEG."""
    return credit.get("extension", "jpg")


def quote(value: str) -> str:
    """Single-quoted TS string literal.

    Credit fields come from free-form Commons HTML, so collapse whitespace
    first — an embedded newline would otherwise emit an unterminated literal.
    """
    flat = re.sub(r"\s+", " ", value).strip()
    return "'" + flat.replace("\\", "\\\\").replace("'", "\\'") + "'"


def write_topic(topic: str, definition: dict, missing: list[str]) -> pathlib.Path:
    """`topic` is the path under content/words: "cats", "body/senses"."""
    name = topic.rsplit("/", 1)[-1]
    credits_path = CONTENT / topic / "credits.json"
    if not credits_path.exists():
        raise SystemExit(f"no credits.json for {topic} — run fetch-word-images.py first")
    credits = json.loads(credits_path.read_text())

    usable = []
    for entry in definition["words"]:
        slug = entry["slug"]
        image = CONTENT / topic / f"{slug}.{extension(credits.get(slug, {}))}"
        audio = AUDIO / topic / f"{slug}.m4a"
        if not image.exists() or slug not in credits:
            missing.append(f"{topic}/{slug}: image or credit missing")
            continue
        if not audio.exists():
            missing.append(f"{topic}/{slug}: audio clip missing")
            continue
        usable.append(entry)

    # Sorted so the file passes the import-order lint rule as generated.
    imports = "\n".join(
        f"import {identifier(e['slug'])} from './{e['slug']}.{extension(credits[e['slug']])}';"
        for e in sorted(usable, key=lambda e: e["slug"])
    )
    entries = ""
    for entry in usable:
        slug = entry["slug"]
        credit = credits[slug]
        entries += (
            "    {\n"
            f"      slug: {quote(slug)},\n"
            f"      dutch: {quote(entry['dutch'])},\n"
            f"      english: {quote(entry['english'])},\n"
            f"      image: {identifier(slug)},\n"
            # Zone-relative, like a next/link href: the player prefixes the
            # basePath at runtime, so the data does not know where it is served.
            f"      audio: '/audio/words/{topic}/{slug}.m4a',\n"
            "      credit: {\n"
            f"        author: {quote(credit['artist'])},\n"
            f"        license: {quote(credit['license'])},\n"
            f"        licenseUrl: {quote(credit.get('licenseUrl', ''))},\n"
            f"        file: {quote(credit['file'])},\n"
            "      },\n"
            "    },\n"
        )

    out = (
        HEADER +
        "import type { WordTopic } from '@/features/words/types';\n\n"
        f"{imports}\n\n"
        f"export const {identifier(name)}: WordTopic = {{\n"
        f"  slug: {quote(name)},\n"
        f"  title: {quote(definition['title'])},\n"
        f"  dutchTitle: {quote(definition['dutchTitle'])},\n"
        f"  description: {quote(definition['description'])},\n"
        f"  entries: [\n{entries}  ],\n"
        "};\n"
    )
    path = CONTENT / topic / f"{name}.ts"
    path.write_text(out)
    print(f"{topic}: {len(usable)} entries")
    return path


def write_section(section: str, definition: dict) -> pathlib.Path:
    imports = "\n".join(
        f"import {{ {identifier(t)} }} from './{t}/{t}';" for t in sorted(section_topics(definition))
    )
    groups = ""
    for group in definition["groups"]:
        groups += (
            "    {\n"
            f"      title: {quote(group['title'])},\n"
            f"      dutchTitle: {quote(group['dutchTitle'])},\n"
            f"      topics: [{', '.join(identifier(t) for t in group['topics'])}],\n"
            "    },\n"
        )
    out = (
        HEADER +
        "import type { WordSection } from '@/features/words/types';\n\n"
        f"{imports}\n\n"
        f"export const {identifier(section)}: WordSection = {{\n"
        f"  slug: {quote(section)},\n"
        f"  title: {quote(definition['title'])},\n"
        f"  dutchTitle: {quote(definition['dutchTitle'])},\n"
        f"  description: {quote(definition['description'])},\n"
        f"  groups: [\n{groups}  ],\n"
        "};\n"
    )
    path = CONTENT / section / f"{section}.ts"
    path.write_text(out)
    return path


def write_registry(topics: list[str]) -> None:
    imports = "\n".join(
        f"import {{ {identifier(t)} }} from './{t}/{t}';" for t in sorted(topics)
    )
    listing = "".join(f"  {identifier(t)},\n" for t in topics)
    out = (
        HEADER +
        "import type { WordSection, WordTopic } from '@/features/words/types';\n\n"
        f"{imports}\n\n"
        "/** Every topic and section, in the order it is listed on the index page. */\n"
        f"export const wordTopics: (WordTopic | WordSection)[] = [\n{listing}];\n"
    )
    (CONTENT / "topics.ts").write_text(out)


def main() -> int:
    missing: list[str] = []
    written = [CONTENT / "topics.ts"]
    for slug, definition in DEFINITIONS.items():
        if is_section(definition):
            for child, topic in section_topics(definition).items():
                written.append(write_topic(f"{slug}/{child}", topic, missing))
            written.append(write_section(slug, definition))
        else:
            written.append(write_topic(slug, definition, missing))
    write_registry(list(DEFINITIONS))
    print("topics.ts")

    # Hand the quoting and wrapping decisions to Prettier rather than mirroring
    # its rules here, so a regenerated file never shows up as a format diff.
    subprocess.run(
        ["pnpm", "exec", "prettier", "--write", "--log-level", "warn", *map(str, written)],
        cwd=REPO,
        check=True,
    )

    if missing:
        print(f"\nskipped {len(missing)}:")
        for line in missing:
            print("  " + line)
    return 0


if __name__ == "__main__":
    sys.exit(main())
