#!/usr/bin/env python3
"""Write content/words/<topic>/<topic>.ts from the topic definitions.

Three things have to line up for a word to work: the image file, the audio
clip, and the credit its licence requires. At four words per topic that was
fine by hand; at ninety it is not, so the data file is generated from
scripts/word-topics.json (the words) and each topic's credits.json (written by
fetch-word-images.py).

To add a word: add it to word-topics.json, then run

    python3 scripts/fetch-word-images.py <topic> --only <slug>
    python3 scripts/generate-pronunciations.py
    python3 scripts/generate-word-data.py

Editing the generated .ts directly is fine for a one-off tweak, but the next
run of this script overwrites it.
"""

from __future__ import annotations

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONTENT = ROOT / "content" / "words"
TOPICS = json.loads((pathlib.Path(__file__).resolve().parent / "word-topics.json").read_text())


def identifier(slug: str) -> str:
    """maine-coon -> maineCoon"""
    head, *rest = slug.split("-")
    return head + "".join(part.capitalize() for part in rest)


def quote(value: str) -> str:
    """Single-quoted TS string literal.

    Credit fields come from free-form Commons HTML, so collapse whitespace
    first — an embedded newline would otherwise emit an unterminated literal.
    """
    flat = re.sub(r"\s+", " ", value).strip()
    return "'" + flat.replace("\\", "\\\\").replace("'", "\\'") + "'"


def main() -> int:
    missing: list[str] = []

    for topic, entries in TOPICS.items():
        credits_path = CONTENT / topic / "credits.json"
        if not credits_path.exists():
            print(f"no credits.json for {topic} — run fetch-word-images.py first")
            return 1
        credits = json.loads(credits_path.read_text())

        usable = []
        for entry in entries:
            slug = entry["slug"]
            image = CONTENT / topic / f"{slug}.jpg"
            audio = ROOT / "public" / "audio" / "words" / topic / f"{slug}.m4a"
            if not image.exists() or slug not in credits:
                missing.append(f"{topic}/{slug}: image or credit missing")
                continue
            if not audio.exists():
                missing.append(f"{topic}/{slug}: audio clip missing")
                continue
            usable.append(entry)

        imports = "\n".join(
            f"import {identifier(e['slug'])} from './{e['slug']}.jpg';" for e in usable
        )
        body = ""
        for entry in usable:
            slug = entry["slug"]
            credit = credits[slug]
            body += (
                "  {\n"
                f"    slug: {quote(slug)},\n"
                f"    dutch: {quote(entry['dutch'])},\n"
                f"    english: {quote(entry['english'])},\n"
                f"    image: {identifier(slug)},\n"
                f"    audio: '/audio/words/{topic}/{slug}.m4a',\n"
                "    credit: {\n"
                f"      author: {quote(credit['artist'])},\n"
                f"      license: {quote(credit['license'])},\n"
                f"      licenseUrl: {quote(credit.get('licenseUrl', ''))},\n"
                f"      file: {quote(credit['file'])},\n"
                "    },\n"
                "  },\n"
            )

        variable = topic
        out = (
            "// Generated by scripts/generate-word-data.py — see that file to add a word.\n"
            "import type { WordEntry } from '@/features/words/types';\n\n"
            f"{imports}\n\n"
            f"export const {variable}: WordEntry[] = [\n{body}];\n"
        )
        (CONTENT / topic / f"{topic}.ts").write_text(out)
        print(f"{topic}.ts: {len(usable)} entries")

    if missing:
        print(f"\nskipped {len(missing)}:")
        for line in missing:
            print("  " + line)
    return 0


if __name__ == "__main__":
    sys.exit(main())
