// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import baarmoeder from './baarmoeder.png';
import blaas from './blaas.png';
import eicel from './eicel.png';
import eierstok from './eierstok.png';
import eileider from './eileider.jpg';
import embryo from './embryo.png';
import foetus from './foetus.png';
import melkklier from './melkklier.png';
import navelstreng from './navelstreng.jpg';
import nier from './nier.png';
import nierbekken from './nierbekken.jpg';
import placenta from './placenta.png';
import prostaat from './prostaat.jpg';
import teelbal from './teelbal.png';
import urinebuis from './urinebuis.jpg';
import urineleider from './urineleider.png';
import zaadcel from './zaadcel.jpg';

export const kidneysAndReproduction: WordTopic = {
  slug: 'kidneys-and-reproduction',
  title: 'Kidneys and reproduction',
  dutchTitle: 'Nieren en voortplanting',
  description: 'The organs that filter the blood, and the ones a new life starts in.',
  entries: [
    {
      slug: 'nier',
      dutch: 'de nier',
      english: 'the kidney',
      image: nier,
      audio: '/audio/words/body/kidneys-and-reproduction/nier.m4a',
      credit: {
        author: 'BruceBlaus',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: 'Blausen_0592_KidneyAnatomy_01.png',
      },
    },
    {
      slug: 'nierbekken',
      dutch: 'het nierbekken',
      english: 'the renal pelvis',
      image: nierbekken,
      audio: '/audio/words/body/kidneys-and-reproduction/nierbekken.m4a',
      credit: {
        author: 'Wikimedia Commons contributor',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Illu_kidney2.jpg',
      },
    },
    {
      slug: 'urineleider',
      dutch: 'de urineleider',
      english: 'the ureter',
      image: urineleider,
      audio: '/audio/words/body/kidneys-and-reproduction/urineleider.m4a',
      credit: {
        author: 'BruceBlaus',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Urinary System (Female).png',
      },
    },
    {
      slug: 'blaas',
      dutch: 'de blaas',
      english: 'the bladder',
      image: blaas,
      audio: '/audio/words/body/kidneys-and-reproduction/blaas.m4a',
      credit: {
        author: 'BruceBlaus',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Urinary Sphincter.png',
      },
    },
    {
      slug: 'urinebuis',
      dutch: 'de urinebuis',
      english: 'the urethra',
      image: urinebuis,
      audio: '/audio/words/body/kidneys-and-reproduction/urinebuis.m4a',
      credit: {
        author: 'OpenStax College',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: 'Female_and_Male_Urethra.jpg',
      },
    },
    {
      slug: 'baarmoeder',
      dutch: 'de baarmoeder',
      english: 'the uterus',
      image: baarmoeder,
      audio: '/audio/words/body/kidneys-and-reproduction/baarmoeder.m4a',
      credit: {
        author: 'Original: ‍US Government Vector: Pixelsquid🎱',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Illu_cervix.svg',
      },
    },
    {
      slug: 'eierstok',
      dutch: 'de eierstok',
      english: 'the ovary',
      image: eierstok,
      audio: '/audio/words/body/kidneys-and-reproduction/eierstok.m4a',
      credit: {
        author: 'Source file: LouisBB This file: Svenskbygderna (talk)',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Basic_Female_Reproductive_System_(English).svg',
      },
    },
    {
      slug: 'eileider',
      dutch: 'de eileider',
      english: 'the fallopian tube',
      image: eileider,
      audio: '/audio/words/body/kidneys-and-reproduction/eileider.m4a',
      credit: {
        author: 'https://www.scientificanimations.com',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Fallopian tube.jpg',
      },
    },
    {
      slug: 'eicel',
      dutch: 'de eicel',
      english: 'the egg cell',
      image: eicel,
      audio: '/audio/words/body/kidneys-and-reproduction/eicel.m4a',
      credit: {
        author: 'Henry Vandyke Carter',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Gray3.png',
      },
    },
    {
      slug: 'zaadcel',
      dutch: 'de zaadcel',
      english: 'the sperm cell',
      image: zaadcel,
      audio: '/audio/words/body/kidneys-and-reproduction/zaadcel.m4a',
      credit: {
        author: 'Unknown author',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Sperm-egg.jpg',
      },
    },
    {
      slug: 'prostaat',
      dutch: 'de prostaat',
      english: 'the prostate',
      image: prostaat,
      audio: '/audio/words/body/kidneys-and-reproduction/prostaat.m4a',
      credit: {
        author: 'Created by US government agency National Cancer Institute',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Prostatelead.jpg',
      },
    },
    {
      slug: 'teelbal',
      dutch: 'de teelbal',
      english: 'the testicle',
      image: teelbal,
      audio: '/audio/words/body/kidneys-and-reproduction/teelbal.m4a',
      credit: {
        author: 'Hariadhi',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Testicle_hariadhi.svg',
      },
    },
    {
      slug: 'embryo',
      dutch: 'het embryo',
      english: 'the embryo',
      image: embryo,
      audio: '/audio/words/body/kidneys-and-reproduction/embryo.m4a',
      credit: {
        author: 'Laboratoires Servier',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Reproductive system - Embryo -- Smart-Servier.png',
      },
    },
    {
      slug: 'foetus',
      dutch: 'de foetus',
      english: 'the foetus',
      image: foetus,
      audio: '/audio/words/body/kidneys-and-reproduction/foetus.m4a',
      credit: {
        author: 'Courtesy of NIAID Ryan Kissinger',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Pregnant Human and Fetus in Uterus (NIH BioArt 420 - 633833).png',
      },
    },
    {
      slug: 'placenta',
      dutch: 'de placenta',
      english: 'the placenta',
      image: placenta,
      audio: '/audio/words/body/kidneys-and-reproduction/placenta.m4a',
      credit: {
        author: 'Gray38.png: User Magnus Manske on en.wikipedia derivative work…',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Placenta.svg',
      },
    },
    {
      slug: 'navelstreng',
      dutch: 'de navelstreng',
      english: 'the umbilical cord',
      image: navelstreng,
      audio: '/audio/words/body/kidneys-and-reproduction/navelstreng.m4a',
      credit: {
        author: 'Tristan Denyer',
        license: 'Copyrighted free use',
        licenseUrl: '',
        file: 'Umbilicalcord.jpg',
      },
    },
    {
      slug: 'melkklier',
      dutch: 'de melkklier',
      english: 'the mammary gland',
      image: melkklier,
      audio: '/audio/words/body/kidneys-and-reproduction/melkklier.m4a',
      credit: {
        author: 'Patrick J. Lynch; reworked by Morgoth666',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: 'Breast_anatomy_normal_scheme.png',
      },
    },
  ],
};
