// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import blauweGlazenmaker from './blauwe-glazenmaker.webp';
import bloedrodeHeidelibel from './bloedrode-heidelibel.webp';
import bruineGlazenmaker from './bruine-glazenmaker.webp';
import bruinrodeHeidelibel from './bruinrode-heidelibel.webp';
import gewoneBronlibel from './gewone-bronlibel.webp';
import gewoneOeverlibel from './gewone-oeverlibel.webp';
import glassnijder from './glassnijder.webp';
import groteKeizerlibel from './grote-keizerlibel.webp';
import libel from './libel.webp';
import paardenbijter from './paardenbijter.webp';
import platbuik from './platbuik.webp';
import smaragdlibel from './smaragdlibel.webp';
import viervlek from './viervlek.webp';
import vuurlibel from './vuurlibel.webp';
import zwarteHeidelibel from './zwarte-heidelibel.webp';

export const dragonflies: WordTopic = {
  slug: 'dragonflies',
  title: 'Dragonflies',
  dutchTitle: 'Libellen',
  description: 'They rest with their wings spread and hunt over every Dutch ditch.',
  entries: [
    {
      slug: 'libel',
      dutch: 'de libel',
      english: 'the dragonfly',
      image: libel,
      audio: '/audio/words/insects/dragonflies/libel.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Red_grasshawk_(Neurothemis_fluctuans)_male_Phuket_2.jpg',
      },
    },
    {
      slug: 'grote-keizerlibel',
      dutch: 'de grote keizerlibel',
      english: 'the emperor dragonfly',
      image: groteKeizerlibel,
      audio: '/audio/words/insects/dragonflies/grote-keizerlibel.m4a',
      credit: {
        author: 'Quartl',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: 'Anax_imperator_qtl2.jpg',
      },
    },
    {
      slug: 'blauwe-glazenmaker',
      dutch: 'de blauwe glazenmaker',
      english: 'the southern hawker',
      image: blauweGlazenmaker,
      audio: '/audio/words/insects/dragonflies/blauwe-glazenmaker.m4a',
      credit: {
        author: 'Ebertakis',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Southern_Hawker_Dragonfly_Bavaria_Germany.jpg',
      },
    },
    {
      slug: 'bruine-glazenmaker',
      dutch: 'de bruine glazenmaker',
      english: 'the brown hawker',
      image: bruineGlazenmaker,
      audio: '/audio/words/insects/dragonflies/bruine-glazenmaker.m4a',
      credit: {
        author: 'Darkone (talk · contribs)',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Braune_Mosaikjungfer_(Aeshna_grandis).jpg',
      },
    },
    {
      slug: 'paardenbijter',
      dutch: 'de paardenbijter',
      english: 'the migrant hawker',
      image: paardenbijter,
      audio: '/audio/words/insects/dragonflies/paardenbijter.m4a',
      credit: {
        author: 'Pierre Dalous',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Aesmix.jpg',
      },
    },
    {
      slug: 'glassnijder',
      dutch: 'de glassnijder',
      english: 'the hairy dragonfly',
      image: glassnijder,
      audio: '/audio/words/insects/dragonflies/glassnijder.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Hairy_dragonfly_(Brachytron_pratense)_male_Burren.jpg',
      },
    },
    {
      slug: 'platbuik',
      dutch: 'de platbuik',
      english: 'the broad-bodied chaser',
      image: platbuik,
      audio: '/audio/words/insects/dragonflies/platbuik.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Broad-bodied_chaser_(Libellula_depressa)_male_dorsal_side.jpg',
      },
    },
    {
      slug: 'viervlek',
      dutch: 'de viervlek',
      english: 'the four-spotted chaser',
      image: viervlek,
      audio: '/audio/words/insects/dragonflies/viervlek.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Four-spotted_chaser_dragonfly_(Libellula_quadrimaculata)_male.jpg',
      },
    },
    {
      slug: 'gewone-oeverlibel',
      dutch: 'de gewone oeverlibel',
      english: 'the black-tailed skimmer',
      image: gewoneOeverlibel,
      audio: '/audio/words/insects/dragonflies/gewone-oeverlibel.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Black-tailed_skimmer_(Orthetrum_cancellatum)_male_2_Postojna.jpg',
      },
    },
    {
      slug: 'bloedrode-heidelibel',
      dutch: 'de bloedrode heidelibel',
      english: 'the ruddy darter',
      image: bloedrodeHeidelibel,
      audio: '/audio/words/insects/dragonflies/bloedrode-heidelibel.m4a',
      credit: {
        author: 'Jörg Hempel',
        license: 'CC BY-SA 3.0 de',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/de/deed.en',
        file: 'Sympetrum_sanguineum_LC0316.jpg',
      },
    },
    {
      slug: 'bruinrode-heidelibel',
      dutch: 'de bruinrode heidelibel',
      english: 'the common darter',
      image: bruinrodeHeidelibel,
      audio: '/audio/words/insects/dragonflies/bruinrode-heidelibel.m4a',
      credit: {
        author: 'Loz (L. B. Tettenborn)',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Sympetrum_striolatum_3(loz).jpg',
      },
    },
    {
      slug: 'zwarte-heidelibel',
      dutch: 'de zwarte heidelibel',
      english: 'the black darter',
      image: zwarteHeidelibel,
      audio: '/audio/words/insects/dragonflies/zwarte-heidelibel.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Black darter (Sympetrum danae) male.jpg',
      },
    },
    {
      slug: 'vuurlibel',
      dutch: 'de vuurlibel',
      english: 'the scarlet dragonfly',
      image: vuurlibel,
      audio: '/audio/words/insects/dragonflies/vuurlibel.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Broad_scarlet_(Crocothemis_erythraea)_male_Cyprus.jpg',
      },
    },
    {
      slug: 'smaragdlibel',
      dutch: 'de smaragdlibel',
      english: 'the downy emerald',
      image: smaragdlibel,
      audio: '/audio/words/insects/dragonflies/smaragdlibel.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Downy_emerald_(Cordulia_aenea)_male.jpg',
      },
    },
    {
      slug: 'gewone-bronlibel',
      dutch: 'de gewone bronlibel',
      english: 'the golden-ringed dragonfly',
      image: gewoneBronlibel,
      audio: '/audio/words/insects/dragonflies/gewone-bronlibel.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Golden-ringed_dragonfly_(Cordulegaster_boltonii)_male.jpg',
      },
    },
  ],
};
