// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import amandel from './amandel.webp';
import antilichaam from './antilichaam.webp';
import bijnier from './bijnier.webp';
import bijschildklier from './bijschildklier.webp';
import hypofyse from './hypofyse.webp';
import klier from './klier.webp';
import lymfeklier from './lymfeklier.webp';
import lymfestelsel from './lymfestelsel.webp';
import lymfevat from './lymfevat.webp';
import milt from './milt.webp';
import pijnappelklier from './pijnappelklier.webp';
import schildklier from './schildklier.webp';
import thymus from './thymus.webp';

export const glandsAndImmunity: WordTopic = {
  slug: 'glands-and-immunity',
  title: 'Glands and immunity',
  dutchTitle: 'Klieren en afweer',
  description:
    'The glands that steer the body with hormones, and the lymph system that defends it.',
  entries: [
    {
      slug: 'klier',
      dutch: 'de klier',
      english: 'the gland',
      image: klier,
      audio: '/audio/words/body/glands-and-immunity/klier.m4a',
      credit: {
        author: 'OpenStax College',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: '1801 The Endocrine System.jpg',
      },
    },
    {
      slug: 'hypofyse',
      dutch: 'de hypofyse',
      english: 'the pituitary gland',
      image: hypofyse,
      audio: '/audio/words/body/glands-and-immunity/hypofyse.m4a',
      credit: {
        author: 'Patrick J. Lynch, medical illustrator',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Hypophyse.png',
      },
    },
    {
      slug: 'pijnappelklier',
      dutch: 'de pijnappelklier',
      english: 'the pineal gland',
      image: pijnappelklier,
      audio: '/audio/words/body/glands-and-immunity/pijnappelklier.m4a',
      credit: {
        author: 'Images are generated by Life Science Databases(LSDB).',
        license: 'CC BY-SA 2.1 jp',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en',
        file: 'Pineal_gland.png',
      },
    },
    {
      slug: 'schildklier',
      dutch: 'de schildklier',
      english: 'the thyroid gland',
      image: schildklier,
      audio: '/audio/words/body/glands-and-immunity/schildklier.m4a',
      credit: {
        author: 'CFCF',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Anterior_thyroid.jpg',
      },
    },
    {
      slug: 'bijschildklier',
      dutch: 'de bijschildklier',
      english: 'the parathyroid gland',
      image: bijschildklier,
      audio: '/audio/words/body/glands-and-immunity/bijschildklier.m4a',
      credit: {
        author: 'CFCF',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Illu_thyroid_parathyroid.jpg',
      },
    },
    {
      slug: 'bijnier',
      dutch: 'de bijnier',
      english: 'the adrenal gland',
      image: bijnier,
      audio: '/audio/words/body/glands-and-immunity/bijnier.m4a',
      credit: {
        author: 'Antinksčio sandara.png Author: EdgarasLe',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Adrenal_Gland_detail_-_English.png',
      },
    },
    {
      slug: 'thymus',
      dutch: 'de thymus',
      english: 'the thymus',
      image: thymus,
      audio: '/audio/words/body/glands-and-immunity/thymus.m4a',
      credit: {
        author: 'Wikimedia Commons contributor',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Illu_thymus.jpg',
      },
    },
    {
      slug: 'lymfestelsel',
      dutch: 'het lymfestelsel',
      english: 'the lymphatic system',
      image: lymfestelsel,
      audio: '/audio/words/body/glands-and-immunity/lymfestelsel.m4a',
      credit: {
        author: 'BruceBlaus',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: 'Blausen_0623_LymphaticSystem_Female.png',
      },
    },
    {
      slug: 'lymfevat',
      dutch: 'het lymfevat',
      english: 'the lymph vessel',
      image: lymfevat,
      audio: '/audio/words/body/glands-and-immunity/lymfevat.m4a',
      credit: {
        author: 'SEER',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Illu_lymph_capillary.png',
      },
    },
    {
      slug: 'lymfeklier',
      dutch: 'de lymfeklier',
      english: 'the lymph node',
      image: lymfeklier,
      audio: '/audio/words/body/glands-and-immunity/lymfeklier.m4a',
      credit: {
        author: 'KC Panchal',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Schematic_of_lymph_node_showing_lymph_sinuses.svg',
      },
    },
    {
      slug: 'milt',
      dutch: 'de milt',
      english: 'the spleen',
      image: milt,
      audio: '/audio/words/body/glands-and-immunity/milt.m4a',
      credit: {
        author: 'Cancer Research UK uploader',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Diagram_showing_the_position_of_the_spleen_CRUK_417.svg',
      },
    },
    {
      slug: 'amandel',
      dutch: 'de amandel',
      english: 'the tonsil',
      image: amandel,
      audio: '/audio/words/body/glands-and-immunity/amandel.m4a',
      credit: {
        author: 'Wikimedia Commons contributor',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Tonsils_diagram.jpg',
      },
    },
    {
      slug: 'antilichaam',
      dutch: 'het antilichaam',
      english: 'the antibody',
      image: antilichaam,
      audio: '/audio/words/body/glands-and-immunity/antilichaam.m4a',
      credit: {
        author: 'Fvasconcellos 19:03, 6 May 2007 (UTC)',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Antibody.svg',
      },
    },
  ],
};
