// Generated by scripts/generate-word-data.py — see that file to add a word.
import type { WordEntry } from '@/features/words/types';

import appelboom from './appelboom.jpg';
import berk from './berk.jpg';
import beuk from './beuk.jpg';
import ceder from './ceder.jpg';
import den from './den.jpg';
import eik from './eik.jpg';
import els from './els.jpg';
import es from './es.jpg';
import esdoorn from './esdoorn.jpg';
import haagbeuk from './haagbeuk.jpg';
import hulst from './hulst.jpg';
import iep from './iep.jpg';
import jeneverbes from './jeneverbes.jpg';
import kastanje from './kastanje.jpg';
import kersenboom from './kersenboom.jpg';
import lariks from './lariks.jpg';
import lijsterbes from './lijsterbes.jpg';
import linde from './linde.jpg';
import magnolia from './magnolia.jpg';
import meidoorn from './meidoorn.jpg';
import olijfboom from './olijfboom.jpg';
import perenboom from './perenboom.jpg';
import plataan from './plataan.jpg';
import populier from './populier.jpg';
import spar from './spar.jpg';
import taxus from './taxus.jpg';
import treurwilg from './treurwilg.jpg';
import vlier from './vlier.jpg';
import walnoot from './walnoot.jpg';
import wilg from './wilg.jpg';

export const trees: WordEntry[] = [
  {
    slug: 'beuk',
    dutch: 'de beuk',
    english: 'the beech',
    image: beuk,
    audio: '/audio/words/trees/beuk.m4a',
    credit: {
      author: 'GooseCanada',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      file: 'Fagus-sylvatica-cansiglio-forest-italy.jpg',
    },
  },
  {
    slug: 'eik',
    dutch: 'de eik',
    english: 'the oak',
    image: eik,
    audio: '/audio/words/trees/eik.m4a',
    credit: {
      author: 'Wikimedia Commons contributor',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
      file: 'Quercus_robur.jpg',
    },
  },
  {
    slug: 'berk',
    dutch: 'de berk',
    english: 'the birch',
    image: berk,
    audio: '/audio/words/trees/berk.m4a',
    credit: {
      author: 'Percita at Flickr',
      license: 'CC BY-SA 2.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
      file: 'Betula_pendula_Finland.jpg',
    },
  },
  {
    slug: 'wilg',
    dutch: 'de wilg',
    english: 'the willow',
    image: wilg,
    audio: '/audio/words/trees/wilg.m4a',
    credit: {
      author: 'MPF',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
      file: 'Salix_alba_leaves.jpg',
    },
  },
  {
    slug: 'esdoorn',
    dutch: 'de esdoorn',
    english: 'the maple',
    image: esdoorn,
    audio: '/audio/words/trees/esdoorn.m4a',
    credit: {
      author: 'Martin Bobka (= Martin120)',
      license: 'CC BY-SA 2.5',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
      file: 'Spitz-Ahorn(mbo).jpg',
    },
  },
  {
    slug: 'linde',
    dutch: 'de linde',
    english: 'the linden',
    image: linde,
    audio: '/audio/words/trees/linde.m4a',
    credit: {
      author: 'Wikimedia Commons contributor',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
      file: 'Tilia-cordata2.JPG',
    },
  },
  {
    slug: 'den',
    dutch: 'de den',
    english: 'the pine',
    image: den,
    audio: '/audio/words/trees/den.m4a',
    credit: {
      author: 'Mickaël Delcey (Silverkey)',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
      file: 'Skuleskogen_pine.jpg',
    },
  },
  {
    slug: 'spar',
    dutch: 'de spar',
    english: 'the spruce',
    image: spar,
    audio: '/audio/words/trees/spar.m4a',
    credit: {
      author: 'Ivar Leidus',
      license: 'CC BY-SA 3.0 ee',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/ee/deed.en',
      file: 'Kuusk_Keila-Paldiski_rdt_ääres.jpg',
    },
  },
  {
    slug: 'iep',
    dutch: 'de iep',
    english: 'the elm',
    image: iep,
    audio: '/audio/words/trees/iep.m4a',
    credit: {
      author: 'Ronnie Nijboer',
      license: 'CC0',
      licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
      file: 'RN_Ulmus_glabra_(alnarp_sweden).jpg',
    },
  },
  {
    slug: 'es',
    dutch: 'de es',
    english: 'the ash',
    image: es,
    audio: '/audio/words/trees/es.m4a',
    credit: {
      author: 'No machine-readable author provided. MPF assumed (based on copyright c',
      license: 'CC BY 2.5',
      licenseUrl: 'https://creativecommons.org/licenses/by/2.5',
      file: 'Fraxinus_excelsior.jpg',
    },
  },
  {
    slug: 'populier',
    dutch: 'de populier',
    english: 'the poplar',
    image: populier,
    audio: '/audio/words/trees/populier.m4a',
    credit: {
      author: 'Kenraiz',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
      file: 'Populus_nigra_kz1.jpg',
    },
  },
  {
    slug: 'kastanje',
    dutch: 'de kastanje',
    english: 'the chestnut',
    image: kastanje,
    audio: '/audio/words/trees/kastanje.m4a',
    credit: {
      author: 'User:Kilom691',
      license: 'Public domain',
      licenseUrl: '',
      file: 'Illustration_Aesculus_hippocastanum0_clean.jpg',
    },
  },
  {
    slug: 'haagbeuk',
    dutch: 'de haagbeuk',
    english: 'the hornbeam',
    image: haagbeuk,
    audio: '/audio/words/trees/haagbeuk.m4a',
    credit: {
      author: 'Willow',
      license: 'CC BY 2.5',
      licenseUrl: 'https://creativecommons.org/licenses/by/2.5',
      file: 'Carpinus_betulus_-_Hunsrück_001.jpg',
    },
  },
  {
    slug: 'els',
    dutch: 'de els',
    english: 'the alder',
    image: els,
    audio: '/audio/words/trees/els.m4a',
    credit: {
      author: 'AnRo0002',
      license: 'CC0',
      licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
      file: '20120904Alnus_glutinosa01.jpg',
    },
  },
  {
    slug: 'lijsterbes',
    dutch: 'de lijsterbes',
    english: 'the rowan',
    image: lijsterbes,
    audio: '/audio/words/trees/lijsterbes.m4a',
    credit: {
      author: 'Eeno11',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
      file: 'Rowan_tree_20081002b.jpg',
    },
  },
  {
    slug: 'hulst',
    dutch: 'de hulst',
    english: 'the holly',
    image: hulst,
    audio: '/audio/words/trees/hulst.m4a',
    credit: {
      author: 'Jürgen Howaldt',
      license: 'CC BY-SA 2.0 de',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/de/deed.en',
      file: 'Ilex-aquifolium_(Europaeische_Stechpalme-1).jpg',
    },
  },
  {
    slug: 'taxus',
    dutch: 'de taxus',
    english: 'the yew',
    image: taxus,
    audio: '/audio/words/trees/taxus.m4a',
    credit: {
      author: 'Didier Descouens',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      file: 'Taxus_baccata_MHNT.jpg',
    },
  },
  {
    slug: 'plataan',
    dutch: 'de plataan',
    english: 'the plane tree',
    image: plataan,
    audio: '/audio/words/trees/plataan.m4a',
    credit: {
      author: 'uncredited',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
      file: 'Plane_tree_Grove_Tsav_River.jpg',
    },
  },
  {
    slug: 'walnoot',
    dutch: 'de walnoot',
    english: 'the walnut',
    image: walnoot,
    audio: '/audio/words/trees/walnoot.m4a',
    credit: {
      author: 'Thesupermat',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
      file: 'Noyer_centenaire_en_automne.JPG',
    },
  },
  {
    slug: 'kersenboom',
    dutch: 'de kersenboom',
    english: 'the cherry tree',
    image: kersenboom,
    audio: '/audio/words/trees/kersenboom.m4a',
    credit: {
      author: 'MPF',
      license: 'CC BY 2.5',
      licenseUrl: 'https://creativecommons.org/licenses/by/2.5',
      file: 'Prunus_avium_fruit.jpg',
    },
  },
  {
    slug: 'appelboom',
    dutch: 'de appelboom',
    english: 'the apple tree',
    image: appelboom,
    audio: '/audio/words/trees/appelboom.m4a',
    credit: {
      author: 'Helge Klaus Rieder',
      license: 'CC0',
      licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
      file: 'Elstar Freilichtmuseum Roscheider Hof Ganzer Baum H2.jpg',
    },
  },
  {
    slug: 'perenboom',
    dutch: 'de perenboom',
    english: 'the pear tree',
    image: perenboom,
    audio: '/audio/words/trees/perenboom.m4a',
    credit: {
      author: 'Keith Weller',
      license: 'Public domain',
      licenseUrl: '',
      file: 'Pears.jpg',
    },
  },
  {
    slug: 'vlier',
    dutch: 'de vlier',
    english: 'the elder',
    image: vlier,
    audio: '/audio/words/trees/vlier.m4a',
    credit: {
      author: 'Willow',
      license: 'CC BY 2.5',
      licenseUrl: 'https://creativecommons.org/licenses/by/2.5',
      file: 'Sambucus_nigra_004.jpg',
    },
  },
  {
    slug: 'meidoorn',
    dutch: 'de meidoorn',
    english: 'the hawthorn',
    image: meidoorn,
    audio: '/audio/words/trees/meidoorn.m4a',
    credit: {
      author: 'Elstro',
      license: 'CC BY 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
      file: 'Hawthorn_fruit.JPG',
    },
  },
  {
    slug: 'lariks',
    dutch: 'de lariks',
    english: 'the larch',
    image: lariks,
    audio: '/audio/words/trees/lariks.m4a',
    credit: {
      author: 'Dominicus Johannes Bergsma',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      file: "L'A_de_Bran,_(1798_m)_Val_d'Anniviers._Europese_larix_(Larix_decidua)_01.JPG",
    },
  },
  {
    slug: 'ceder',
    dutch: 'de ceder',
    english: 'the cedar',
    image: ceder,
    audio: '/audio/words/trees/ceder.m4a',
    credit: {
      author: 'Olivier BEZES',
      license: 'CC BY 2.5',
      licenseUrl: 'https://creativecommons.org/licenses/by/2.5',
      file: 'Cèdre_du_Liban_Barouk_2005.jpg',
    },
  },
  {
    slug: 'magnolia',
    dutch: 'de magnolia',
    english: 'the magnolia',
    image: magnolia,
    audio: '/audio/words/trees/magnolia.m4a',
    credit: {
      author: 'William (Ned) Friedman',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      file: 'Magnolia_sieboldii_flower_1.jpg',
    },
  },
  {
    slug: 'olijfboom',
    dutch: 'de olijfboom',
    english: 'the olive tree',
    image: olijfboom,
    audio: '/audio/words/trees/olijfboom.m4a',
    credit: {
      author: 'en:User:Nickfraser',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
      file: 'Olivesfromjordan.jpg',
    },
  },
  {
    slug: 'treurwilg',
    dutch: 'de treurwilg',
    english: 'the weeping willow',
    image: treurwilg,
    audio: '/audio/words/trees/treurwilg.m4a',
    credit: {
      author: 'Fab5669',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      file: 'Château_de_Chenonceau_-_jardin_Russell-Page_(01).jpg',
    },
  },
  {
    slug: 'jeneverbes',
    dutch: 'de jeneverbes',
    english: 'the juniper',
    image: jeneverbes,
    audio: '/audio/words/trees/jeneverbes.m4a',
    credit: {
      author: 'Rasbak at Dutch Wikipedia',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
      file: 'Jeneverbes.jpg',
    },
  },
];
