// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import { cats } from './cats/cats';
import { dogs } from './dogs/dogs';
import { instruments } from './instruments/instruments';
import { trees } from './trees/trees';

/** Every topic, in the order it is listed on the index page. */
export const wordTopics: WordTopic[] = [trees, cats, dogs, instruments];
