// Generated by scripts/generate-word-data.py — see that file to add a word.
import type { WordEntry } from '@/features/words/types';

import abessijn from './abessijn.jpg';
import amerikaanseKorthaar from './amerikaanse-korthaar.jpg';
import bengaal from './bengaal.jpg';
import birmaan from './birmaan.jpg';
import bombay from './bombay.jpg';
import britseKorthaar from './britse-korthaar.jpg';
import burmees from './burmees.jpg';
import chartreux from './chartreux.jpg';
import cornishRex from './cornish-rex.jpg';
import devonRex from './devon-rex.jpg';
import exotischeKorthaar from './exotische-korthaar.jpg';
import maineCoon from './maine-coon.jpg';
import manx from './manx.jpg';
import munchkin from './munchkin.jpg';
import noorseBoskat from './noorse-boskat.jpg';
import ocicat from './ocicat.jpg';
import orientaal from './orientaal.jpg';
import pers from './pers.jpg';
import ragdoll from './ragdoll.jpg';
import russischBlauw from './russisch-blauw.jpg';
import savannah from './savannah.jpg';
import schotseVouwoor from './schotse-vouwoor.jpg';
import selkirkRex from './selkirk-rex.jpg';
import siamees from './siamees.jpg';
import siberischeKat from './siberische-kat.jpg';
import somali from './somali.jpg';
import sphynx from './sphynx.jpg';
import tonkinees from './tonkinees.jpg';
import turkseAngora from './turkse-angora.jpg';
import turkseVan from './turkse-van.jpg';

export const cats: WordEntry[] = [
  {
    slug: 'pers',
    dutch: 'de Perzische kat',
    english: 'the Persian cat',
    image: pers,
    audio: '/audio/words/cats/pers.m4a',
    credit: {
      author: 'The original uploader was Lajoma at Finnish Wikipedia.',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
      file: 'Persialainen.jpg',
    },
  },
  {
    slug: 'siamees',
    dutch: 'de siamees',
    english: 'the Siamese cat',
    image: siamees,
    audio: '/audio/words/cats/siamees.m4a',
    credit: {
      author: 'Meekahoo',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
      file: 'Siamese_cat_Vaillante.JPG',
    },
  },
  {
    slug: 'maine-coon',
    dutch: 'de maine coon',
    english: 'the Maine Coon',
    image: maineCoon,
    audio: '/audio/words/cats/maine-coon.m4a',
    credit: {
      author: 'Wikimedia Commons contributor',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      file: 'Mâle_Black_Silver_Blotched_Tabby.jpeg',
    },
  },
  {
    slug: 'britse-korthaar',
    dutch: 'de Britse korthaar',
    english: 'the British Shorthair',
    image: britseKorthaar,
    audio: '/audio/words/cats/britse-korthaar.m4a',
    credit: {
      author: 'BritishEmpire',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
      file: 'Mystica_from_British_Empire_Cattery.jpg',
    },
  },
  {
    slug: 'ragdoll',
    dutch: 'de ragdoll',
    english: 'the Ragdoll',
    image: ragdoll,
    audio: '/audio/words/cats/ragdoll.m4a',
    credit: {
      author: 'Simone Johnsson',
      license: 'CC BY-SA 2.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
      file: 'Ragdoll_from_Gatil_Ragbelas.jpg',
    },
  },
  {
    slug: 'bengaal',
    dutch: 'de bengaal',
    english: 'the Bengal',
    image: bengaal,
    audio: '/audio/words/cats/bengaal.m4a',
    credit: {
      author: 'User:Lightburst',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      file: 'Paintedcats_Red_Star_standing.jpg',
    },
  },
  {
    slug: 'noorse-boskat',
    dutch: 'de Noorse boskat',
    english: 'the Norwegian Forest cat',
    image: noorseBoskat,
    audio: '/audio/words/cats/noorse-boskat.m4a',
    credit: {
      author: 'Gangburgondes',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
      file: 'Dalaja-Doll-norvégien-ambre-blotched-tabby_avec-blanc_2008_(cropped).jpg',
    },
  },
  {
    slug: 'birmaan',
    dutch: 'de heilige birmaan',
    english: 'the Birman',
    image: birmaan,
    audio: '/audio/words/cats/birmaan.m4a',
    credit: {
      author: 'Kristin Kokkersvold',
      license: 'Copyrighted free use',
      licenseUrl: '',
      file: 'Birmanstrofe.jpg',
    },
  },
  {
    slug: 'abessijn',
    dutch: 'de abessijn',
    english: 'the Abyssinian',
    image: abessijn,
    audio: '/audio/words/cats/abessijn.m4a',
    credit: {
      author: 'Karin Langner-Bahmann',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
      file: 'Gustav_chocolate.jpg',
    },
  },
  {
    slug: 'russisch-blauw',
    dutch: 'de Russisch blauw',
    english: 'the Russian Blue',
    image: russischBlauw,
    audio: '/audio/words/cats/russisch-blauw.m4a',
    credit: {
      author: 'Anna Utekhina http://kidsphoto.ru/',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
      file: 'Russian_blue_kitten_(cropped).jpg',
    },
  },
  {
    slug: 'sphynx',
    dutch: 'de sphynx',
    english: 'the Sphynx',
    image: sphynx,
    audio: '/audio/words/cats/sphynx.m4a',
    credit: {
      author: 'Dmitry Makeev',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      file: 'Sphynx_-_cat._img_031.jpg',
    },
  },
  {
    slug: 'schotse-vouwoor',
    dutch: 'de Schotse vouwoor',
    english: 'the Scottish Fold',
    image: schotseVouwoor,
    audio: '/audio/words/cats/schotse-vouwoor.m4a',
    credit: {
      author: 'Heikki Siltala',
      license: 'CC BY 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
      file: 'Scottish_Fold_-_CFF_cat_show_Heinola_2008-05-03_IMG_7882.JPG',
    },
  },
  {
    slug: 'devon-rex',
    dutch: 'de devon rex',
    english: 'the Devon Rex',
    image: devonRex,
    audio: '/audio/words/cats/devon-rex.m4a',
    credit: {
      author: 'Anna Belial',
      license: 'CC BY 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by/4.0',
      file: 'Devon_Rex_Cassini.jpeg',
    },
  },
  {
    slug: 'cornish-rex',
    dutch: 'de cornish rex',
    english: 'the Cornish Rex',
    image: cornishRex,
    audio: '/audio/words/cats/cornish-rex.m4a',
    credit: {
      author: 'Tomi Tapio K from Helsinki, Finland',
      license: 'CC BY 2.0',
      licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
      file: 'Rex_staredown.jpg',
    },
  },
  {
    slug: 'orientaal',
    dutch: 'de oriëntaal',
    english: 'the Oriental Shorthair',
    image: orientaal,
    audio: '/audio/words/cats/orientaal.m4a',
    credit: {
      author: 'Daly69',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
      file: "Fatale_de_la_légende_d'ali.jpg",
    },
  },
  {
    slug: 'turkse-angora',
    dutch: 'de Turkse angora',
    english: 'the Turkish Angora',
    image: turkseAngora,
    audio: '/audio/words/cats/turkse-angora.m4a',
    credit: {
      author: 'Ankarakediler',
      license: 'CC BY 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
      file: 'Turkish_Angora_in_Ankara_Zoo_(AOÇ).JPG',
    },
  },
  {
    slug: 'turkse-van',
    dutch: 'de Turkse van',
    english: 'the Turkish Van',
    image: turkseVan,
    audio: '/audio/words/cats/turkse-van.m4a',
    credit: {
      author: 'Matsu1024',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      file: 'Turkish_Van_cat_transparent_(cropped).png',
    },
  },
  {
    slug: 'bombay',
    dutch: 'de bombay',
    english: 'the Bombay',
    image: bombay,
    audio: '/audio/words/cats/bombay.m4a',
    credit: {
      author: 'Pititebilette',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
      file: 'Bombay_femelle.JPG',
    },
  },
  {
    slug: 'burmees',
    dutch: 'de burmees',
    english: 'the Burmese',
    image: burmees,
    audio: '/audio/words/cats/burmees.m4a',
    credit: {
      author: 'Heikkisiltala',
      license: 'CC BY 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
      file: 'British_burmese_-_Andel_Alois_at_Cat_show.JPG',
    },
  },
  {
    slug: 'ocicat',
    dutch: 'de ocicat',
    english: 'the Ocicat',
    image: ocicat,
    audio: '/audio/words/cats/ocicat.m4a',
    credit: {
      author: 'Heikki Siltala - catza.net',
      license: 'CC BY 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
      file: 'Topspot_La_Colombina_(Liina)_OCI_c_24_female_kitten_EX1.JPG',
    },
  },
  {
    slug: 'savannah',
    dutch: 'de savannah',
    english: 'the Savannah',
    image: savannah,
    audio: '/audio/words/cats/savannah.m4a',
    credit: {
      author: 'Jason Douglas',
      license: 'Public domain',
      licenseUrl: '',
      file: 'Savannah_Cat_portrait.jpg',
    },
  },
  {
    slug: 'munchkin',
    dutch: 'de munchkin',
    english: 'the Munchkin',
    image: munchkin,
    audio: '/audio/words/cats/munchkin.m4a',
    credit: {
      author: 'Sg0668commons',
      license: 'CC BY 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
      file: 'Longhairedmunchkin.jpg',
    },
  },
  {
    slug: 'manx',
    dutch: 'de manx',
    english: 'the Manx',
    image: manx,
    audio: '/audio/words/cats/manx.m4a',
    credit: {
      author: 'Karen Weaver',
      license: 'CC BY 2.5',
      licenseUrl: 'https://creativecommons.org/licenses/by/2.5',
      file: 'Manx_cat_by_Karen_Weaver.jpg',
    },
  },
  {
    slug: 'siberische-kat',
    dutch: 'de Siberische kat',
    english: 'the Siberian',
    image: siberischeKat,
    audio: '/audio/words/cats/siberische-kat.m4a',
    credit: {
      author: 'Floofymarshmallow',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      file: "Samiha's_Siberian_cat_Moon_Pie.jpg",
    },
  },
  {
    slug: 'chartreux',
    dutch: 'de chartreux',
    english: 'the Chartreux',
    image: chartreux,
    audio: '/audio/words/cats/chartreux.m4a',
    credit: {
      author: 'Heikki Siltala - catza.net',
      license: 'CC BY 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
      file: 'IC_Blue_Melody_Flipper_CHA_male_EX1_CACIB.jpg',
    },
  },
  {
    slug: 'amerikaanse-korthaar',
    dutch: 'de Amerikaanse korthaar',
    english: 'the American Shorthair',
    image: amerikaanseKorthaar,
    audio: '/audio/words/cats/amerikaanse-korthaar.m4a',
    credit: {
      author: 'odin_aka_zero-one',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
      file: 'Jewelkatz_Romeo_Of_Stalker-Bars.jpg',
    },
  },
  {
    slug: 'exotische-korthaar',
    dutch: 'de exotische korthaar',
    english: 'the Exotic Shorthair',
    image: exotischeKorthaar,
    audio: '/audio/words/cats/exotische-korthaar.m4a',
    credit: {
      author: 'Tcm1707',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      file: 'Ginger_Exotic_Shorthair.jpg',
    },
  },
  {
    slug: 'somali',
    dutch: 'de somali',
    english: 'the Somali',
    image: somali,
    audio: '/audio/words/cats/somali.m4a',
    credit: {
      author: 'Матвеева Ирина Владимировна',
      license: 'Public domain',
      licenseUrl: '',
      file: 'Сомалийская_кошка.jpg',
    },
  },
  {
    slug: 'tonkinees',
    dutch: 'de tonkinees',
    english: 'the Tonkinese',
    image: tonkinees,
    audio: '/audio/words/cats/tonkinees.m4a',
    credit: {
      author: 'Luigi Leahy',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      file: 'Tonkinese_Cat_-_Leo.jpg',
    },
  },
  {
    slug: 'selkirk-rex',
    dutch: 'de selkirk rex',
    english: 'the Selkirk Rex',
    image: selkirkRex,
    audio: '/audio/words/cats/selkirk-rex.m4a',
    credit: {
      author: 'Wikimedia Commons contributor',
      license: 'CC-BY-SA-3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/',
      file: 'PolloSelkirkRex.jpg',
    },
  },
];
