// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import dansmug from './dansmug.webp';
import galmug from './galmug.webp';
import gelekoortsmug from './gelekoortsmug.webp';
import knut from './knut.webp';
import kriebelmug from './kriebelmug.webp';
import langpootmug from './langpootmug.webp';
import malariamug from './malariamug.webp';
import motmug from './motmug.webp';
import rouwmug from './rouwmug.webp';
import steekmug from './steekmug.webp';
import tijgermug from './tijgermug.webp';
import wintermug from './wintermug.webp';

export const mosquitoes: WordTopic = {
  slug: 'mosquitoes',
  title: 'Mosquitoes and midges',
  dutchTitle: 'Muggen',
  description: 'Long antennae and thin legs. Only a few of them bite.',
  entries: [
    {
      slug: 'steekmug',
      dutch: 'de steekmug',
      english: 'the mosquito',
      image: steekmug,
      audio: '/audio/words/insects/mosquitoes/steekmug.m4a',
      credit: {
        author: 'Alvesgaspar',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Culex_pipiens_2007-1.jpg',
      },
    },
    {
      slug: 'malariamug',
      dutch: 'de malariamug',
      english: 'the malaria mosquito',
      image: malariamug,
      audio: '/audio/words/insects/mosquitoes/malariamug.m4a',
      credit: {
        author: 'Jim Gathany',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Anopheles_stephensi.jpeg',
      },
    },
    {
      slug: 'tijgermug',
      dutch: 'de tijgermug',
      english: 'the tiger mosquito',
      image: tijgermug,
      audio: '/audio/words/insects/mosquitoes/tijgermug.m4a',
      credit: {
        author: 'James Gathany, CDC',
        license: 'Public domain',
        licenseUrl: '',
        file: 'CDC-Gathany-Aedes-albopictus-1.jpg',
      },
    },
    {
      slug: 'gelekoortsmug',
      dutch: 'de gelekoortsmug',
      english: 'the yellow fever mosquito',
      image: gelekoortsmug,
      audio: '/audio/words/insects/mosquitoes/gelekoortsmug.m4a',
      credit: {
        author: 'Muhammad Mahdi Karim',
        license: 'GFDL 1.2',
        licenseUrl: 'http://www.gnu.org/licenses/old-licenses/fdl-1.2.html',
        file: 'Aedes_aegypti.jpg',
      },
    },
    {
      slug: 'langpootmug',
      dutch: 'de langpootmug',
      english: 'the crane fly',
      image: langpootmug,
      audio: '/audio/words/insects/mosquitoes/langpootmug.m4a',
      credit: {
        author: 'Alvesgaspar',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Tipulidae_April_2008-2.jpg',
      },
    },
    {
      slug: 'dansmug',
      dutch: 'de dansmug',
      english: 'the non-biting midge',
      image: dansmug,
      audio: '/audio/words/insects/mosquitoes/dansmug.m4a',
      credit: {
        author: 'Entomart',
        license: 'Attribution',
        licenseUrl: '',
        file: 'Chironomus_plumosus01.jpg',
      },
    },
    {
      slug: 'knut',
      dutch: 'de knut',
      english: 'the biting midge',
      image: knut,
      audio: '/audio/words/insects/mosquitoes/knut.m4a',
      credit: {
        author: 'Scott Bauer, USDA ARS',
        license: 'Public domain',
        licenseUrl: '',
        file: 'BitingMidge.jpg',
      },
    },
    {
      slug: 'kriebelmug',
      dutch: 'de kriebelmug',
      english: 'the black fly',
      image: kriebelmug,
      audio: '/audio/words/insects/mosquitoes/kriebelmug.m4a',
      credit: {
        author: 'AJC1',
        license: 'CC BY-SA 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
        file: 'Blackfly.jpg',
      },
    },
    {
      slug: 'motmug',
      dutch: 'de motmug',
      english: 'the drain fly',
      image: motmug,
      audio: '/audio/words/insects/mosquitoes/motmug.m4a',
      credit: {
        author: 'Sanjay Acharya',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Clogmia_Albipunctata_or_moth_fly.jpg',
      },
    },
    {
      slug: 'rouwmug',
      dutch: 'de rouwmug',
      english: 'the fungus gnat',
      image: rouwmug,
      audio: '/audio/words/insects/mosquitoes/rouwmug.m4a',
      credit: {
        author: 'gailhampshire from Cradley, Malvern, U.K',
        license: 'CC BY 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
        file: 'Sciara_hemerobioides_-_Flickr_-_gailhampshire.jpg',
      },
    },
    {
      slug: 'galmug',
      dutch: 'de galmug',
      english: 'the gall midge',
      image: galmug,
      audio: '/audio/words/insects/mosquitoes/galmug.m4a',
      credit: {
        author: 'Alvesgaspar',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Fly_December_2007-4.jpg',
      },
    },
    {
      slug: 'wintermug',
      dutch: 'de wintermug',
      english: 'the winter gnat',
      image: wintermug,
      audio: '/audio/words/insects/mosquitoes/wintermug.m4a',
      credit: {
        author: 'Entomart',
        license: 'Attribution',
        licenseUrl: '',
        file: 'Trichocera_hiemalis.jpg',
      },
    },
  ],
};
