// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import bestuiving from './bestuiving.webp';
import bijenkoningin from './bijenkoningin.webp';
import bijenkorf from './bijenkorf.webp';
import bijenwas from './bijenwas.webp';
import dar from './dar.webp';
import gal from './gal.webp';
import honing from './honing.webp';
import honingraat from './honingraat.webp';
import imker from './imker.webp';
import insectenhotel from './insectenhotel.webp';
import mierenhoop from './mierenhoop.webp';
import nectar from './nectar.webp';
import stuifmeel from './stuifmeel.webp';
import termietenheuvel from './termietenheuvel.webp';
import werkbij from './werkbij.webp';
import wespennest from './wespennest.webp';
import zijde from './zijde.webp';
import zwerm from './zwerm.webp';

export const nestsAndHoney: WordTopic = {
  slug: 'nests-and-honey',
  title: 'Nests and honey',
  dutchTitle: 'Nesten en honing',
  description: 'What insects build and make, and what people do with it.',
  entries: [
    {
      slug: 'bijenkorf',
      dutch: 'de bijenkorf',
      english: 'the beehive',
      image: bijenkorf,
      audio: '/audio/words/insects/nests-and-honey/bijenkorf.m4a',
      credit: {
        author: 'Frank Schulenburg',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Beehives_in_Butte_County_(2025)-104A8312.jpg',
      },
    },
    {
      slug: 'honingraat',
      dutch: 'de honingraat',
      english: 'the honeycomb',
      image: honingraat,
      audio: '/audio/words/insects/nests-and-honey/honingraat.m4a',
      credit: {
        author: 'Merdal at Turkish Wikipedia',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Honey_comb.jpg',
      },
    },
    {
      slug: 'honing',
      dutch: 'de honing',
      english: 'the honey',
      image: honing,
      audio: '/audio/words/insects/nests-and-honey/honing.m4a',
      credit: {
        author: 'Scott Bauer, USDA ARS',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Runny_hunny.jpg',
      },
    },
    {
      slug: 'bijenwas',
      dutch: 'de bijenwas',
      english: 'the beeswax',
      image: bijenwas,
      audio: '/audio/words/insects/nests-and-honey/bijenwas.m4a',
      credit: {
        author: 'Jack Soley',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Pure Natural Beeswax Blocks.jpg',
      },
    },
    {
      slug: 'stuifmeel',
      dutch: 'het stuifmeel',
      english: 'the pollen',
      image: stuifmeel,
      audio: '/audio/words/insects/nests-and-honey/stuifmeel.m4a',
      credit: {
        author: 'Friedrich Haag',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Staub 001 2018 06 14.jpg',
      },
    },
    {
      slug: 'nectar',
      dutch: 'de nectar',
      english: 'the nectar',
      image: nectar,
      audio: '/audio/words/insects/nests-and-honey/nectar.m4a',
      credit: {
        author: 'Daiju Azuma',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Nectar.jpg',
      },
    },
    {
      slug: 'bestuiving',
      dutch: 'de bestuiving',
      english: 'the pollination',
      image: bestuiving,
      audio: '/audio/words/insects/nests-and-honey/bestuiving.m4a',
      credit: {
        author: 'Bob Peterson from North Palm Beach, Florida, Planet Earth!',
        license: 'CC BY-SA 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
        file: 'Pollen Dusted Bee (11027119186).jpg',
      },
    },
    {
      slug: 'imker',
      dutch: 'de imker',
      english: 'the beekeeper',
      image: imker,
      audio: '/audio/words/insects/nests-and-honey/imker.m4a',
      credit: {
        author: 'Michael Gäbler',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: 'Beekeeper_keeping_bees.jpg',
      },
    },
    {
      slug: 'bijenkoningin',
      dutch: 'de bijenkoningin',
      english: 'the queen bee',
      image: bijenkoningin,
      audio: '/audio/words/insects/nests-and-honey/bijenkoningin.m4a',
      credit: {
        author: 'Scott Bauer, USDA Agricultural Research Service',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Apis_mellifera_scutellata_1355021.jpg',
      },
    },
    {
      slug: 'werkbij',
      dutch: 'de werkbij',
      english: 'the worker bee',
      image: werkbij,
      audio: '/audio/words/insects/nests-and-honey/werkbij.m4a',
      credit: {
        author: 'Todd Huffman from Phoenix, AZ',
        license: 'CC BY 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
        file: 'Todd_Huffman_-_Lattice_(by).jpg',
      },
    },
    {
      slug: 'dar',
      dutch: 'de dar',
      english: 'the drone',
      image: dar,
      audio: '/audio/words/insects/nests-and-honey/dar.m4a',
      credit: {
        author: 'Guillaume Pelletier',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Drone_bee_(32-image_macro_stack).jpg',
      },
    },
    {
      slug: 'zwerm',
      dutch: 'de zwerm',
      english: 'the swarm',
      image: zwerm,
      audio: '/audio/words/insects/nests-and-honey/zwerm.m4a',
      credit: {
        author: 'Famartin',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: '2024-04-27 12 46 54 A honey bee swarm on a fir tree branch along Aquetong Lane in the Mountainview section of Ewing Township, Mercer County, New Jersey.jpg',
      },
    },
    {
      slug: 'wespennest',
      dutch: 'het wespennest',
      english: "the wasps' nest",
      image: wespennest,
      audio: '/audio/words/insects/nests-and-honey/wespennest.m4a',
      credit: {
        author: 'Alex Blokha',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Wasp nest, Dnipro, Ukraine.jpg',
      },
    },
    {
      slug: 'mierenhoop',
      dutch: 'de mierenhoop',
      english: 'the anthill',
      image: mierenhoop,
      audio: '/audio/words/insects/nests-and-honey/mierenhoop.m4a',
      credit: {
        author: 'Tholst93',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Large red wood anthill against a spruce tree at Stursbøl plantage. (73972).jpg',
      },
    },
    {
      slug: 'termietenheuvel',
      dutch: 'de termietenheuvel',
      english: 'the termite mound',
      image: termietenheuvel,
      audio: '/audio/words/insects/nests-and-honey/termietenheuvel.m4a',
      credit: {
        author: 'Hansjoerg Morandell from Bolzano, Italy',
        license: 'CC BY 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
        file: 'Litchfield_National_Park-03.jpg',
      },
    },
    {
      slug: 'gal',
      dutch: 'de gal',
      english: 'the gall',
      image: gal,
      audio: '/audio/words/insects/nests-and-honey/gal.m4a',
      credit: {
        author: 'Rosser1954 Roger Griffith',
        license: 'Public domain',
        licenseUrl: '',
        file: 'Andricus_lignicola_-_Cola-nut_Gall.JPG',
      },
    },
    {
      slug: 'zijde',
      dutch: 'de zijde',
      english: 'the silk',
      image: zijde,
      audio: '/audio/words/insects/nests-and-honey/zijde.m4a',
      credit: {
        author: 'Boonlert Aroonpiboon',
        license: 'CC BY 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/4.0',
        file: 'Silk fiber.jpg',
      },
    },
    {
      slug: 'insectenhotel',
      dutch: 'het insectenhotel',
      english: 'the insect hotel',
      image: insectenhotel,
      audio: '/audio/words/insects/nests-and-honey/insectenhotel.m4a',
      credit: {
        author: 'Obscurasky',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Insect_house.jpg',
      },
    },
  ],
};
