// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import apollovlinder from './apollovlinder.webp';
import argusvlinder from './argusvlinder.webp';
import atalanta from './atalanta.webp';
import bontZandoogje from './bont-zandoogje.webp';
import boomblauwtje from './boomblauwtje.webp';
import bruinZandoogje from './bruin-zandoogje.webp';
import citroenvlinder from './citroenvlinder.webp';
import dagpauwoog from './dagpauwoog.webp';
import distelvlinder from './distelvlinder.webp';
import gehakkeldeAurelia from './gehakkelde-aurelia.webp';
import groentje from './groentje.webp';
import grootKoolwitje from './groot-koolwitje.webp';
import groteWeerschijnvlinder from './grote-weerschijnvlinder.webp';
import hooibeestje from './hooibeestje.webp';
import icarusblauwtje from './icarusblauwtje.webp';
import keizersmantel from './keizersmantel.webp';
import kleinGeaderdWitje from './klein-geaderd-witje.webp';
import kleinKoolwitje from './klein-koolwitje.webp';
import kleineIjsvogelvlinder from './kleine-ijsvogelvlinder.webp';
import kleineVos from './kleine-vos.webp';
import kleineVuurvlinder from './kleine-vuurvlinder.webp';
import koevinkje from './koevinkje.webp';
import koninginnenpage from './koninginnenpage.webp';
import landkaartje from './landkaartje.webp';
import monarchvlinder from './monarchvlinder.webp';
import oranjeLuzernevlinder from './oranje-luzernevlinder.webp';
import oranjetipje from './oranjetipje.webp';
import rouwmantel from './rouwmantel.webp';
import zwartsprietdikkopje from './zwartsprietdikkopje.webp';

export const butterflies: WordTopic = {
  slug: 'butterflies',
  title: 'Butterflies',
  dutchTitle: 'Dagvlinders',
  description: 'The ones that fly by day, from het koolwitje to de koninginnenpage.',
  entries: [
    {
      slug: 'dagpauwoog',
      dutch: 'de dagpauwoog',
      english: 'the peacock butterfly',
      image: dagpauwoog,
      audio: '/audio/words/insects/butterflies/dagpauwoog.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Peacock_butterfly_(Aglais_io)_2.jpg',
      },
    },
    {
      slug: 'atalanta',
      dutch: 'de atalanta',
      english: 'the red admiral',
      image: atalanta,
      audio: '/audio/words/insects/butterflies/atalanta.m4a',
      credit: {
        author: 'Christian Fischer',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'VanessaAtalanta_Closeup.jpg',
      },
    },
    {
      slug: 'kleine-vos',
      dutch: 'de kleine vos',
      english: 'the small tortoiseshell',
      image: kleineVos,
      audio: '/audio/words/insects/butterflies/kleine-vos.m4a',
      credit: {
        author: 'Jörg Hempel',
        license: 'CC BY-SA 3.0 de',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/de/deed.en',
        file: 'Aglais_urticae_LC0310.jpg',
      },
    },
    {
      slug: 'citroenvlinder',
      dutch: 'de citroenvlinder',
      english: 'the brimstone',
      image: citroenvlinder,
      audio: '/audio/words/insects/butterflies/citroenvlinder.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Common_brimstone_butterfly_(Gonepteryx_rhamni)_male_in_flight.jpg',
      },
    },
    {
      slug: 'groot-koolwitje',
      dutch: 'het groot koolwitje',
      english: 'the large white',
      image: grootKoolwitje,
      audio: '/audio/words/insects/butterflies/groot-koolwitje.m4a',
      credit: {
        author: 'gailhampshire from Cradley, Malvern, U.K',
        license: 'CC BY 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
        file: 'Large_White._Pieris_brassicae_-_Flickr_-_gailhampshire_(1).jpg',
      },
    },
    {
      slug: 'klein-koolwitje',
      dutch: 'het klein koolwitje',
      english: 'the small white',
      image: kleinKoolwitje,
      audio: '/audio/words/insects/butterflies/klein-koolwitje.m4a',
      credit: {
        author: 'Sarefo',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Pieris.rapae.mounted.jpg',
      },
    },
    {
      slug: 'klein-geaderd-witje',
      dutch: 'het klein geaderd witje',
      english: 'the green-veined white',
      image: kleinGeaderdWitje,
      audio: '/audio/words/insects/butterflies/klein-geaderd-witje.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Green-veined_white_butterfly_(Pieris_napi)_topside.JPG',
      },
    },
    {
      slug: 'oranjetipje',
      dutch: 'het oranjetipje',
      english: 'the orange tip',
      image: oranjetipje,
      audio: '/audio/words/insects/butterflies/oranjetipje.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Orange_tip_(Anthocharis_cardamines)_male_Geiranger.jpg',
      },
    },
    {
      slug: 'distelvlinder',
      dutch: 'de distelvlinder',
      english: 'the painted lady',
      image: distelvlinder,
      audio: '/audio/words/insects/butterflies/distelvlinder.m4a',
      credit: {
        author: 'Jean-Pol GRANDMONT',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: '0_Belle-dame_(Vanessa_cardui)_-_Echinacea_purpurea_-_Havré_(3).jpg',
      },
    },
    {
      slug: 'koninginnenpage',
      dutch: 'de koninginnenpage',
      english: 'the swallowtail',
      image: koninginnenpage,
      audio: '/audio/words/insects/butterflies/koninginnenpage.m4a',
      credit: {
        author: 'Entomolo',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'PapilioMachaon2016_001.JPG',
      },
    },
    {
      slug: 'gehakkelde-aurelia',
      dutch: 'de gehakkelde aurelia',
      english: 'the comma',
      image: gehakkeldeAurelia,
      audio: '/audio/words/insects/butterflies/gehakkelde-aurelia.m4a',
      credit: {
        author: 'Quartl',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Polygonia_c-album_qtl2.jpg',
      },
    },
    {
      slug: 'landkaartje',
      dutch: 'het landkaartje',
      english: 'the map butterfly',
      image: landkaartje,
      audio: '/audio/words/insects/butterflies/landkaartje.m4a',
      credit: {
        author: 'Jörg Hempel',
        license: 'CC BY-SA 3.0 de',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/de/deed.en',
        file: 'Araschnia_levana_LC0263.jpg',
      },
    },
    {
      slug: 'icarusblauwtje',
      dutch: 'het icarusblauwtje',
      english: 'the common blue',
      image: icarusblauwtje,
      audio: '/audio/words/insects/butterflies/icarusblauwtje.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Common_blue_(Polyommatus_icarus)_male_Turna.jpg',
      },
    },
    {
      slug: 'boomblauwtje',
      dutch: 'het boomblauwtje',
      english: 'the holly blue',
      image: boomblauwtje,
      audio: '/audio/words/insects/butterflies/boomblauwtje.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Holly_blue_(Celastrina_argiolus)_male.jpg',
      },
    },
    {
      slug: 'kleine-vuurvlinder',
      dutch: 'de kleine vuurvlinder',
      english: 'the small copper',
      image: kleineVuurvlinder,
      audio: '/audio/words/insects/butterflies/kleine-vuurvlinder.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Small_copper_(Lycaena_phlaeas_phlaeas)_Extremadura.jpg',
      },
    },
    {
      slug: 'bont-zandoogje',
      dutch: 'het bont zandoogje',
      english: 'the speckled wood',
      image: bontZandoogje,
      audio: '/audio/words/insects/butterflies/bont-zandoogje.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Speckled_wood_butterfly_(Pararge_aegeria_tircis)_male_2.jpg',
      },
    },
    {
      slug: 'bruin-zandoogje',
      dutch: 'het bruin zandoogje',
      english: 'the meadow brown',
      image: bruinZandoogje,
      audio: '/audio/words/insects/butterflies/bruin-zandoogje.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Meadow_brown_butterfly_(Maniola_jurtina)_female.jpg',
      },
    },
    {
      slug: 'koevinkje',
      dutch: 'het koevinkje',
      english: 'the ringlet',
      image: koevinkje,
      audio: '/audio/words/insects/butterflies/koevinkje.m4a',
      credit: {
        author: 'Ivar Leidus',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Aphantopus_hyperantus_-_Keila.jpg',
      },
    },
    {
      slug: 'hooibeestje',
      dutch: 'het hooibeestje',
      english: 'the small heath',
      image: hooibeestje,
      audio: '/audio/words/insects/butterflies/hooibeestje.m4a',
      credit: {
        author: 'Ivar Leidus',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Coenonympha_pamphilus_-_Kulna.jpg',
      },
    },
    {
      slug: 'argusvlinder',
      dutch: 'de argusvlinder',
      english: 'the wall brown',
      image: argusvlinder,
      audio: '/audio/words/insects/butterflies/argusvlinder.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Wall_(Lasiommata_megera)_male_Italy.jpg',
      },
    },
    {
      slug: 'rouwmantel',
      dutch: 'de rouwmantel',
      english: 'the mourning cloak',
      image: rouwmantel,
      audio: '/audio/words/insects/butterflies/rouwmantel.m4a',
      credit: {
        author: 'Pavel Kirillov from St.Petersburg, Russia',
        license: 'CC BY-SA 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
        file: 'The_Mourning_Cloak_(23369139485).jpg',
      },
    },
    {
      slug: 'keizersmantel',
      dutch: 'de keizersmantel',
      english: 'the silver-washed fritillary',
      image: keizersmantel,
      audio: '/audio/words/insects/butterflies/keizersmantel.m4a',
      credit: {
        author: 'Uoaei1',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Argynnis_paphia_Mitterbach_01.jpg',
      },
    },
    {
      slug: 'grote-weerschijnvlinder',
      dutch: 'de grote weerschijnvlinder',
      english: 'the purple emperor',
      image: groteWeerschijnvlinder,
      audio: '/audio/words/insects/butterflies/grote-weerschijnvlinder.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Purple_emperor_(Apatura_iris)_male.jpg',
      },
    },
    {
      slug: 'kleine-ijsvogelvlinder',
      dutch: 'de kleine ijsvogelvlinder',
      english: 'the white admiral',
      image: kleineIjsvogelvlinder,
      audio: '/audio/words/insects/butterflies/kleine-ijsvogelvlinder.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'White_admiral_(Limenitis_camilla).jpg',
      },
    },
    {
      slug: 'groentje',
      dutch: 'het groentje',
      english: 'the green hairstreak',
      image: groentje,
      audio: '/audio/words/insects/butterflies/groentje.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Green_hairstreak_(Callophrys_rubi)_3.jpg',
      },
    },
    {
      slug: 'zwartsprietdikkopje',
      dutch: 'het zwartsprietdikkopje',
      english: 'the Essex skipper',
      image: zwartsprietdikkopje,
      audio: '/audio/words/insects/butterflies/zwartsprietdikkopje.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Essex_skipper_(Thymelicus_lineola)_male.jpg',
      },
    },
    {
      slug: 'oranje-luzernevlinder',
      dutch: 'de oranje luzernevlinder',
      english: 'the clouded yellow',
      image: oranjeLuzernevlinder,
      audio: '/audio/words/insects/butterflies/oranje-luzernevlinder.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Clouded_yellow_(Colias_croceus)_male_underside_2.jpg',
      },
    },
    {
      slug: 'apollovlinder',
      dutch: 'de apollovlinder',
      english: 'the Apollo',
      image: apollovlinder,
      audio: '/audio/words/insects/butterflies/apollovlinder.m4a',
      credit: {
        author: 'Hinox',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Parnassius_apollo_Pirineus.JPG',
      },
    },
    {
      slug: 'monarchvlinder',
      dutch: 'de monarchvlinder',
      english: 'the monarch',
      image: monarchvlinder,
      audio: '/audio/words/insects/butterflies/monarchvlinder.m4a',
      credit: {
        author: 'Photo by and (c)2007 Derek Ramsey (Ram-Man)',
        license: 'GFDL 1.2',
        licenseUrl: 'http://www.gnu.org/licenses/old-licenses/fdl-1.2.html',
        file: 'Monarch_Butterfly_Danaus_plexippus_Male_2664px.jpg',
      },
    },
  ],
};
