// Generated by scripts/generate-word-data.py — see that file to add a word or a topic.
import type { WordTopic } from '@/features/words/types';

import blindeBij from './blinde-bij.webp';
import bromvlieg from './bromvlieg.webp';
import daas from './daas.webp';
import fruitvlieg from './fruitvlieg.webp';
import grijzeVleesvlieg from './grijze-vleesvlieg.webp';
import groeneVleesvlieg from './groene-vleesvlieg.webp';
import hertenluisvlieg from './hertenluisvlieg.webp';
import hommelreus from './hommelreus.webp';
import huisvlieg from './huisvlieg.webp';
import pyjamazweefvlieg from './pyjamazweefvlieg.webp';
import roofvlieg from './roofvlieg.webp';
import stalvlieg from './stalvlieg.webp';
import strontvlieg from './strontvlieg.webp';
import tseetseevlieg from './tseetseevlieg.webp';
import wapenvlieg from './wapenvlieg.webp';
import wolzwever from './wolzwever.webp';
import zweefvlieg from './zweefvlieg.webp';

export const flies: WordTopic = {
  slug: 'flies',
  title: 'Flies',
  dutchTitle: 'Vliegen',
  description: 'Two wings and short antennae: the ones that buzz, hover and bite.',
  entries: [
    {
      slug: 'huisvlieg',
      dutch: 'de huisvlieg',
      english: 'the housefly',
      image: huisvlieg,
      audio: '/audio/words/insects/flies/huisvlieg.m4a',
      credit: {
        author: 'USDAgov',
        license: 'CC BY 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
        file: 'Common_house_fly,_Musca_domestica.jpg',
      },
    },
    {
      slug: 'bromvlieg',
      dutch: 'de bromvlieg',
      english: 'the bluebottle',
      image: bromvlieg,
      audio: '/audio/words/insects/flies/bromvlieg.m4a',
      credit: {
        author: 'TristramBrelstaff',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Calliphora-vomitoria-Bluebottle-fly-20100806a.jpg',
      },
    },
    {
      slug: 'groene-vleesvlieg',
      dutch: 'de groene vleesvlieg',
      english: 'the greenbottle',
      image: groeneVleesvlieg,
      audio: '/audio/words/insects/flies/groene-vleesvlieg.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Common_green_bottle_flies_(Lucilia_sericata)_female_left_and_male_Bürgerpark.jpg',
      },
    },
    {
      slug: 'grijze-vleesvlieg',
      dutch: 'de grijze vleesvlieg',
      english: 'the flesh fly',
      image: grijzeVleesvlieg,
      audio: '/audio/words/insects/flies/grijze-vleesvlieg.m4a',
      credit: {
        author: 'Janet Graham',
        license: 'CC BY 2.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
        file: 'Sarcophaga_carnaria,_Marford_Quarry,_North_Wales,_May_2012_(17167424630).jpg',
      },
    },
    {
      slug: 'fruitvlieg',
      dutch: 'de fruitvlieg',
      english: 'the fruit fly',
      image: fruitvlieg,
      audio: '/audio/words/insects/flies/fruitvlieg.m4a',
      credit: {
        author: 'Sanjay Acharya',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Drosophila_melanogaster_Proboscis.jpg',
      },
    },
    {
      slug: 'zweefvlieg',
      dutch: 'de zweefvlieg',
      english: 'the hoverfly',
      image: zweefvlieg,
      audio: '/audio/words/insects/flies/zweefvlieg.m4a',
      credit: {
        author: 'Ivar Leidus',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Berteroa incana - Syrphus ribesii - Tallinn.jpg',
      },
    },
    {
      slug: 'pyjamazweefvlieg',
      dutch: 'de pyjamazweefvlieg',
      english: 'the marmalade hoverfly',
      image: pyjamazweefvlieg,
      audio: '/audio/words/insects/flies/pyjamazweefvlieg.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Marmalade_hoverfly_(Episyrphus_balteatus)_male_Wengen_2.jpg',
      },
    },
    {
      slug: 'blinde-bij',
      dutch: 'de blinde bij',
      english: 'the drone fly',
      image: blindeBij,
      audio: '/audio/words/insects/flies/blinde-bij.m4a',
      credit: {
        author: 'Stoxastikos',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Eristalis_tenax_Male.jpg',
      },
    },
    {
      slug: 'hommelreus',
      dutch: 'de hommelreus',
      english: 'the bumblebee hoverfly',
      image: hommelreus,
      audio: '/audio/words/insects/flies/hommelreus.m4a',
      credit: {
        author: 'Sandy Rae',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Voluc.bombylans.jpg',
      },
    },
    {
      slug: 'daas',
      dutch: 'de daas',
      english: 'the horsefly',
      image: daas,
      audio: '/audio/words/insects/flies/daas.m4a',
      credit: {
        author: 'Bruce Marlin',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Horse_fly_Tabanus_2.jpg',
      },
    },
    {
      slug: 'stalvlieg',
      dutch: 'de stalvlieg',
      english: 'the stable fly',
      image: stalvlieg,
      audio: '/audio/words/insects/flies/stalvlieg.m4a',
      credit: {
        author: 'User:Fir0002',
        license: 'GFDL 1.2',
        licenseUrl: 'http://www.gnu.org/licenses/old-licenses/fdl-1.2.html',
        file: 'Stomoxys_calcitrans_on_aloe_vera.jpg',
      },
    },
    {
      slug: 'strontvlieg',
      dutch: 'de strontvlieg',
      english: 'the yellow dung fly',
      image: strontvlieg,
      audio: '/audio/words/insects/flies/strontvlieg.m4a',
      credit: {
        author: 'Luc Viatour',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
        file: 'Scatophaga_stercoraria_1_Luc_Viatour.jpg',
      },
    },
    {
      slug: 'wolzwever',
      dutch: 'de wolzwever',
      english: 'the bee-fly',
      image: wolzwever,
      audio: '/audio/words/insects/flies/wolzwever.m4a',
      credit: {
        author: 'Richard Bartz, Munich aka Makro Freak',
        license: 'CC BY-SA 2.5',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
        file: 'Grosser_Wollschweber_Bombylius_major.jpg',
      },
    },
    {
      slug: 'roofvlieg',
      dutch: 'de roofvlieg',
      english: 'the robber fly',
      image: roofvlieg,
      audio: '/audio/words/insects/flies/roofvlieg.m4a',
      credit: {
        author: 'Charles J. Sharp',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Robber_fly_(Promachus_sp.)_female_with_bee_prey_Babadag.jpg',
      },
    },
    {
      slug: 'hertenluisvlieg',
      dutch: 'de hertenluisvlieg',
      english: 'the deer ked',
      image: hertenluisvlieg,
      audio: '/audio/words/insects/flies/hertenluisvlieg.m4a',
      credit: {
        author: 'Kymi',
        license: 'CC BY 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0',
        file: 'Lipoptena_cervi_1.jpg',
      },
    },
    {
      slug: 'wapenvlieg',
      dutch: 'de zwarte wapenvlieg',
      english: 'the black soldier fly',
      image: wapenvlieg,
      audio: '/audio/words/insects/flies/wapenvlieg.m4a',
      credit: {
        author: 'Didier Descouens',
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
        file: 'Hermetia_illucens_MHNT_Fronton.jpg',
      },
    },
    {
      slug: 'tseetseevlieg',
      dutch: 'de tseetseevlieg',
      english: 'the tsetse fly',
      image: tseetseevlieg,
      audio: '/audio/words/insects/flies/tseetseevlieg.m4a',
      credit: {
        author: 'Alan R Walker',
        license: 'CC BY-SA 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
        file: 'Glossina-morsitans.jpg',
      },
    },
  ],
};
